// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: f9ed73bf42663a56c304297f3e4891d114987eafe7470cfd7985aa989c4d88cc
// Version: v0.0.4 (https://github.com/pk910/dynamic-ssz)
package deneb

import (
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *BlobIdentifier) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	fn1 := func(t *BlobIdentifier) (err error) { // *deneb.BlobIdentifier
		// Field #0 'BlockRoot'
		dst = append(dst, t.BlockRoot[:]...)
		// Field #1 'Index'
		dst = sszutils.MarshalUint64(dst, uint64(t.Index))
		return err
	}
	err = fn1(t)
	return dst, err
}
func (t *BlobIdentifier) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

func (t *BlobIdentifier) SizeSSZ() (size int) {
	sfn1 := func(t *BlobIdentifier) (size int) { // *BlobIdentifier
		size = 40
		return size
	}
	return sfn1(t)
}

func (t *BlobIdentifier) UnmarshalSSZ(buf []byte) (err error) {
	fn1 := func(t *BlobIdentifier, buf []byte) (*BlobIdentifier, error) { // *BlobIdentifier
		var err error
		if t == nil {
			t = new(BlobIdentifier)
		}
		buflen := len(buf)
		if buflen < 40 {
			return t, sszutils.ErrUnexpectedEOF
		}
		// Field #0 'BlockRoot'
		copy(t.BlockRoot[:], buf[0:32])
		// Field #1 'Index'
		t.Index = (BlobIndex)(sszutils.UnmarshallUint64(buf[32:40]))
		return t, err
	}
	_, err = fn1(t, buf)
	return err
}

func (t *BlobIdentifier) HashTreeRootWith(hh sszutils.HashWalker) error {
	fn1 := func(t *BlobIdentifier) (err error) { // *deneb.BlobIdentifier
		idx := hh.Index()
		// Field #0 'BlockRoot'
		hh.PutBytes(t.BlockRoot[:])
		// Field #1 'Index'
		hh.PutUint64(uint64(t.Index))
		hh.Merkleize(idx)
		return err
	}
	return fn1(t)
}
func (t *BlobIdentifier) HashTreeRoot() ([32]byte, error) {
	pool := &hasher.FastHasherPool
	hh := pool.Get()
	defer func() {
		pool.Put(hh)
	}()
	if err := t.HashTreeRootWith(hh); err != nil {
		return [32]byte{}, err
	}
	r, _ := hh.HashRoot()
	return r, nil
}
