// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 8359ea5a5cd25797d6ccb6f7b08b8175c54c77732bd5e73d63a6c4bb0424dc0a
// Version: v1.0.1 (https://github.com/pk910/dynamic-ssz)
package deneb

import (
	"github.com/holiman/uint256"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *ExecutionPayloadHeader) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	dstlen := len(dst)
	{ // Field #0 'ParentHash'
		t := t.ParentHash
		limit := 32
		dst = append(dst, []byte(t[:limit])...)
	}
	{ // Field #1 'FeeRecipient'
		t := t.FeeRecipient
		limit := 20
		dst = append(dst, []byte(t[:limit])...)
	}
	{ // Field #2 'StateRoot'
		t := t.StateRoot
		limit := 32
		dst = append(dst, []byte(t[:limit])...)
	}
	{ // Field #3 'ReceiptsRoot'
		t := t.ReceiptsRoot
		limit := 32
		dst = append(dst, []byte(t[:limit])...)
	}
	{ // Field #4 'LogsBloom'
		t := t.LogsBloom
		limit := 256
		dst = append(dst, []byte(t[:limit])...)
	}
	{ // Field #5 'PrevRandao'
		t := t.PrevRandao
		limit := 32
		dst = append(dst, []byte(t[:limit])...)
	}
	{ // Field #6 'BlockNumber'
		t := t.BlockNumber
		dst = sszutils.MarshalUint64(dst, uint64(t))
	}
	{ // Field #7 'GasLimit'
		t := t.GasLimit
		dst = sszutils.MarshalUint64(dst, uint64(t))
	}
	{ // Field #8 'GasUsed'
		t := t.GasUsed
		dst = sszutils.MarshalUint64(dst, uint64(t))
	}
	{ // Field #9 'Timestamp'
		t := t.Timestamp
		dst = sszutils.MarshalUint64(dst, uint64(t))
	}
	// Offset #10 'ExtraData'
	offset10 := len(dst)
	dst = sszutils.MarshalOffset(dst, 0)
	{ // Field #11 'BaseFeePerGas'
		t := t.BaseFeePerGas
		limit := 4
		for i := 0; i < limit; i++ {
			t := t[i]
			dst = sszutils.MarshalUint64(dst, uint64(t))
		}
	}
	{ // Field #12 'BlockHash'
		t := t.BlockHash
		limit := 32
		dst = append(dst, []byte(t[:limit])...)
	}
	{ // Field #13 'TransactionsRoot'
		t := t.TransactionsRoot
		limit := 32
		dst = append(dst, []byte(t[:limit])...)
	}
	{ // Field #14 'WithdrawalsRoot'
		t := t.WithdrawalsRoot
		limit := 32
		dst = append(dst, []byte(t[:limit])...)
	}
	{ // Field #15 'BlobGasUsed'
		t := t.BlobGasUsed
		dst = sszutils.MarshalUint64(dst, uint64(t))
	}
	{ // Field #16 'ExcessBlobGas'
		t := t.ExcessBlobGas
		dst = sszutils.MarshalUint64(dst, uint64(t))
	}
	{ // Dynamic Field #10 'ExtraData'
		sszutils.UpdateOffset(dst[offset10:offset10+4], len(dst)-dstlen)
		t := t.ExtraData
		max := 32
		hasMax := true
		vlen := len(t)
		if hasMax && vlen > int(max) {
			return dst, sszutils.ErrListTooBig
		}
		dst = append(dst, []byte(t[:])...)
	}
	return dst, nil
}

func (t *ExecutionPayloadHeader) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *ExecutionPayloadHeader) SizeSSZ() (size int) {
	// Field #0 'ParentHash' static (32 bytes)
	// Field #1 'FeeRecipient' static (20 bytes)
	// Field #2 'StateRoot' static (32 bytes)
	// Field #3 'ReceiptsRoot' static (32 bytes)
	// Field #4 'LogsBloom' static (256 bytes)
	// Field #5 'PrevRandao' static (32 bytes)
	// Field #6 'BlockNumber' static (8 bytes)
	// Field #7 'GasLimit' static (8 bytes)
	// Field #8 'GasUsed' static (8 bytes)
	// Field #9 'Timestamp' static (8 bytes)
	// Field #10 'ExtraData' offset (4 bytes)
	// Field #11 'BaseFeePerGas' static (32 bytes)
	// Field #12 'BlockHash' static (32 bytes)
	// Field #13 'TransactionsRoot' static (32 bytes)
	// Field #14 'WithdrawalsRoot' static (32 bytes)
	// Field #15 'BlobGasUsed' static (8 bytes)
	// Field #16 'ExcessBlobGas' static (8 bytes)
	size += 584
	{ // Dynamic field #10 'ExtraData'
		size += len(t.ExtraData)
	}
	return size
}

func (t *ExecutionPayloadHeader) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 584 {
		return sszutils.ErrUnexpectedEOF
	}
	{ // Field #0 'ParentHash' (static)
		buf := buf[0:32]
		copy(t.ParentHash[:], buf)
	}
	{ // Field #1 'FeeRecipient' (static)
		buf := buf[32:52]
		copy(t.FeeRecipient[:], buf)
	}
	{ // Field #2 'StateRoot' (static)
		buf := buf[52:84]
		copy(t.StateRoot[:], buf)
	}
	{ // Field #3 'ReceiptsRoot' (static)
		buf := buf[84:116]
		copy(t.ReceiptsRoot[:], buf)
	}
	{ // Field #4 'LogsBloom' (static)
		buf := buf[116:372]
		copy(t.LogsBloom[:], buf)
	}
	{ // Field #5 'PrevRandao' (static)
		buf := buf[372:404]
		copy(t.PrevRandao[:], buf)
	}
	{ // Field #6 'BlockNumber' (static)
		buf := buf[404:412]
		t.BlockNumber = uint64(sszutils.UnmarshallUint64(buf))
	}
	{ // Field #7 'GasLimit' (static)
		buf := buf[412:420]
		t.GasLimit = uint64(sszutils.UnmarshallUint64(buf))
	}
	{ // Field #8 'GasUsed' (static)
		buf := buf[420:428]
		t.GasUsed = uint64(sszutils.UnmarshallUint64(buf))
	}
	{ // Field #9 'Timestamp' (static)
		buf := buf[428:436]
		t.Timestamp = uint64(sszutils.UnmarshallUint64(buf))
	}
	// Field #10 'ExtraData' (offset)
	offset10 := int(sszutils.UnmarshallUint32(buf[436:440]))
	if offset10 < 584 || offset10 > buflen {
		return sszutils.ErrOffset
	}
	{ // Field #11 'BaseFeePerGas' (static)
		buf := buf[440:472]
		val1 := t.BaseFeePerGas
		if val1 == nil {
			val1 = new(uint256.Int)
		}
		for i := 0; i < 4; i++ {
			buf := buf[8*i : 8*(i+1)]
			val1[i] = uint64(sszutils.UnmarshallUint64(buf))
		}
		t.BaseFeePerGas = val1
	}
	{ // Field #12 'BlockHash' (static)
		buf := buf[472:504]
		copy(t.BlockHash[:], buf)
	}
	{ // Field #13 'TransactionsRoot' (static)
		buf := buf[504:536]
		copy(t.TransactionsRoot[:], buf)
	}
	{ // Field #14 'WithdrawalsRoot' (static)
		buf := buf[536:568]
		copy(t.WithdrawalsRoot[:], buf)
	}
	{ // Field #15 'BlobGasUsed' (static)
		buf := buf[568:576]
		t.BlobGasUsed = uint64(sszutils.UnmarshallUint64(buf))
	}
	{ // Field #16 'ExcessBlobGas' (static)
		buf := buf[576:584]
		t.ExcessBlobGas = uint64(sszutils.UnmarshallUint64(buf))
	}
	{ // Field #10 'ExtraData' (dynamic)
		buf := buf[offset10:]
		val2 := t.ExtraData
		limit := len(buf)
		if len(val2) < limit {
			val2 = make([]byte, limit)
		} else if len(val2) > limit {
			val2 = val2[:limit]
		}
		copy(val2[:], buf)
		t.ExtraData = val2
	}
	return nil
}

func (t *ExecutionPayloadHeader) HashTreeRootWith(hh sszutils.HashWalker) error {
	idx := hh.Index()
	{ // Field #0 'ParentHash'
		t := t.ParentHash
		idx := hh.Index()
		hh.PutBytes(t[:])
		hh.Merkleize(idx)
	}
	{ // Field #1 'FeeRecipient'
		t := t.FeeRecipient
		idx := hh.Index()
		hh.PutBytes(t[:])
		hh.Merkleize(idx)
	}
	{ // Field #2 'StateRoot'
		t := t.StateRoot
		idx := hh.Index()
		hh.PutBytes(t[:])
		hh.Merkleize(idx)
	}
	{ // Field #3 'ReceiptsRoot'
		t := t.ReceiptsRoot
		idx := hh.Index()
		hh.PutBytes(t[:])
		hh.Merkleize(idx)
	}
	{ // Field #4 'LogsBloom'
		t := t.LogsBloom
		idx := hh.Index()
		hh.PutBytes(t[:])
		hh.Merkleize(idx)
	}
	{ // Field #5 'PrevRandao'
		t := t.PrevRandao
		idx := hh.Index()
		hh.PutBytes(t[:])
		hh.Merkleize(idx)
	}
	{ // Field #6 'BlockNumber'
		t := t.BlockNumber
		hh.PutUint64(uint64(t))
	}
	{ // Field #7 'GasLimit'
		t := t.GasLimit
		hh.PutUint64(uint64(t))
	}
	{ // Field #8 'GasUsed'
		t := t.GasUsed
		hh.PutUint64(uint64(t))
	}
	{ // Field #9 'Timestamp'
		t := t.Timestamp
		hh.PutUint64(uint64(t))
	}
	{ // Field #10 'ExtraData'
		t := t.ExtraData
		idx := hh.Index()
		vlen := uint64(len(t))
		hh.PutBytes(t[:])
		limit := sszutils.CalculateLimit(32, vlen, 1)
		hh.MerkleizeWithMixin(idx, vlen, limit)
	}
	{ // Field #11 'BaseFeePerGas'
		t := t.BaseFeePerGas
		vlen := len(t)
		for i := 0; i < 4; i++ {
			var val1 uint64
			if i < vlen {
				val1 = t[i]
			}
			hh.AppendUint64(uint64(val1))
		}
	}
	{ // Field #12 'BlockHash'
		t := t.BlockHash
		idx := hh.Index()
		hh.PutBytes(t[:])
		hh.Merkleize(idx)
	}
	{ // Field #13 'TransactionsRoot'
		t := t.TransactionsRoot
		idx := hh.Index()
		hh.PutBytes(t[:])
		hh.Merkleize(idx)
	}
	{ // Field #14 'WithdrawalsRoot'
		t := t.WithdrawalsRoot
		idx := hh.Index()
		hh.PutBytes(t[:])
		hh.Merkleize(idx)
	}
	{ // Field #15 'BlobGasUsed'
		t := t.BlobGasUsed
		hh.PutUint64(uint64(t))
	}
	{ // Field #16 'ExcessBlobGas'
		t := t.ExcessBlobGas
		hh.PutUint64(uint64(t))
	}
	hh.Merkleize(idx)
	return nil
}

func (t *ExecutionPayloadHeader) HashTreeRoot() ([32]byte, error) {
	pool := &hasher.FastHasherPool
	hh := pool.Get()
	defer func() {
		pool.Put(hh)
	}()
	if err := t.HashTreeRootWith(hh); err != nil {
		return [32]byte{}, err
	}
	r, _ := hh.HashRoot()
	return r, nil
}
