// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: d2fa6f0b4ceb4b107289835b7633522f937e48ed681c6f6ad260f2ecf988d314
// Version: v0.0.4 (https://github.com/pk910/dynamic-ssz)
package deneb

import (
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *SignedBeaconBlock) MarshalSSZDyn(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	fn1 := func(t *BeaconBlock) (err error) { // *deneb.BeaconBlock
		dst, err = t.MarshalSSZDyn(ds, dst)
		return err
	}
	fn2 := func(t *SignedBeaconBlock) (err error) { // *deneb.SignedBeaconBlock
		dstlen := len(dst)
		// Offset #0 'Message'
		offset0 := len(dst)
		dst = sszutils.MarshalOffset(dst, 0)
		// Field #1 'Signature'
		dst = append(dst, t.Signature[:]...)
		// Dynamic Field #0 'Message'
		sszutils.UpdateOffset(dst[offset0:offset0+4], len(dst)-dstlen)
		if err = fn1(t.Message); err != nil {
			return err
		}
		return err
	}
	err = fn2(t)
	return dst, err
}
func (t *SignedBeaconBlock) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *SignedBeaconBlock) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	return t.MarshalSSZDyn(dynssz.GetGlobalDynSsz(), buf)
}

func (t *SignedBeaconBlock) SizeSSZDyn(ds sszutils.DynamicSpecs) (size int) {
	sfn1 := func(t *BeaconBlock) (size int) { // *BeaconBlock
		size = t.SizeSSZDyn(ds)
		return size
	}
	sfn2 := func(t *SignedBeaconBlock) (size int) { // *SignedBeaconBlock
		size = 96
		size += 4 + sfn1(t.Message)
		return size
	}
	return sfn2(t)
}
func (t *SignedBeaconBlock) SizeSSZ() (size int) {
	return t.SizeSSZDyn(dynssz.GetGlobalDynSsz())
}

func (t *SignedBeaconBlock) UnmarshalSSZDyn(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	fn1 := func(t *BeaconBlock, buf []byte) (*BeaconBlock, error) { // *BeaconBlock
		var err error
		if t == nil {
			t = new(BeaconBlock)
		}
		err = t.UnmarshalSSZDyn(ds, buf)
		return t, err
	}
	fn2 := func(t *SignedBeaconBlock, buf []byte) (*SignedBeaconBlock, error) { // *SignedBeaconBlock
		var err error
		if t == nil {
			t = new(SignedBeaconBlock)
		}
		bufpos := 100
		buflen := len(buf)
		if buflen < 100 {
			return t, sszutils.ErrUnexpectedEOF
		}
		// Read offset #0 'Message'
		offset0 := int(sszutils.ReadOffset(buf[0:4]))
		// Field #1 'Signature'
		copy(t.Signature[:], buf[4:100])
		// Dynamic Field #0 'Message'
		if offset0 < bufpos {
			return t, sszutils.ErrOffset
		}
		{
			fieldSlice := buf[offset0:]
			if t.Message, err = fn1(t.Message, fieldSlice); err != nil {
				return t, err
			}
			bufpos += len(fieldSlice)
		}
		return t, err
	}
	_, err = fn2(t, buf)
	return err
}
func (t *SignedBeaconBlock) UnmarshalSSZ(buf []byte) (err error) {
	return t.UnmarshalSSZDyn(dynssz.GetGlobalDynSsz(), buf)
}

func (t *SignedBeaconBlock) HashTreeRootWithDyn(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	fn1 := func(t *BeaconBlock) (err error) { // *deneb.BeaconBlock
		err = t.HashTreeRootWithDyn(ds, hh)
		return err
	}
	fn2 := func(t *SignedBeaconBlock) (err error) { // *deneb.SignedBeaconBlock
		idx := hh.Index()
		// Field #0 'Message'
		if err = fn1(t.Message); err != nil {
			return err
		}
		// Field #1 'Signature'
		hh.PutBytes(t.Signature[:])
		hh.Merkleize(idx)
		return err
	}
	return fn2(t)
}
func (t *SignedBeaconBlock) HashTreeRootDyn(ds sszutils.DynamicSpecs) ([32]byte, error) {
	pool := &hasher.FastHasherPool
	hh := pool.Get()
	defer func() {
		pool.Put(hh)
	}()
	if err := t.HashTreeRootWithDyn(ds, hh); err != nil {
		return [32]byte{}, err
	}
	r, _ := hh.HashRoot()
	return r, nil
}
func (t *SignedBeaconBlock) HashTreeRootWith(hh sszutils.HashWalker) error {
	return t.HashTreeRootWithDyn(dynssz.GetGlobalDynSsz(), hh)
}
func (t *SignedBeaconBlock) HashTreeRoot() ([32]byte, error) {
	pool := &hasher.FastHasherPool
	hh := pool.Get()
	defer func() {
		pool.Put(hh)
	}()
	if err := t.HashTreeRootWithDyn(dynssz.GetGlobalDynSsz(), hh); err != nil {
		return [32]byte{}, err
	}
	r, _ := hh.HashRoot()
	return r, nil
}
