// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 3da3bcf2804fef44aa986348f94d532887200bada6c58d0fbbbb6b7f00ae6904
// Version: v1.1.0 (https://github.com/pk910/dynamic-ssz)
package deneb

import (
	"github.com/attestantio/go-eth2-client/spec/deneb"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *BlockContents) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *BlockContents) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(BlockContents)
	}
	dstlen := len(dst)
	// Offset #0 'Block'
	offset0 := len(dst)
	dst = sszutils.MarshalOffset(dst, 0)
	// Offset #1 'KZGProofs'
	offset1 := len(dst)
	dst = sszutils.MarshalOffset(dst, 0)
	// Offset #2 'Blobs'
	offset2 := len(dst)
	dst = sszutils.MarshalOffset(dst, 0)
	{ // Dynamic Field #0 'Block'
		sszutils.UpdateOffset(dst[offset0:offset0+4], len(dst)-dstlen)
		t := t.Block
		if t == nil {
			t = new(deneb.BeaconBlock)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return dst, err
		}
	}
	{ // Dynamic Field #1 'KZGProofs'
		sszutils.UpdateOffset(dst[offset1:offset1+4], len(dst)-dstlen)
		t := t.KZGProofs
		vlen := len(t)
		if vlen > 4096 {
			return dst, sszutils.ErrListTooBig
		}
		for i := 0; i < vlen; i++ {
			dst = append(dst, []byte(t[i][:48])...)
		}
	}
	{ // Dynamic Field #2 'Blobs'
		sszutils.UpdateOffset(dst[offset2:offset2+4], len(dst)-dstlen)
		t := t.Blobs
		vlen := len(t)
		if vlen > 4096 {
			return dst, sszutils.ErrListTooBig
		}
		for i := 0; i < vlen; i++ {
			dst = append(dst, []byte(t[i][:131072])...)
		}
	}
	return dst, nil
}

func (t *BlockContents) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 12 {
		return sszutils.ErrUnexpectedEOF
	}
	// Field #0 'Block' (offset)
	offset0 := int(sszutils.UnmarshallUint32(buf[0:4]))
	if offset0 != 12 {
		return sszutils.ErrOffset
	}
	// Field #1 'KZGProofs' (offset)
	offset1 := int(sszutils.UnmarshallUint32(buf[4:8]))
	if offset1 < offset0 || offset1 > buflen {
		return sszutils.ErrOffset
	}
	// Field #2 'Blobs' (offset)
	offset2 := int(sszutils.UnmarshallUint32(buf[8:12]))
	if offset2 < offset1 || offset2 > buflen {
		return sszutils.ErrOffset
	}
	{ // Field #0 'Block' (dynamic)
		buf := buf[offset0:offset1]
		val1 := t.Block
		if val1 == nil {
			val1 = new(deneb.BeaconBlock)
		}
		if err = val1.UnmarshalSSZ(buf); err != nil {
			return err
		}
		t.Block = val1
	}
	{ // Field #1 'KZGProofs' (dynamic)
		buf := buf[offset1:offset2]
		val2 := t.KZGProofs
		itemCount := len(buf) / 48
		if len(buf)%48 != 0 {
			return sszutils.ErrUnexpectedEOF
		}
		val2 = sszutils.ExpandSlice(val2, itemCount)
		for i := 0; i < itemCount; i++ {
			buf := buf[48*i : 48*(i+1)]
			copy(val2[i][:], buf)
		}
		t.KZGProofs = val2
	}
	{ // Field #2 'Blobs' (dynamic)
		buf := buf[offset2:]
		val3 := t.Blobs
		itemCount := len(buf) / 131072
		if len(buf)%131072 != 0 {
			return sszutils.ErrUnexpectedEOF
		}
		val3 = sszutils.ExpandSlice(val3, itemCount)
		for i := 0; i < itemCount; i++ {
			buf := buf[131072*i : 131072*(i+1)]
			copy(val3[i][:], buf)
		}
		t.Blobs = val3
	}
	return nil
}

func (t *BlockContents) SizeSSZ() (size int) {
	if t == nil {
		t = new(BlockContents)
	}
	// Field #0 'Block' offset (4 bytes)
	// Field #1 'KZGProofs' offset (4 bytes)
	// Field #2 'Blobs' offset (4 bytes)
	size += 12
	{ // Dynamic field #0 'Block'
		size += t.Block.SizeSSZ()
	}
	{ // Dynamic field #1 'KZGProofs'
		size += len(t.KZGProofs) * 48
	}
	{ // Dynamic field #2 'Blobs'
		size += len(t.Blobs) * 131072
	}
	return size
}

func (t *BlockContents) HashTreeRoot() ([32]byte, error) {
	pool := &hasher.FastHasherPool
	hh := pool.Get()
	defer func() {
		pool.Put(hh)
	}()
	if err := t.HashTreeRootWith(hh); err != nil {
		return [32]byte{}, err
	}
	r, _ := hh.HashRoot()
	return r, nil
}
func (t *BlockContents) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(BlockContents)
	}
	idx := hh.Index()
	{ // Field #0 'Block'
		t := t.Block
		if t == nil {
			t = new(deneb.BeaconBlock)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return err
		}
	}
	{ // Field #1 'KZGProofs'
		t := t.KZGProofs
		vlen := uint64(len(t))
		if vlen > 4096 {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		for i := 0; i < int(vlen); i++ {
			hh.PutBytes(t[i][:48])
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(4096, vlen, 32))
	}
	{ // Field #2 'Blobs'
		t := t.Blobs
		vlen := uint64(len(t))
		if vlen > 4096 {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		for i := 0; i < int(vlen); i++ {
			hh.PutBytes(t[i][:131072])
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(4096, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}

