// Code generated by fastssz. DO NOT EDIT.
// Hash: cb2f1c63717d30324163608065e759ce532e3cf10373eb26de9e3dc4f0553100
// Version: 0.1.3
package deneb

import (
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the SignedBlindedBlobSidecar object
func (s *SignedBlindedBlobSidecar) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(s)
}

// MarshalSSZTo ssz marshals the SignedBlindedBlobSidecar object to a target array
func (s *SignedBlindedBlobSidecar) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'Message'
	if s.Message == nil {
		s.Message = new(BlindedBlobSidecar)
	}
	if dst, err = s.Message.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (1) 'Signature'
	dst = append(dst, s.Signature[:]...)

	return
}

// UnmarshalSSZ ssz unmarshals the SignedBlindedBlobSidecar object
func (s *SignedBlindedBlobSidecar) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 312 {
		return ssz.ErrSize
	}

	// Field (0) 'Message'
	if s.Message == nil {
		s.Message = new(BlindedBlobSidecar)
	}
	if err = s.Message.UnmarshalSSZ(buf[0:216]); err != nil {
		return err
	}

	// Field (1) 'Signature'
	copy(s.Signature[:], buf[216:312])

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the SignedBlindedBlobSidecar object
func (s *SignedBlindedBlobSidecar) SizeSSZ() (size int) {
	size = 312
	return
}

// HashTreeRoot ssz hashes the SignedBlindedBlobSidecar object
func (s *SignedBlindedBlobSidecar) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(s)
}

// HashTreeRootWith ssz hashes the SignedBlindedBlobSidecar object with a hasher
func (s *SignedBlindedBlobSidecar) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Message'
	if s.Message == nil {
		s.Message = new(BlindedBlobSidecar)
	}
	if err = s.Message.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'Signature'
	hh.PutBytes(s.Signature[:])

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the SignedBlindedBlobSidecar object
func (s *SignedBlindedBlobSidecar) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(s)
}
