// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 4fc23b8ef409bc9977192e2bbecca61f591441bd4d40337a49cbad76335aaaa4
// Version: v0.0.4 (https://github.com/pk910/dynamic-ssz)
package capella

import (
	"github.com/attestantio/go-eth2-client/spec/capella"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *ExecutionPayloadWithdrawals) MarshalSSZDyn(_ sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	return t.MarshalSSZTo(buf)
}
func (t *ExecutionPayloadWithdrawals) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	fn1 := func(t *capella.Withdrawal) (err error) { // *capella.Withdrawal
		dst, err = t.MarshalSSZTo(dst)
		return err
	}
	fn2 := func(t []*capella.Withdrawal) (err error) { // []*capella.Withdrawal
		vlen := len(t)
		for i := 0; i < vlen; i++ {
			if err = fn1(t[i]); err != nil {
				return err
			}
		}
		return err
	}
	fn3 := func(t *ExecutionPayloadWithdrawals) (err error) { // *capella.ExecutionPayloadWithdrawals
		dstlen := len(dst)
		// Offset #0 'Withdrawals'
		offset0 := len(dst)
		dst = sszutils.MarshalOffset(dst, 0)
		// Dynamic Field #0 'Withdrawals'
		sszutils.UpdateOffset(dst[offset0:offset0+4], len(dst)-dstlen)
		if err = fn2(t.Withdrawals); err != nil {
			return err
		}
		return err
	}
	err = fn3(t)
	return dst, err
}
func (t *ExecutionPayloadWithdrawals) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

func (t *ExecutionPayloadWithdrawals) SizeSSZDyn(_ sszutils.DynamicSpecs) (size int) {
	return t.SizeSSZ()
}
func (t *ExecutionPayloadWithdrawals) SizeSSZ() (size int) {
	sfn1 := func(t []*capella.Withdrawal) (size int) { // []*capella.Withdrawal
		size += len(t) * 44
		return size
	}
	sfn2 := func(t *ExecutionPayloadWithdrawals) (size int) { // *ExecutionPayloadWithdrawals
		size = 0
		size += 4 + sfn1(t.Withdrawals)
		return size
	}
	return sfn2(t)
}

func (t *ExecutionPayloadWithdrawals) UnmarshalSSZDyn(_ sszutils.DynamicSpecs, buf []byte) (err error) {
	return t.UnmarshalSSZ(buf)
}
func (t *ExecutionPayloadWithdrawals) UnmarshalSSZ(buf []byte) (err error) {
	fn1 := func(t *capella.Withdrawal, buf []byte) (*capella.Withdrawal, error) { // *capella.Withdrawal
		var err error
		if t == nil {
			t = new(capella.Withdrawal)
		}
		err = t.UnmarshalSSZ(buf)
		return t, err
	}
	fn2 := func(t []*capella.Withdrawal, buf []byte) ([]*capella.Withdrawal, error) { // []*capella.Withdrawal
		var err error
		buflen := len(buf)
		itemsize := 44
		itemCount := buflen / itemsize
		if buflen%itemsize != 0 {
			return t, sszutils.ErrUnexpectedEOF
		}
		if len(t) < itemCount {
			t = make([]*capella.Withdrawal, itemCount)
		} else {
			t = t[:itemCount]
		}
		for i := 0; i < itemCount; i++ {
			if t[i], err = fn1(t[i], buf[i*itemsize:(i+1)*itemsize]); err != nil {
				return t, err
			}
		}
		return t, err
	}
	fn3 := func(t *ExecutionPayloadWithdrawals, buf []byte) (*ExecutionPayloadWithdrawals, error) { // *ExecutionPayloadWithdrawals
		var err error
		if t == nil {
			t = new(ExecutionPayloadWithdrawals)
		}
		bufpos := 4
		buflen := len(buf)
		if buflen < 4 {
			return t, sszutils.ErrUnexpectedEOF
		}
		// Read offset #0 'Withdrawals'
		offset0 := int(sszutils.ReadOffset(buf[0:4]))
		// Dynamic Field #0 'Withdrawals'
		if offset0 < bufpos {
			return t, sszutils.ErrOffset
		}
		{
			fieldSlice := buf[offset0:]
			if t.Withdrawals, err = fn2(t.Withdrawals, fieldSlice); err != nil {
				return t, err
			}
			bufpos += len(fieldSlice)
		}
		return t, err
	}
	_, err = fn3(t, buf)
	return err
}

func (t *ExecutionPayloadWithdrawals) HashTreeRootWithDyn(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	fn1 := func(t []*capella.Withdrawal) (err error) { // []*capella.Withdrawal:16:MAX_WITHDRAWALS_PER_PAYLOAD
		hasLimit, maxLen, err := ds.ResolveSpecValue("MAX_WITHDRAWALS_PER_PAYLOAD")
		if err != nil {
			return err
		}
		if !hasLimit {
			maxLen = 16
		}
		vlen := len(t)
		if vlen > int(maxLen) {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		for i := 0; i < vlen; i++ {
			if err = t[i].HashTreeRootWith(hh); err != nil {
				return err
			}
		}
		limit := uint64(maxLen)
		if (uint64(hh.Index()-idx)+31)/32 > limit {
			return sszutils.ErrListTooBig
		}
		hh.MerkleizeWithMixin(idx, uint64(vlen), limit)
		return err
	}
	fn2 := func(t *ExecutionPayloadWithdrawals) (err error) { // *capella.ExecutionPayloadWithdrawals
		idx := hh.Index()
		// Field #0 'Withdrawals'
		if err = fn1(t.Withdrawals); err != nil {
			return err
		}
		hh.Merkleize(idx)
		return err
	}
	return fn2(t)
}
func (t *ExecutionPayloadWithdrawals) HashTreeRootDyn(ds sszutils.DynamicSpecs) ([32]byte, error) {
	pool := &hasher.FastHasherPool
	hh := pool.Get()
	defer func() {
		pool.Put(hh)
	}()
	if err := t.HashTreeRootWithDyn(ds, hh); err != nil {
		return [32]byte{}, err
	}
	r, _ := hh.HashRoot()
	return r, nil
}
func (t *ExecutionPayloadWithdrawals) HashTreeRootWith(hh sszutils.HashWalker) error {
	return t.HashTreeRootWithDyn(dynssz.GetGlobalDynSsz(), hh)
}
func (t *ExecutionPayloadWithdrawals) HashTreeRoot() ([32]byte, error) {
	pool := &hasher.FastHasherPool
	hh := pool.Get()
	defer func() {
		pool.Put(hh)
	}()
	if err := t.HashTreeRootWithDyn(dynssz.GetGlobalDynSsz(), hh); err != nil {
		return [32]byte{}, err
	}
	r, _ := hh.HashRoot()
	return r, nil
}
