// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: a266205cccc225d4a9dfa83e77f5e7a7659af20158f8013913325bc3321f3c27
// Version: v1.3.1 (https://github.com/pk910/dynamic-ssz)
package capella

import (
	"encoding/binary"

	"github.com/attestantio/go-eth2-client/spec/capella"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

// MarshalSSZ marshals the *ExecutionPayloadWithdrawals to SSZ-encoded bytes.
func (t *ExecutionPayloadWithdrawals) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *ExecutionPayloadWithdrawals to SSZ-encoded bytes, appending to the provided buffer.
func (t *ExecutionPayloadWithdrawals) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(ExecutionPayloadWithdrawals)
	}
	dstlen := len(dst)
	// Offset Field #0 'Withdrawals'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #0 'Withdrawals'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.Withdrawals
		vlen := len(t)
		if vlen > 16 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 16), "Withdrawals")
		}
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(capella.Withdrawal)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "Withdrawals[%d]", idx1)
			}
		}
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *ExecutionPayloadWithdrawals from SSZ-encoded bytes.
func (t *ExecutionPayloadWithdrawals) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 4 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 4)
	}
	// Field #0 'Withdrawals' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 4 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 4), "Withdrawals:o")
	}
	{ // Field #0 'Withdrawals' (dynamic)
		buf := buf[offset0:]
		val1 := t.Withdrawals
		itemCount := len(buf) / 44
		if len(buf)%44 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 44), "Withdrawals")
		}
		if itemCount > 16 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 16), "Withdrawals")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		for idx1 := range itemCount {
			if val1[idx1] == nil {
				val1[idx1] = new(capella.Withdrawal)
			}
			buf := buf[44*idx1 : 44*(idx1+1)]
			if err = val1[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "Withdrawals[%d]", idx1)
			}
		}
		t.Withdrawals = val1
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *ExecutionPayloadWithdrawals.
func (t *ExecutionPayloadWithdrawals) SizeSSZ() (size int) {
	if t == nil {
		t = new(ExecutionPayloadWithdrawals)
	}
	// Field #0 'Withdrawals' offset (4 bytes)
	size += 4
	{ // Dynamic field #0 'Withdrawals'
		size += len(t.Withdrawals) * 44
	}
	return size
}

// HashTreeRoot computes the SSZ hash tree root of the *ExecutionPayloadWithdrawals.
func (t *ExecutionPayloadWithdrawals) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *ExecutionPayloadWithdrawals using the given hash walker.
func (t *ExecutionPayloadWithdrawals) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(ExecutionPayloadWithdrawals)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Withdrawals'
		t := t.Withdrawals
		vlen := uint64(len(t))
		if vlen > 16 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 16), "Withdrawals")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			t := t[idx1]
			if t == nil {
				t = new(capella.Withdrawal)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "Withdrawals[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(16, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}
