// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 5ae6421317e05fcc9c6853f8e312b2506afdac11e70cec3efebd75a41a56a7eb
// Version: v0.0.4 (https://github.com/pk910/dynamic-ssz)
package altair

import (
	"github.com/attestantio/go-eth2-client/spec/phase0"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *SyncCommitteeMessage) MarshalSSZDyn(_ sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	return t.MarshalSSZTo(buf)
}
func (t *SyncCommitteeMessage) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	fn1 := func(t *SyncCommitteeMessage) (err error) { // *altair.SyncCommitteeMessage
		// Field #0 'Slot'
		dst = sszutils.MarshalUint64(dst, uint64(t.Slot))
		// Field #1 'BeaconBlockRoot'
		dst = append(dst, t.BeaconBlockRoot[:]...)
		// Field #2 'ValidatorIndex'
		dst = sszutils.MarshalUint64(dst, uint64(t.ValidatorIndex))
		// Field #3 'Signature'
		dst = append(dst, t.Signature[:]...)
		return err
	}
	err = fn1(t)
	return dst, err
}
func (t *SyncCommitteeMessage) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

func (t *SyncCommitteeMessage) SizeSSZDyn(_ sszutils.DynamicSpecs) (size int) {
	return t.SizeSSZ()
}
func (t *SyncCommitteeMessage) SizeSSZ() (size int) {
	sfn1 := func(t *SyncCommitteeMessage) (size int) { // *SyncCommitteeMessage
		size = 144
		return size
	}
	return sfn1(t)
}

func (t *SyncCommitteeMessage) UnmarshalSSZDyn(_ sszutils.DynamicSpecs, buf []byte) (err error) {
	return t.UnmarshalSSZ(buf)
}
func (t *SyncCommitteeMessage) UnmarshalSSZ(buf []byte) (err error) {
	fn1 := func(t *SyncCommitteeMessage, buf []byte) (*SyncCommitteeMessage, error) { // *SyncCommitteeMessage
		var err error
		if t == nil {
			t = new(SyncCommitteeMessage)
		}
		buflen := len(buf)
		if buflen < 144 {
			return t, sszutils.ErrUnexpectedEOF
		}
		// Field #0 'Slot'
		t.Slot = (phase0.Slot)(sszutils.UnmarshallUint64(buf[0:8]))
		// Field #1 'BeaconBlockRoot'
		copy(t.BeaconBlockRoot[:], buf[8:40])
		// Field #2 'ValidatorIndex'
		t.ValidatorIndex = (phase0.ValidatorIndex)(sszutils.UnmarshallUint64(buf[40:48]))
		// Field #3 'Signature'
		copy(t.Signature[:], buf[48:144])
		return t, err
	}
	_, err = fn1(t, buf)
	return err
}

func (t *SyncCommitteeMessage) HashTreeRootWithDyn(_ sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	return t.HashTreeRootWith(hh)
}
func (t *SyncCommitteeMessage) HashTreeRootWith(hh sszutils.HashWalker) error {
	fn1 := func(t *SyncCommitteeMessage) (err error) { // *altair.SyncCommitteeMessage
		idx := hh.Index()
		// Field #0 'Slot'
		hh.PutUint64(uint64(t.Slot))
		// Field #1 'BeaconBlockRoot'
		hh.PutBytes(t.BeaconBlockRoot[:])
		// Field #2 'ValidatorIndex'
		hh.PutUint64(uint64(t.ValidatorIndex))
		// Field #3 'Signature'
		hh.PutBytes(t.Signature[:])
		hh.Merkleize(idx)
		return err
	}
	return fn1(t)
}
func (t *SyncCommitteeMessage) HashTreeRootDyn(ds sszutils.DynamicSpecs) ([32]byte, error) {
	pool := &hasher.FastHasherPool
	hh := pool.Get()
	defer func() {
		pool.Put(hh)
	}()
	if err := t.HashTreeRootWith(hh); err != nil {
		return [32]byte{}, err
	}
	r, _ := hh.HashRoot()
	return r, nil
}
func (t *SyncCommitteeMessage) HashTreeRoot() ([32]byte, error) {
	pool := &hasher.FastHasherPool
	hh := pool.Get()
	defer func() {
		pool.Put(hh)
	}()
	if err := t.HashTreeRootWith(hh); err != nil {
		return [32]byte{}, err
	}
	r, _ := hh.HashRoot()
	return r, nil
}
