// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 248f1d364a35661b392375b947b6c0ccaccb10a8a3d69e75b8415ee77506ce09
// Version: v1.0.1 (https://github.com/pk910/dynamic-ssz)
package v1

import (
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *SignedValidatorRegistration) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	{ // Field #0 'Message'
		t := t.Message
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return dst, err
		}
	}
	{ // Field #1 'Signature'
		t := t.Signature
		limit := 96
		dst = append(dst, []byte(t[:limit])...)
	}
	return dst, nil
}

func (t *SignedValidatorRegistration) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *SignedValidatorRegistration) SizeSSZ() (size int) {
	return 180
}

func (t *SignedValidatorRegistration) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 180 {
		return sszutils.ErrUnexpectedEOF
	}
	{ // Field #0 'Message' (static)
		buf := buf[0:84]
		if t.Message == nil {
			t.Message = new(ValidatorRegistration)
		}
		if err = t.Message.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	{ // Field #1 'Signature' (static)
		buf := buf[84:180]
		copy(t.Signature[:], buf)
	}
	return nil
}

func (t *SignedValidatorRegistration) HashTreeRootWith(hh sszutils.HashWalker) error {
	idx := hh.Index()
	{ // Field #0 'Message'
		t := t.Message
		if err := t.HashTreeRootWith(hh); err != nil {
			return err
		}
	}
	{ // Field #1 'Signature'
		t := t.Signature
		idx := hh.Index()
		hh.PutBytes(t[:])
		hh.Merkleize(idx)
	}
	hh.Merkleize(idx)
	return nil
}

func (t *SignedValidatorRegistration) HashTreeRoot() ([32]byte, error) {
	pool := &hasher.FastHasherPool
	hh := pool.Get()
	defer func() {
		pool.Put(hh)
	}()
	if err := t.HashTreeRootWith(hh); err != nil {
		return [32]byte{}, err
	}
	r, _ := hh.HashRoot()
	return r, nil
}
