// Copyright © 2026 Attestant Limited.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package testclients

import consensusclient "github.com/attestantio/go-eth2-client"

// Compile-time assertions ensure that the test clients continue to satisfy their intended client interfaces.
var (
	_ consensusclient.Service                               = (*Erroring)(nil)
	_ consensusclient.Service                               = (*Sleepy)(nil)
	_ consensusclient.EpochFromStateIDProvider              = (*Erroring)(nil)
	_ consensusclient.EpochFromStateIDProvider              = (*Sleepy)(nil)
	_ consensusclient.SlotFromStateIDProvider               = (*Erroring)(nil)
	_ consensusclient.SlotFromStateIDProvider               = (*Sleepy)(nil)
	_ consensusclient.SlotDurationProvider                  = (*Erroring)(nil)
	_ consensusclient.SlotDurationProvider                  = (*Sleepy)(nil)
	_ consensusclient.SlotsPerEpochProvider                 = (*Erroring)(nil)
	_ consensusclient.SlotsPerEpochProvider                 = (*Sleepy)(nil)
	_ consensusclient.FarFutureEpochProvider                = (*Erroring)(nil)
	_ consensusclient.FarFutureEpochProvider                = (*Sleepy)(nil)
	_ consensusclient.TargetAggregatorsPerCommitteeProvider = (*Erroring)(nil)
	_ consensusclient.TargetAggregatorsPerCommitteeProvider = (*Sleepy)(nil)
	_ consensusclient.SignedBeaconBlockProvider             = (*Erroring)(nil)
	_ consensusclient.BlobsProvider                         = (*Erroring)(nil)
	_ consensusclient.BlobsProvider                         = (*Sleepy)(nil)
	_ consensusclient.BlobSidecarsProvider                  = (*Erroring)(nil)
	_ consensusclient.BlobSidecarsProvider                  = (*Sleepy)(nil)
	_ consensusclient.BeaconCommitteesProvider              = (*Erroring)(nil)
	_ consensusclient.SyncCommitteesProvider                = (*Erroring)(nil)
	_ consensusclient.AggregateAttestationProvider          = (*Erroring)(nil)
	_ consensusclient.AggregateAttestationProvider          = (*Sleepy)(nil)
	_ consensusclient.AggregateAttestationsSubmitter        = (*Erroring)(nil)
	_ consensusclient.AggregateAttestationsSubmitter        = (*Sleepy)(nil)
	_ consensusclient.AttestationDataProvider               = (*Erroring)(nil)
	_ consensusclient.AttestationDataProvider               = (*Sleepy)(nil)
	_ consensusclient.AttestationPoolProvider               = (*Erroring)(nil)
	_ consensusclient.AttestationPoolProvider               = (*Sleepy)(nil)
	_ consensusclient.AttestationRewardsProvider            = (*Erroring)(nil)
	_ consensusclient.AttestationRewardsProvider            = (*Sleepy)(nil)
	_ consensusclient.AttestationsSubmitter                 = (*Erroring)(nil)
	_ consensusclient.AttestationsSubmitter                 = (*Sleepy)(nil)
	_ consensusclient.AttesterDutiesProvider                = (*Erroring)(nil)
	_ consensusclient.AttesterDutiesProvider                = (*Sleepy)(nil)
	_ consensusclient.BlockRewardsProvider                  = (*Erroring)(nil)
	_ consensusclient.BlockRewardsProvider                  = (*Sleepy)(nil)
	_ consensusclient.DepositContractProvider               = (*Erroring)(nil)
	_ consensusclient.SyncCommitteeDutiesProvider           = (*Erroring)(nil)
	_ consensusclient.SyncCommitteeMessagesSubmitter        = (*Erroring)(nil)
	_ consensusclient.SyncCommitteeSubscriptionsSubmitter   = (*Erroring)(nil)
	_ consensusclient.SyncCommitteeContributionProvider     = (*Erroring)(nil)
	_ consensusclient.SyncCommitteeContributionsSubmitter   = (*Erroring)(nil)
	_ consensusclient.SyncCommitteeRewardsProvider          = (*Erroring)(nil)
	_ consensusclient.SyncCommitteeRewardsProvider          = (*Sleepy)(nil)
	_ consensusclient.BeaconBlockHeadersProvider            = (*Erroring)(nil)
	_ consensusclient.BeaconBlockHeadersProvider            = (*Sleepy)(nil)
	_ consensusclient.ProposalProvider                      = (*Erroring)(nil)
	_ consensusclient.ProposalProvider                      = (*Sleepy)(nil)
	_ consensusclient.BeaconBlockRootProvider               = (*Erroring)(nil)
	_ consensusclient.BeaconBlockSubmitter                  = (*Erroring)(nil)
	_ consensusclient.BeaconBlockSubmitter                  = (*Sleepy)(nil)
	_ consensusclient.BeaconCommitteeSubscriptionsSubmitter = (*Erroring)(nil)
	_ consensusclient.BeaconCommitteeSubscriptionsSubmitter = (*Sleepy)(nil)
	_ consensusclient.BeaconCommitteeSelectionsProvider     = (*Erroring)(nil)
	_ consensusclient.BeaconCommitteeSelectionsProvider     = (*Sleepy)(nil)
	_ consensusclient.BeaconStateProvider                   = (*Erroring)(nil)
	_ consensusclient.BeaconStateProvider                   = (*Sleepy)(nil)
	_ consensusclient.BeaconStateRootProvider               = (*Erroring)(nil)
	_ consensusclient.BlindedBeaconBlockSubmitter           = (*Erroring)(nil)
	_ consensusclient.BlindedBeaconBlockSubmitter           = (*Sleepy)(nil)
	_ consensusclient.ValidatorRegistrationsSubmitter       = (*Erroring)(nil)
	_ consensusclient.ValidatorRegistrationsSubmitter       = (*Sleepy)(nil)
	_ consensusclient.EventsProvider                        = (*Erroring)(nil)
	_ consensusclient.EventsProvider                        = (*Sleepy)(nil)
	_ consensusclient.FinalityProvider                      = (*Erroring)(nil)
	_ consensusclient.FinalityProvider                      = (*Sleepy)(nil)
	_ consensusclient.ForkChoiceProvider                    = (*Erroring)(nil)
	_ consensusclient.ForkChoiceProvider                    = (*Sleepy)(nil)
	_ consensusclient.ForkProvider                          = (*Erroring)(nil)
	_ consensusclient.ForkProvider                          = (*Sleepy)(nil)
	_ consensusclient.ForkScheduleProvider                  = (*Erroring)(nil)
	_ consensusclient.ForkScheduleProvider                  = (*Sleepy)(nil)
	_ consensusclient.GenesisProvider                       = (*Erroring)(nil)
	_ consensusclient.GenesisProvider                       = (*Sleepy)(nil)
	_ consensusclient.NodePeersProvider                     = (*Erroring)(nil)
	_ consensusclient.NodePeersProvider                     = (*Sleepy)(nil)
	_ consensusclient.NodeSyncingProvider                   = (*Erroring)(nil)
	_ consensusclient.NodeSyncingProvider                   = (*Sleepy)(nil)
	_ consensusclient.ValidatorLivenessProvider             = (*Erroring)(nil)
	_ consensusclient.ValidatorLivenessProvider             = (*Sleepy)(nil)
	_ consensusclient.NodeVersionProvider                   = (*Erroring)(nil)
	_ consensusclient.NodeVersionProvider                   = (*Sleepy)(nil)
	_ consensusclient.ProposalPreparationsSubmitter         = (*Erroring)(nil)
	_ consensusclient.ProposalPreparationsSubmitter         = (*Sleepy)(nil)
	_ consensusclient.ProposerDutiesProvider                = (*Erroring)(nil)
	_ consensusclient.ProposerDutiesProvider                = (*Sleepy)(nil)
	_ consensusclient.SpecProvider                          = (*Erroring)(nil)
	_ consensusclient.SpecProvider                          = (*Sleepy)(nil)
	_ consensusclient.ValidatorBalancesProvider             = (*Erroring)(nil)
	_ consensusclient.ValidatorBalancesProvider             = (*Sleepy)(nil)
	_ consensusclient.ValidatorsProvider                    = (*Erroring)(nil)
	_ consensusclient.ValidatorsProvider                    = (*Sleepy)(nil)
	_ consensusclient.VoluntaryExitSubmitter                = (*Erroring)(nil)
	_ consensusclient.VoluntaryExitSubmitter                = (*Sleepy)(nil)
	_ consensusclient.VoluntaryExitPoolProvider             = (*Erroring)(nil)
	_ consensusclient.VoluntaryExitPoolProvider             = (*Sleepy)(nil)
	_ consensusclient.PendingDepositProvider                = (*Erroring)(nil)
	_ consensusclient.PendingDepositProvider                = (*Sleepy)(nil)
	_ consensusclient.PendingConsolidationsProvider         = (*Sleepy)(nil)
	_ consensusclient.PendingPartialWithdrawalsProvider     = (*Sleepy)(nil)
	_ consensusclient.DomainProvider                        = (*Erroring)(nil)
	_ consensusclient.DomainProvider                        = (*Sleepy)(nil)
	//nolint:staticcheck // GenesisTimeProvider is deprecated but still implemented.
	_ consensusclient.GenesisTimeProvider = (*Erroring)(nil)
	//nolint:staticcheck // GenesisTimeProvider is deprecated but still implemented.
	_ consensusclient.GenesisTimeProvider = (*Sleepy)(nil)
)
