// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 035deed017873b88c4fe2b49225859c80fb95e3d9a938da90ead36c64600e74e
// Version: v0.0.4 (https://github.com/pk910/dynamic-ssz)
package electra

import (
	"github.com/attestantio/go-eth2-client/spec/phase0"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
	go_bitfield "github.com/prysmaticlabs/go-bitfield"
)

var _ = sszutils.ErrListTooBig

func (t *Attestation) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	fn1 := func(t go_bitfield.Bitlist) (err error) { // bitfield.Bitlist
		dst = append(dst, t[:]...)
		return err
	}
	fn2 := func(t *phase0.AttestationData) (err error) { // *phase0.AttestationData
		dst, err = t.MarshalSSZTo(dst)
		return err
	}
	fn3 := func(t go_bitfield.Bitvector64) (err error) { // bitfield.Bitvector64:8
		limit := 8
		vlen := len(t)
		if vlen > int(limit) {
			return sszutils.ErrListTooBig
		}
		vlimit := int(limit)
		if vlimit > vlen {
			vlimit = vlen
		}
		dst = append(dst, t[:vlimit]...)
		if vlen < int(limit) {
			dst = sszutils.AppendZeroPadding(dst, int(limit)-vlen)
		}
		return err
	}
	fn4 := func(t *Attestation) (err error) { // *electra.Attestation
		dstlen := len(dst)
		// Offset #0 'AggregationBits'
		offset0 := len(dst)
		dst = sszutils.MarshalOffset(dst, 0)
		// Field #1 'Data'
		if err = fn2(t.Data); err != nil {
			return err
		}
		// Field #2 'Signature'
		dst = append(dst, t.Signature[:]...)
		// Field #3 'CommitteeBits'
		if err = fn3(t.CommitteeBits); err != nil {
			return err
		}
		// Dynamic Field #0 'AggregationBits'
		sszutils.UpdateOffset(dst[offset0:offset0+4], len(dst)-dstlen)
		if err = fn1(t.AggregationBits); err != nil {
			return err
		}
		return err
	}
	err = fn4(t)
	return dst, err
}
func (t *Attestation) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

func (t *Attestation) SizeSSZ() (size int) {
	sfn1 := func(t go_bitfield.Bitlist) (size int) { // go_bitfield.Bitlist
		size += len(t)
		return size
	}
	sfn2 := func(t go_bitfield.Bitvector64) (size int) { // go_bitfield.Bitvector64:8
		limit := 8
		size += int(limit) * 1
		return size
	}
	sfn3 := func(t *Attestation) (size int) { // *Attestation
		size = 224
		size += 4 + sfn1(t.AggregationBits)
		size += sfn2(t.CommitteeBits)
		return size
	}
	return sfn3(t)
}

func (t *Attestation) UnmarshalSSZ(buf []byte) (err error) {
	fn1 := func(t go_bitfield.Bitlist, buf []byte) (go_bitfield.Bitlist, error) { // go_bitfield.Bitlist
		var err error
		if len(t) < len(buf) {
			t = make(go_bitfield.Bitlist, len(buf))
		} else {
			t = t[:len(buf)]
		}
		if len(buf) > 0 {
			copy(t[:], buf)
		}
		return t, err
	}
	fn2 := func(t *phase0.AttestationData, buf []byte) (*phase0.AttestationData, error) { // *phase0.AttestationData
		var err error
		if t == nil {
			t = new(phase0.AttestationData)
		}
		err = t.UnmarshalSSZ(buf)
		return t, err
	}
	fn3 := func(t go_bitfield.Bitvector64, buf []byte) (go_bitfield.Bitvector64, error) { // go_bitfield.Bitvector64:8
		var err error
		itemsize := 1
		limit := 8
		if len(t) < int(limit) {
			t = make(go_bitfield.Bitvector64, int(limit))
		} else {
			t = t[:int(limit)]
		}
		if len(buf) > int(limit)*itemsize {
			return t, sszutils.ErrListTooBig
		}
		copy(t[:], buf)
		return t, err
	}
	fn4 := func(t *Attestation, buf []byte) (*Attestation, error) { // *Attestation
		var err error
		if t == nil {
			t = new(Attestation)
		}
		bufpos := 236
		buflen := len(buf)
		if buflen < 236 {
			return t, sszutils.ErrUnexpectedEOF
		}
		// Read offset #0 'AggregationBits'
		offset0 := int(sszutils.ReadOffset(buf[0:4]))
		// Field #1 'Data'
		if t.Data, err = fn2(t.Data, buf[4:132]); err != nil {
			return t, err
		}
		// Field #2 'Signature'
		copy(t.Signature[:], buf[132:228])
		// Field #3 'CommitteeBits'
		if t.CommitteeBits, err = fn3(t.CommitteeBits, buf[228:236]); err != nil {
			return t, err
		}
		// Dynamic Field #0 'AggregationBits'
		if offset0 < bufpos {
			return t, sszutils.ErrOffset
		}
		{
			fieldSlice := buf[offset0:]
			if t.AggregationBits, err = fn1(t.AggregationBits, fieldSlice); err != nil {
				return t, err
			}
			bufpos += len(fieldSlice)
		}
		return t, err
	}
	_, err = fn4(t, buf)
	return err
}

func (t *Attestation) HashTreeRootWith(hh sszutils.HashWalker) error {
	fn1 := func(t go_bitfield.Bitlist) (err error) { // bitfield.Bitlist:131072
		maxLen := uint64(131072)
		var size uint64
		var bitlist []byte
		hh.WithTemp(func(tmp []byte) []byte {
			tmp, size = hasher.ParseBitlist(tmp[:0], t[:])
			bitlist = tmp
			return tmp
		})
		if size > maxLen {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		hh.AppendBytes32(bitlist)
		hh.MerkleizeWithMixin(idx, size, (maxLen+255)/256)
		return err
	}
	fn2 := func(t go_bitfield.Bitvector64) (err error) { // bitfield.Bitvector64:8
		limit := 8
		if len(t) != int(limit) {
			return sszutils.ErrVectorLength
		}
		hh.PutBytes(t[:])
		return err
	}
	fn3 := func(t *Attestation) (err error) { // *electra.Attestation
		idx := hh.Index()
		// Field #0 'AggregationBits'
		if err = fn1(t.AggregationBits); err != nil {
			return err
		}
		// Field #1 'Data'
		if err = t.Data.HashTreeRootWith(hh); err != nil {
			return err
		}
		// Field #2 'Signature'
		hh.PutBytes(t.Signature[:])
		// Field #3 'CommitteeBits'
		if err = fn2(t.CommitteeBits); err != nil {
			return err
		}
		hh.Merkleize(idx)
		return err
	}
	return fn3(t)
}
func (t *Attestation) HashTreeRoot() ([32]byte, error) {
	pool := &hasher.FastHasherPool
	hh := pool.Get()
	defer func() {
		pool.Put(hh)
	}()
	if err := t.HashTreeRootWith(hh); err != nil {
		return [32]byte{}, err
	}
	r, _ := hh.HashRoot()
	return r, nil
}
