// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 49dad08a11c1fb69934d2d92c44a5897ef6fc1f3b1c8bbd21bf9771457116e09
// Version: v0.0.0-20250923001904-cd6c84c23a24 (https://github.com/pk910/dynamic-ssz)
package electra

import (
	"github.com/attestantio/go-eth2-client/spec/altair"
	"github.com/attestantio/go-eth2-client/spec/capella"
	"github.com/attestantio/go-eth2-client/spec/deneb"
	"github.com/attestantio/go-eth2-client/spec/phase0"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
	go_bitfield "github.com/prysmaticlabs/go-bitfield"
)

var _ = sszutils.ErrListTooBig

func (t *BeaconState) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	dstlen := len(dst)
	{ // Field #0 'GenesisTime'
		t := t.GenesisTime
		dst = sszutils.MarshalUint64(dst, uint64(t))
	}
	{ // Field #1 'GenesisValidatorsRoot'
		t := t.GenesisValidatorsRoot
		limit := 32
		dst = append(dst, []byte(t[:limit])...)
	}
	{ // Field #2 'Slot'
		t := t.Slot
		dst = sszutils.MarshalUint64(dst, uint64(t))
	}
	{ // Field #3 'Fork'
		t := t.Fork
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return dst, err
		}
	}
	{ // Field #4 'LatestBlockHeader'
		t := t.LatestBlockHeader
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return dst, err
		}
	}
	{ // Field #5 'BlockRoots'
		t := t.BlockRoots
		limit := 8192
		vlen := len(t)
		if vlen > int(limit) {
			return dst, sszutils.ErrListTooBig
		}
		for i := 0; i < vlen; i++ {
			t := t[i]
			limit := 32
			dst = append(dst, []byte(t[:limit])...)
		}
		if vlen < int(limit) {
			dst = sszutils.AppendZeroPadding(dst, (int(limit)-vlen)*32)
		}
	}
	{ // Field #6 'StateRoots'
		t := t.StateRoots
		limit := 8192
		vlen := len(t)
		if vlen > int(limit) {
			return dst, sszutils.ErrListTooBig
		}
		for i := 0; i < vlen; i++ {
			t := t[i]
			limit := 32
			dst = append(dst, []byte(t[:limit])...)
		}
		if vlen < int(limit) {
			dst = sszutils.AppendZeroPadding(dst, (int(limit)-vlen)*32)
		}
	}
	// Offset #7 'HistoricalRoots'
	offset7 := len(dst)
	dst = sszutils.MarshalOffset(dst, 0)
	{ // Field #8 'ETH1Data'
		t := t.ETH1Data
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return dst, err
		}
	}
	// Offset #9 'ETH1DataVotes'
	offset9 := len(dst)
	dst = sszutils.MarshalOffset(dst, 0)
	{ // Field #10 'ETH1DepositIndex'
		t := t.ETH1DepositIndex
		dst = sszutils.MarshalUint64(dst, uint64(t))
	}
	// Offset #11 'Validators'
	offset11 := len(dst)
	dst = sszutils.MarshalOffset(dst, 0)
	// Offset #12 'Balances'
	offset12 := len(dst)
	dst = sszutils.MarshalOffset(dst, 0)
	{ // Field #13 'RANDAOMixes'
		t := t.RANDAOMixes
		limit := 65536
		vlen := len(t)
		if vlen > int(limit) {
			return dst, sszutils.ErrListTooBig
		}
		for i := 0; i < vlen; i++ {
			t := t[i]
			limit := 32
			dst = append(dst, []byte(t[:limit])...)
		}
		if vlen < int(limit) {
			dst = sszutils.AppendZeroPadding(dst, (int(limit)-vlen)*32)
		}
	}
	{ // Field #14 'Slashings'
		t := t.Slashings
		limit := 8192
		vlen := len(t)
		if vlen > int(limit) {
			return dst, sszutils.ErrListTooBig
		}
		for i := 0; i < vlen; i++ {
			t := t[i]
			dst = sszutils.MarshalUint64(dst, uint64(t))
		}
		if vlen < int(limit) {
			dst = sszutils.AppendZeroPadding(dst, (int(limit)-vlen)*8)
		}
	}
	// Offset #15 'PreviousEpochParticipation'
	offset15 := len(dst)
	dst = sszutils.MarshalOffset(dst, 0)
	// Offset #16 'CurrentEpochParticipation'
	offset16 := len(dst)
	dst = sszutils.MarshalOffset(dst, 0)
	{ // Field #17 'JustificationBits'
		t := t.JustificationBits
		limit := 1
		vlen := len(t)
		if vlen > int(limit) {
			return dst, sszutils.ErrListTooBig
		}
		dst = append(dst, []byte(t[:limit])...)
		if vlen < int(limit) {
			dst = sszutils.AppendZeroPadding(dst, (int(limit)-vlen)*1)
		}
	}
	{ // Field #18 'PreviousJustifiedCheckpoint'
		t := t.PreviousJustifiedCheckpoint
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return dst, err
		}
	}
	{ // Field #19 'CurrentJustifiedCheckpoint'
		t := t.CurrentJustifiedCheckpoint
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return dst, err
		}
	}
	{ // Field #20 'FinalizedCheckpoint'
		t := t.FinalizedCheckpoint
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return dst, err
		}
	}
	// Offset #21 'InactivityScores'
	offset21 := len(dst)
	dst = sszutils.MarshalOffset(dst, 0)
	{ // Field #22 'CurrentSyncCommittee'
		t := t.CurrentSyncCommittee
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return dst, err
		}
	}
	{ // Field #23 'NextSyncCommittee'
		t := t.NextSyncCommittee
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return dst, err
		}
	}
	// Offset #24 'LatestExecutionPayloadHeader'
	offset24 := len(dst)
	dst = sszutils.MarshalOffset(dst, 0)
	{ // Field #25 'NextWithdrawalIndex'
		t := t.NextWithdrawalIndex
		dst = sszutils.MarshalUint64(dst, uint64(t))
	}
	{ // Field #26 'NextWithdrawalValidatorIndex'
		t := t.NextWithdrawalValidatorIndex
		dst = sszutils.MarshalUint64(dst, uint64(t))
	}
	// Offset #27 'HistoricalSummaries'
	offset27 := len(dst)
	dst = sszutils.MarshalOffset(dst, 0)
	{ // Field #28 'DepositRequestsStartIndex'
		t := t.DepositRequestsStartIndex
		dst = sszutils.MarshalUint64(dst, uint64(t))
	}
	{ // Field #29 'DepositBalanceToConsume'
		t := t.DepositBalanceToConsume
		dst = sszutils.MarshalUint64(dst, uint64(t))
	}
	{ // Field #30 'ExitBalanceToConsume'
		t := t.ExitBalanceToConsume
		dst = sszutils.MarshalUint64(dst, uint64(t))
	}
	{ // Field #31 'EarliestExitEpoch'
		t := t.EarliestExitEpoch
		dst = sszutils.MarshalUint64(dst, uint64(t))
	}
	{ // Field #32 'ConsolidationBalanceToConsume'
		t := t.ConsolidationBalanceToConsume
		dst = sszutils.MarshalUint64(dst, uint64(t))
	}
	{ // Field #33 'EarliestConsolidationEpoch'
		t := t.EarliestConsolidationEpoch
		dst = sszutils.MarshalUint64(dst, uint64(t))
	}
	// Offset #34 'PendingDeposits'
	offset34 := len(dst)
	dst = sszutils.MarshalOffset(dst, 0)
	// Offset #35 'PendingPartialWithdrawals'
	offset35 := len(dst)
	dst = sszutils.MarshalOffset(dst, 0)
	// Offset #36 'PendingConsolidations'
	offset36 := len(dst)
	dst = sszutils.MarshalOffset(dst, 0)
	{ // Dynamic Field #7 'HistoricalRoots'
		sszutils.UpdateOffset(dst[offset7:offset7+4], len(dst)-dstlen)
		t := t.HistoricalRoots
		max := 16777216
		hasMax := true
		vlen := len(t)
		if hasMax && vlen > int(max) {
			return dst, sszutils.ErrListTooBig
		}
		for i := 0; i < vlen; i++ {
			t := t[i]
			limit := 32
			dst = append(dst, []byte(t[:limit])...)
		}
	}
	{ // Dynamic Field #9 'ETH1DataVotes'
		sszutils.UpdateOffset(dst[offset9:offset9+4], len(dst)-dstlen)
		t := t.ETH1DataVotes
		max := 2048
		hasMax := true
		vlen := len(t)
		if hasMax && vlen > int(max) {
			return dst, sszutils.ErrListTooBig
		}
		for i := 0; i < vlen; i++ {
			t := t[i]
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return dst, err
			}
		}
	}
	{ // Dynamic Field #11 'Validators'
		sszutils.UpdateOffset(dst[offset11:offset11+4], len(dst)-dstlen)
		t := t.Validators
		max := 1099511627776
		hasMax := true
		vlen := len(t)
		if hasMax && vlen > int(max) {
			return dst, sszutils.ErrListTooBig
		}
		for i := 0; i < vlen; i++ {
			t := t[i]
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return dst, err
			}
		}
	}
	{ // Dynamic Field #12 'Balances'
		sszutils.UpdateOffset(dst[offset12:offset12+4], len(dst)-dstlen)
		t := t.Balances
		max := 1099511627776
		hasMax := true
		vlen := len(t)
		if hasMax && vlen > int(max) {
			return dst, sszutils.ErrListTooBig
		}
		for i := 0; i < vlen; i++ {
			t := t[i]
			dst = sszutils.MarshalUint64(dst, uint64(t))
		}
	}
	{ // Dynamic Field #15 'PreviousEpochParticipation'
		sszutils.UpdateOffset(dst[offset15:offset15+4], len(dst)-dstlen)
		t := t.PreviousEpochParticipation
		max := 1099511627776
		hasMax := true
		vlen := len(t)
		if hasMax && vlen > int(max) {
			return dst, sszutils.ErrListTooBig
		}
		for i := 0; i < vlen; i++ {
			t := t[i]
			dst = sszutils.MarshalUint8(dst, uint8(t))
		}
	}
	{ // Dynamic Field #16 'CurrentEpochParticipation'
		sszutils.UpdateOffset(dst[offset16:offset16+4], len(dst)-dstlen)
		t := t.CurrentEpochParticipation
		max := 1099511627776
		hasMax := true
		vlen := len(t)
		if hasMax && vlen > int(max) {
			return dst, sszutils.ErrListTooBig
		}
		for i := 0; i < vlen; i++ {
			t := t[i]
			dst = sszutils.MarshalUint8(dst, uint8(t))
		}
	}
	{ // Dynamic Field #21 'InactivityScores'
		sszutils.UpdateOffset(dst[offset21:offset21+4], len(dst)-dstlen)
		t := t.InactivityScores
		max := 1099511627776
		hasMax := true
		vlen := len(t)
		if hasMax && vlen > int(max) {
			return dst, sszutils.ErrListTooBig
		}
		for i := 0; i < vlen; i++ {
			t := t[i]
			dst = sszutils.MarshalUint64(dst, uint64(t))
		}
	}
	{ // Dynamic Field #24 'LatestExecutionPayloadHeader'
		sszutils.UpdateOffset(dst[offset24:offset24+4], len(dst)-dstlen)
		t := t.LatestExecutionPayloadHeader
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return dst, err
		}
	}
	{ // Dynamic Field #27 'HistoricalSummaries'
		sszutils.UpdateOffset(dst[offset27:offset27+4], len(dst)-dstlen)
		t := t.HistoricalSummaries
		max := 16777216
		hasMax := true
		vlen := len(t)
		if hasMax && vlen > int(max) {
			return dst, sszutils.ErrListTooBig
		}
		for i := 0; i < vlen; i++ {
			t := t[i]
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return dst, err
			}
		}
	}
	{ // Dynamic Field #34 'PendingDeposits'
		sszutils.UpdateOffset(dst[offset34:offset34+4], len(dst)-dstlen)
		t := t.PendingDeposits
		max := 134217728
		hasMax := true
		vlen := len(t)
		if hasMax && vlen > int(max) {
			return dst, sszutils.ErrListTooBig
		}
		for i := 0; i < vlen; i++ {
			t := t[i]
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return dst, err
			}
		}
	}
	{ // Dynamic Field #35 'PendingPartialWithdrawals'
		sszutils.UpdateOffset(dst[offset35:offset35+4], len(dst)-dstlen)
		t := t.PendingPartialWithdrawals
		max := 134217728
		hasMax := true
		vlen := len(t)
		if hasMax && vlen > int(max) {
			return dst, sszutils.ErrListTooBig
		}
		for i := 0; i < vlen; i++ {
			t := t[i]
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return dst, err
			}
		}
	}
	{ // Dynamic Field #36 'PendingConsolidations'
		sszutils.UpdateOffset(dst[offset36:offset36+4], len(dst)-dstlen)
		t := t.PendingConsolidations
		max := 262144
		hasMax := true
		vlen := len(t)
		if hasMax && vlen > int(max) {
			return dst, sszutils.ErrListTooBig
		}
		for i := 0; i < vlen; i++ {
			t := t[i]
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return dst, err
			}
		}
	}
	return dst, nil
}

func (t *BeaconState) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *BeaconState) SizeSSZ() (size int) {
	size += 8 // Field #0 'GenesisTime'
	size += 32 // Field #1 'GenesisValidatorsRoot'
	size += 8 // Field #2 'Slot'
	size += 16 // Field #3 'Fork'
	size += 112 // Field #4 'LatestBlockHeader'
	{ // Field #5 'BlockRoots'
		limit := 8192
		size += int(limit) * 32
	}
	{ // Field #6 'StateRoots'
		limit := 8192
		size += int(limit) * 32
	}
	size += 4 // Offset for field #7 'HistoricalRoots'
	size += 72 // Field #8 'ETH1Data'
	size += 4 // Offset for field #9 'ETH1DataVotes'
	size += 8 // Field #10 'ETH1DepositIndex'
	size += 4 // Offset for field #11 'Validators'
	size += 4 // Offset for field #12 'Balances'
	{ // Field #13 'RANDAOMixes'
		limit := 65536
		size += int(limit) * 32
	}
	{ // Field #14 'Slashings'
		limit := 8192
		size += int(limit) * 8
	}
	size += 4 // Offset for field #15 'PreviousEpochParticipation'
	size += 4 // Offset for field #16 'CurrentEpochParticipation'
	size += 1 // Field #17 'JustificationBits'
	size += 40 // Field #18 'PreviousJustifiedCheckpoint'
	size += 40 // Field #19 'CurrentJustifiedCheckpoint'
	size += 40 // Field #20 'FinalizedCheckpoint'
	size += 4 // Offset for field #21 'InactivityScores'
	{ // Field #22 'CurrentSyncCommittee'
		size += t.CurrentSyncCommittee.SizeSSZ()
	}
	{ // Field #23 'NextSyncCommittee'
		size += t.NextSyncCommittee.SizeSSZ()
	}
	size += 4 // Offset for field #24 'LatestExecutionPayloadHeader'
	size += 8 // Field #25 'NextWithdrawalIndex'
	size += 8 // Field #26 'NextWithdrawalValidatorIndex'
	size += 4 // Offset for field #27 'HistoricalSummaries'
	size += 8 // Field #28 'DepositRequestsStartIndex'
	size += 8 // Field #29 'DepositBalanceToConsume'
	size += 8 // Field #30 'ExitBalanceToConsume'
	size += 8 // Field #31 'EarliestExitEpoch'
	size += 8 // Field #32 'ConsolidationBalanceToConsume'
	size += 8 // Field #33 'EarliestConsolidationEpoch'
	size += 4 // Offset for field #34 'PendingDeposits'
	size += 4 // Offset for field #35 'PendingPartialWithdrawals'
	size += 4 // Offset for field #36 'PendingConsolidations'
	{ // Dynamic field #7 'HistoricalRoots'
		vlen := len(t.HistoricalRoots)
		size += vlen * 32
	}
	{ // Dynamic field #9 'ETH1DataVotes'
		vlen := len(t.ETH1DataVotes)
		size += vlen * 72
	}
	{ // Dynamic field #11 'Validators'
		vlen := len(t.Validators)
		size += vlen * 121
	}
	{ // Dynamic field #12 'Balances'
		vlen := len(t.Balances)
		size += vlen * 8
	}
	{ // Dynamic field #15 'PreviousEpochParticipation'
		vlen := len(t.PreviousEpochParticipation)
		size += vlen * 1
	}
	{ // Dynamic field #16 'CurrentEpochParticipation'
		vlen := len(t.CurrentEpochParticipation)
		size += vlen * 1
	}
	{ // Dynamic field #21 'InactivityScores'
		vlen := len(t.InactivityScores)
		size += vlen * 8
	}
	{ // Dynamic field #24 'LatestExecutionPayloadHeader'
		size += t.LatestExecutionPayloadHeader.SizeSSZ()
	}
	{ // Dynamic field #27 'HistoricalSummaries'
		vlen := len(t.HistoricalSummaries)
		size += vlen * 64
	}
	{ // Dynamic field #34 'PendingDeposits'
		vlen := len(t.PendingDeposits)
		size += vlen * 192
	}
	{ // Dynamic field #35 'PendingPartialWithdrawals'
		vlen := len(t.PendingPartialWithdrawals)
		size += vlen * 24
	}
	{ // Dynamic field #36 'PendingConsolidations'
		vlen := len(t.PendingConsolidations)
		size += vlen * 16
	}
	return size
}

func (t *BeaconState) UnmarshalSSZ(buf []byte) (err error) {
	size1 := 32 * 8192
	size2 := 32 * 8192
	size3 := 32 * 65536
	size4 := 8 * 8192
	exproffset := 0
	buflen := len(buf)
	if buflen < size1+size2+size3+size4+24624+24624+489 {
		return sszutils.ErrUnexpectedEOF
	}
	{ // Field #0 'GenesisTime' (static)
		buf := buf[0:8]
		t.GenesisTime = uint64(sszutils.UnmarshallUint64(buf))
	}
	{ // Field #1 'GenesisValidatorsRoot' (static)
		buf := buf[8:40]
		val1 := t.GenesisValidatorsRoot
		copy(val1[:], buf)
		t.GenesisValidatorsRoot = val1
	}
	{ // Field #2 'Slot' (static)
		buf := buf[40:48]
		t.Slot = phase0.Slot(sszutils.UnmarshallUint64(buf))
	}
	{ // Field #3 'Fork' (static)
		buf := buf[48:64]
		val2 := t.Fork
		if val2 == nil {
			val2 = new(phase0.Fork)
		}
		if err = val2.UnmarshalSSZ(buf); err != nil {
			return err
		}
		t.Fork = val2
	}
	{ // Field #4 'LatestBlockHeader' (static)
		buf := buf[64:176]
		val3 := t.LatestBlockHeader
		if val3 == nil {
			val3 = new(phase0.BeaconBlockHeader)
		}
		if err = val3.UnmarshalSSZ(buf); err != nil {
			return err
		}
		t.LatestBlockHeader = val3
	}
	{ // Field #5 'BlockRoots' (static)
		buf := buf[176:size1+176]
		exproffset += int(size1)
		val4 := t.BlockRoots
		if(len(val4) < 8192) {
			val4 = make([]phase0.Root, 8192)
		} else if(len(val4) > 8192) {
			val4 = val4[:8192]
		}
		for i := 0; i < 8192; i++ {
			val5 := val4[i]
			buf := buf[32*i:32*(i+1)]
			copy(val5[:], buf)
			val4[i] = val5
		}
		t.BlockRoots = val4
	}
	{ // Field #6 'StateRoots' (static)
		buf := buf[exproffset+176:exproffset+size2+176]
		exproffset += int(size2)
		val6 := t.StateRoots
		if(len(val6) < 8192) {
			val6 = make([]phase0.Root, 8192)
		} else if(len(val6) > 8192) {
			val6 = val6[:8192]
		}
		for i := 0; i < 8192; i++ {
			val7 := val6[i]
			buf := buf[32*i:32*(i+1)]
			copy(val7[:], buf)
			val6[i] = val7
		}
		t.StateRoots = val6
	}
	// Field #7 'HistoricalRoots' (offset)
	offset7 := int(sszutils.UnmarshallUint32(buf[exproffset+176:exproffset+180]))
	if offset7 < size1+size2+size3+size4+24624+24624+489 || offset7 > buflen {
		return sszutils.ErrOffset
	}
	{ // Field #8 'ETH1Data' (static)
		buf := buf[exproffset+180:exproffset+252]
		val8 := t.ETH1Data
		if val8 == nil {
			val8 = new(phase0.ETH1Data)
		}
		if err = val8.UnmarshalSSZ(buf); err != nil {
			return err
		}
		t.ETH1Data = val8
	}
	// Field #9 'ETH1DataVotes' (offset)
	offset9 := int(sszutils.UnmarshallUint32(buf[exproffset+252:exproffset+256]))
	if offset9 < offset7 || offset9 > buflen {
		return sszutils.ErrOffset
	}
	{ // Field #10 'ETH1DepositIndex' (static)
		buf := buf[exproffset+256:exproffset+264]
		t.ETH1DepositIndex = uint64(sszutils.UnmarshallUint64(buf))
	}
	// Field #11 'Validators' (offset)
	offset11 := int(sszutils.UnmarshallUint32(buf[exproffset+264:exproffset+268]))
	if offset11 < offset9 || offset11 > buflen {
		return sszutils.ErrOffset
	}
	// Field #12 'Balances' (offset)
	offset12 := int(sszutils.UnmarshallUint32(buf[exproffset+268:exproffset+272]))
	if offset12 < offset11 || offset12 > buflen {
		return sszutils.ErrOffset
	}
	{ // Field #13 'RANDAOMixes' (static)
		buf := buf[exproffset+272:exproffset+size3+272]
		exproffset += int(size3)
		val9 := t.RANDAOMixes
		if(len(val9) < 65536) {
			val9 = make([]phase0.Root, 65536)
		} else if(len(val9) > 65536) {
			val9 = val9[:65536]
		}
		for i := 0; i < 65536; i++ {
			val10 := val9[i]
			buf := buf[32*i:32*(i+1)]
			copy(val10[:], buf)
			val9[i] = val10
		}
		t.RANDAOMixes = val9
	}
	{ // Field #14 'Slashings' (static)
		buf := buf[exproffset+272:exproffset+size4+272]
		exproffset += int(size4)
		val11 := t.Slashings
		if(len(val11) < 8192) {
			val11 = make([]phase0.Gwei, 8192)
		} else if(len(val11) > 8192) {
			val11 = val11[:8192]
		}
		for i := 0; i < 8192; i++ {
			buf := buf[8*i:8*(i+1)]
			val11[i] = phase0.Gwei(sszutils.UnmarshallUint64(buf))
		}
		t.Slashings = val11
	}
	// Field #15 'PreviousEpochParticipation' (offset)
	offset15 := int(sszutils.UnmarshallUint32(buf[exproffset+272:exproffset+276]))
	if offset15 < offset12 || offset15 > buflen {
		return sszutils.ErrOffset
	}
	// Field #16 'CurrentEpochParticipation' (offset)
	offset16 := int(sszutils.UnmarshallUint32(buf[exproffset+276:exproffset+280]))
	if offset16 < offset15 || offset16 > buflen {
		return sszutils.ErrOffset
	}
	{ // Field #17 'JustificationBits' (static)
		buf := buf[exproffset+280:exproffset+281]
		val12 := t.JustificationBits
		if(len(val12) < 1) {
			val12 = make(go_bitfield.Bitvector4, 1)
		} else if(len(val12) > 1) {
			val12 = val12[:1]
		}
		copy(val12[:], buf)
		t.JustificationBits = val12
	}
	{ // Field #18 'PreviousJustifiedCheckpoint' (static)
		buf := buf[exproffset+281:exproffset+321]
		val13 := t.PreviousJustifiedCheckpoint
		if val13 == nil {
			val13 = new(phase0.Checkpoint)
		}
		if err = val13.UnmarshalSSZ(buf); err != nil {
			return err
		}
		t.PreviousJustifiedCheckpoint = val13
	}
	{ // Field #19 'CurrentJustifiedCheckpoint' (static)
		buf := buf[exproffset+321:exproffset+361]
		val14 := t.CurrentJustifiedCheckpoint
		if val14 == nil {
			val14 = new(phase0.Checkpoint)
		}
		if err = val14.UnmarshalSSZ(buf); err != nil {
			return err
		}
		t.CurrentJustifiedCheckpoint = val14
	}
	{ // Field #20 'FinalizedCheckpoint' (static)
		buf := buf[exproffset+361:exproffset+401]
		val15 := t.FinalizedCheckpoint
		if val15 == nil {
			val15 = new(phase0.Checkpoint)
		}
		if err = val15.UnmarshalSSZ(buf); err != nil {
			return err
		}
		t.FinalizedCheckpoint = val15
	}
	// Field #21 'InactivityScores' (offset)
	offset21 := int(sszutils.UnmarshallUint32(buf[exproffset+401:exproffset+405]))
	if offset21 < offset16 || offset21 > buflen {
		return sszutils.ErrOffset
	}
	{ // Field #22 'CurrentSyncCommittee' (static)
		buf := buf[exproffset+405:exproffset+24624+405]
		exproffset += int(24624)
		val16 := t.CurrentSyncCommittee
		if val16 == nil {
			val16 = new(altair.SyncCommittee)
		}
		if err = val16.UnmarshalSSZ(buf); err != nil {
			return err
		}
		t.CurrentSyncCommittee = val16
	}
	{ // Field #23 'NextSyncCommittee' (static)
		buf := buf[exproffset+405:exproffset+24624+405]
		exproffset += int(24624)
		val17 := t.NextSyncCommittee
		if val17 == nil {
			val17 = new(altair.SyncCommittee)
		}
		if err = val17.UnmarshalSSZ(buf); err != nil {
			return err
		}
		t.NextSyncCommittee = val17
	}
	// Field #24 'LatestExecutionPayloadHeader' (offset)
	offset24 := int(sszutils.UnmarshallUint32(buf[exproffset+405:exproffset+409]))
	if offset24 < offset21 || offset24 > buflen {
		return sszutils.ErrOffset
	}
	{ // Field #25 'NextWithdrawalIndex' (static)
		buf := buf[exproffset+409:exproffset+417]
		t.NextWithdrawalIndex = capella.WithdrawalIndex(sszutils.UnmarshallUint64(buf))
	}
	{ // Field #26 'NextWithdrawalValidatorIndex' (static)
		buf := buf[exproffset+417:exproffset+425]
		t.NextWithdrawalValidatorIndex = phase0.ValidatorIndex(sszutils.UnmarshallUint64(buf))
	}
	// Field #27 'HistoricalSummaries' (offset)
	offset27 := int(sszutils.UnmarshallUint32(buf[exproffset+425:exproffset+429]))
	if offset27 < offset24 || offset27 > buflen {
		return sszutils.ErrOffset
	}
	{ // Field #28 'DepositRequestsStartIndex' (static)
		buf := buf[exproffset+429:exproffset+437]
		t.DepositRequestsStartIndex = uint64(sszutils.UnmarshallUint64(buf))
	}
	{ // Field #29 'DepositBalanceToConsume' (static)
		buf := buf[exproffset+437:exproffset+445]
		t.DepositBalanceToConsume = phase0.Gwei(sszutils.UnmarshallUint64(buf))
	}
	{ // Field #30 'ExitBalanceToConsume' (static)
		buf := buf[exproffset+445:exproffset+453]
		t.ExitBalanceToConsume = phase0.Gwei(sszutils.UnmarshallUint64(buf))
	}
	{ // Field #31 'EarliestExitEpoch' (static)
		buf := buf[exproffset+453:exproffset+461]
		t.EarliestExitEpoch = phase0.Epoch(sszutils.UnmarshallUint64(buf))
	}
	{ // Field #32 'ConsolidationBalanceToConsume' (static)
		buf := buf[exproffset+461:exproffset+469]
		t.ConsolidationBalanceToConsume = phase0.Gwei(sszutils.UnmarshallUint64(buf))
	}
	{ // Field #33 'EarliestConsolidationEpoch' (static)
		buf := buf[exproffset+469:exproffset+477]
		t.EarliestConsolidationEpoch = phase0.Epoch(sszutils.UnmarshallUint64(buf))
	}
	// Field #34 'PendingDeposits' (offset)
	offset34 := int(sszutils.UnmarshallUint32(buf[exproffset+477:exproffset+481]))
	if offset34 < offset27 || offset34 > buflen {
		return sszutils.ErrOffset
	}
	// Field #35 'PendingPartialWithdrawals' (offset)
	offset35 := int(sszutils.UnmarshallUint32(buf[exproffset+481:exproffset+485]))
	if offset35 < offset34 || offset35 > buflen {
		return sszutils.ErrOffset
	}
	// Field #36 'PendingConsolidations' (offset)
	offset36 := int(sszutils.UnmarshallUint32(buf[exproffset+485:exproffset+489]))
	if offset36 < offset35 || offset36 > buflen {
		return sszutils.ErrOffset
	}
	{ // Field #7 'HistoricalRoots' (dynamic)
		buf := buf[offset7:offset9]
		val18 := t.HistoricalRoots
		itemCount := len(buf)/32
		if len(buf)%32 != 0 {
			return sszutils.ErrUnexpectedEOF
		}
		if(len(val18) < itemCount) {
			val18 = make([]phase0.Root, itemCount)
		} else if(len(val18) > itemCount) {
			val18 = val18[:itemCount]
		}
		for i := 0; i < itemCount; i++ {
			val19 := val18[i]
			buf := buf[32*i:32*(i+1)]
			copy(val19[:], buf)
			val18[i] = val19
		}
		t.HistoricalRoots = val18
	}
	{ // Field #9 'ETH1DataVotes' (dynamic)
		buf := buf[offset9:offset11]
		val20 := t.ETH1DataVotes
		itemCount := len(buf)/72
		if len(buf)%72 != 0 {
			return sszutils.ErrUnexpectedEOF
		}
		if(len(val20) < itemCount) {
			val20 = make([]*phase0.ETH1Data, itemCount)
		} else if(len(val20) > itemCount) {
			val20 = val20[:itemCount]
		}
		for i := 0; i < itemCount; i++ {
			val21 := val20[i]
			if val21 == nil {
				val21 = new(phase0.ETH1Data)
			}
			buf := buf[72*i:72*(i+1)]
			if err = val21.UnmarshalSSZ(buf); err != nil {
				return err
			}
			val20[i] = val21
		}
		t.ETH1DataVotes = val20
	}
	{ // Field #11 'Validators' (dynamic)
		buf := buf[offset11:offset12]
		val22 := t.Validators
		itemCount := len(buf)/121
		if len(buf)%121 != 0 {
			return sszutils.ErrUnexpectedEOF
		}
		if(len(val22) < itemCount) {
			val22 = make([]*phase0.Validator, itemCount)
		} else if(len(val22) > itemCount) {
			val22 = val22[:itemCount]
		}
		for i := 0; i < itemCount; i++ {
			val23 := val22[i]
			if val23 == nil {
				val23 = new(phase0.Validator)
			}
			buf := buf[121*i:121*(i+1)]
			if err = val23.UnmarshalSSZ(buf); err != nil {
				return err
			}
			val22[i] = val23
		}
		t.Validators = val22
	}
	{ // Field #12 'Balances' (dynamic)
		buf := buf[offset12:offset15]
		val24 := t.Balances
		itemCount := len(buf)/8
		if len(buf)%8 != 0 {
			return sszutils.ErrUnexpectedEOF
		}
		if(len(val24) < itemCount) {
			val24 = make([]phase0.Gwei, itemCount)
		} else if(len(val24) > itemCount) {
			val24 = val24[:itemCount]
		}
		for i := 0; i < itemCount; i++ {
			buf := buf[8*i:8*(i+1)]
			val24[i] = phase0.Gwei(sszutils.UnmarshallUint64(buf))
		}
		t.Balances = val24
	}
	{ // Field #15 'PreviousEpochParticipation' (dynamic)
		buf := buf[offset15:offset16]
		val25 := t.PreviousEpochParticipation
		itemCount := len(buf)/1
		if len(buf)%1 != 0 {
			return sszutils.ErrUnexpectedEOF
		}
		if(len(val25) < itemCount) {
			val25 = make([]altair.ParticipationFlags, itemCount)
		} else if(len(val25) > itemCount) {
			val25 = val25[:itemCount]
		}
		for i := 0; i < itemCount; i++ {
			buf := buf[1*i:1*(i+1)]
			val25[i] = altair.ParticipationFlags(sszutils.UnmarshallUint8(buf))
		}
		t.PreviousEpochParticipation = val25
	}
	{ // Field #16 'CurrentEpochParticipation' (dynamic)
		buf := buf[offset16:offset21]
		val26 := t.CurrentEpochParticipation
		itemCount := len(buf)/1
		if len(buf)%1 != 0 {
			return sszutils.ErrUnexpectedEOF
		}
		if(len(val26) < itemCount) {
			val26 = make([]altair.ParticipationFlags, itemCount)
		} else if(len(val26) > itemCount) {
			val26 = val26[:itemCount]
		}
		for i := 0; i < itemCount; i++ {
			buf := buf[1*i:1*(i+1)]
			val26[i] = altair.ParticipationFlags(sszutils.UnmarshallUint8(buf))
		}
		t.CurrentEpochParticipation = val26
	}
	{ // Field #21 'InactivityScores' (dynamic)
		buf := buf[offset21:offset24]
		val27 := t.InactivityScores
		itemCount := len(buf)/8
		if len(buf)%8 != 0 {
			return sszutils.ErrUnexpectedEOF
		}
		if(len(val27) < itemCount) {
			val27 = make([]uint64, itemCount)
		} else if(len(val27) > itemCount) {
			val27 = val27[:itemCount]
		}
		for i := 0; i < itemCount; i++ {
			buf := buf[8*i:8*(i+1)]
			val27[i] = uint64(sszutils.UnmarshallUint64(buf))
		}
		t.InactivityScores = val27
	}
	{ // Field #24 'LatestExecutionPayloadHeader' (dynamic)
		buf := buf[offset24:offset27]
		val28 := t.LatestExecutionPayloadHeader
		if val28 == nil {
			val28 = new(deneb.ExecutionPayloadHeader)
		}
		if err = val28.UnmarshalSSZ(buf); err != nil {
			return err
		}
		t.LatestExecutionPayloadHeader = val28
	}
	{ // Field #27 'HistoricalSummaries' (dynamic)
		buf := buf[offset27:offset34]
		val29 := t.HistoricalSummaries
		itemCount := len(buf)/64
		if len(buf)%64 != 0 {
			return sszutils.ErrUnexpectedEOF
		}
		if(len(val29) < itemCount) {
			val29 = make([]*capella.HistoricalSummary, itemCount)
		} else if(len(val29) > itemCount) {
			val29 = val29[:itemCount]
		}
		for i := 0; i < itemCount; i++ {
			val30 := val29[i]
			if val30 == nil {
				val30 = new(capella.HistoricalSummary)
			}
			buf := buf[64*i:64*(i+1)]
			if err = val30.UnmarshalSSZ(buf); err != nil {
				return err
			}
			val29[i] = val30
		}
		t.HistoricalSummaries = val29
	}
	{ // Field #34 'PendingDeposits' (dynamic)
		buf := buf[offset34:offset35]
		val31 := t.PendingDeposits
		itemCount := len(buf)/192
		if len(buf)%192 != 0 {
			return sszutils.ErrUnexpectedEOF
		}
		if(len(val31) < itemCount) {
			val31 = make([]*PendingDeposit, itemCount)
		} else if(len(val31) > itemCount) {
			val31 = val31[:itemCount]
		}
		for i := 0; i < itemCount; i++ {
			val32 := val31[i]
			if val32 == nil {
				val32 = new(PendingDeposit)
			}
			buf := buf[192*i:192*(i+1)]
			if err = val32.UnmarshalSSZ(buf); err != nil {
				return err
			}
			val31[i] = val32
		}
		t.PendingDeposits = val31
	}
	{ // Field #35 'PendingPartialWithdrawals' (dynamic)
		buf := buf[offset35:offset36]
		val33 := t.PendingPartialWithdrawals
		itemCount := len(buf)/24
		if len(buf)%24 != 0 {
			return sszutils.ErrUnexpectedEOF
		}
		if(len(val33) < itemCount) {
			val33 = make([]*PendingPartialWithdrawal, itemCount)
		} else if(len(val33) > itemCount) {
			val33 = val33[:itemCount]
		}
		for i := 0; i < itemCount; i++ {
			val34 := val33[i]
			if val34 == nil {
				val34 = new(PendingPartialWithdrawal)
			}
			buf := buf[24*i:24*(i+1)]
			if err = val34.UnmarshalSSZ(buf); err != nil {
				return err
			}
			val33[i] = val34
		}
		t.PendingPartialWithdrawals = val33
	}
	{ // Field #36 'PendingConsolidations' (dynamic)
		buf := buf[offset36:]
		val35 := t.PendingConsolidations
		itemCount := len(buf)/16
		if len(buf)%16 != 0 {
			return sszutils.ErrUnexpectedEOF
		}
		if(len(val35) < itemCount) {
			val35 = make([]*PendingConsolidation, itemCount)
		} else if(len(val35) > itemCount) {
			val35 = val35[:itemCount]
		}
		for i := 0; i < itemCount; i++ {
			val36 := val35[i]
			if val36 == nil {
				val36 = new(PendingConsolidation)
			}
			buf := buf[16*i:16*(i+1)]
			if err = val36.UnmarshalSSZ(buf); err != nil {
				return err
			}
			val35[i] = val36
		}
		t.PendingConsolidations = val35
	}
	return nil
}

func (t *BeaconState) HashTreeRootWith(hh sszutils.HashWalker) error {
	idx := hh.Index()
	{ // Field #0 'GenesisTime'
		t := t.GenesisTime
		hh.PutUint64(uint64(t))
	}
	{ // Field #1 'GenesisValidatorsRoot'
		t := t.GenesisValidatorsRoot
		idx := hh.Index()
		hh.PutBytes(t[:])
		hh.Merkleize(idx)
	}
	{ // Field #2 'Slot'
		t := t.Slot
		hh.PutUint64(uint64(t))
	}
	{ // Field #3 'Fork'
		t := t.Fork
		if err := t.HashTreeRootWith(hh); err != nil {
			return err
		}
	}
	{ // Field #4 'LatestBlockHeader'
		t := t.LatestBlockHeader
		if err := t.HashTreeRootWith(hh); err != nil {
			return err
		}
	}
	{ // Field #5 'BlockRoots'
		t := t.BlockRoots
		idx := hh.Index()
		vlen := len(t)
		if vlen > 8192 {
			return sszutils.ErrVectorLength
		}
		for i := 0; i < 8192; i++ {
			var val1 phase0.Root
			if i < vlen {
				val1 = t[i]
			}
			idx := hh.Index()
			hh.PutBytes(val1[:])
			hh.Merkleize(idx)
		}
		hh.Merkleize(idx)
	}
	{ // Field #6 'StateRoots'
		t := t.StateRoots
		idx := hh.Index()
		vlen := len(t)
		if vlen > 8192 {
			return sszutils.ErrVectorLength
		}
		for i := 0; i < 8192; i++ {
			var val2 phase0.Root
			if i < vlen {
				val2 = t[i]
			}
			idx := hh.Index()
			hh.PutBytes(val2[:])
			hh.Merkleize(idx)
		}
		hh.Merkleize(idx)
	}
	{ // Field #7 'HistoricalRoots'
		t := t.HistoricalRoots
		idx := hh.Index()
		vlen := uint64(len(t))
		for i := 0; i < int(vlen); i++ {
			t := t[i]
			idx := hh.Index()
			hh.PutBytes(t[:])
			hh.Merkleize(idx)
		}
		limit := sszutils.CalculateLimit(16777216, vlen, 32)
		hh.MerkleizeWithMixin(idx, vlen, limit)
	}
	{ // Field #8 'ETH1Data'
		t := t.ETH1Data
		if err := t.HashTreeRootWith(hh); err != nil {
			return err
		}
	}
	{ // Field #9 'ETH1DataVotes'
		t := t.ETH1DataVotes
		idx := hh.Index()
		vlen := uint64(len(t))
		for i := 0; i < int(vlen); i++ {
			t := t[i]
			if err := t.HashTreeRootWith(hh); err != nil {
				return err
			}
		}
		limit := sszutils.CalculateLimit(2048, vlen, 32)
		hh.MerkleizeWithMixin(idx, vlen, limit)
	}
	{ // Field #10 'ETH1DepositIndex'
		t := t.ETH1DepositIndex
		hh.PutUint64(uint64(t))
	}
	{ // Field #11 'Validators'
		t := t.Validators
		idx := hh.Index()
		vlen := uint64(len(t))
		for i := 0; i < int(vlen); i++ {
			t := t[i]
			if err := t.HashTreeRootWith(hh); err != nil {
				return err
			}
		}
		limit := sszutils.CalculateLimit(1099511627776, vlen, 32)
		hh.MerkleizeWithMixin(idx, vlen, limit)
	}
	{ // Field #12 'Balances'
		t := t.Balances
		idx := hh.Index()
		vlen := uint64(len(t))
		for i := 0; i < int(vlen); i++ {
			t := t[i]
			hh.AppendUint64(uint64(t))
		}
		limit := sszutils.CalculateLimit(1099511627776, vlen, 8)
		hh.MerkleizeWithMixin(idx, vlen, limit)
	}
	{ // Field #13 'RANDAOMixes'
		t := t.RANDAOMixes
		idx := hh.Index()
		vlen := len(t)
		if vlen > 65536 {
			return sszutils.ErrVectorLength
		}
		for i := 0; i < 65536; i++ {
			var val3 phase0.Root
			if i < vlen {
				val3 = t[i]
			}
			idx := hh.Index()
			hh.PutBytes(val3[:])
			hh.Merkleize(idx)
		}
		hh.Merkleize(idx)
	}
	{ // Field #14 'Slashings'
		t := t.Slashings
		idx := hh.Index()
		vlen := len(t)
		if vlen > 8192 {
			return sszutils.ErrVectorLength
		}
		for i := 0; i < 8192; i++ {
			var val4 phase0.Gwei
			if i < vlen {
				val4 = t[i]
			}
			hh.AppendUint64(uint64(val4))
		}
		hh.Merkleize(idx)
	}
	{ // Field #15 'PreviousEpochParticipation'
		t := t.PreviousEpochParticipation
		idx := hh.Index()
		vlen := uint64(len(t))
		for i := 0; i < int(vlen); i++ {
			t := t[i]
			hh.AppendUint8(uint8(t))
		}
		limit := sszutils.CalculateLimit(1099511627776, vlen, 1)
		hh.MerkleizeWithMixin(idx, vlen, limit)
	}
	{ // Field #16 'CurrentEpochParticipation'
		t := t.CurrentEpochParticipation
		idx := hh.Index()
		vlen := uint64(len(t))
		for i := 0; i < int(vlen); i++ {
			t := t[i]
			hh.AppendUint8(uint8(t))
		}
		limit := sszutils.CalculateLimit(1099511627776, vlen, 1)
		hh.MerkleizeWithMixin(idx, vlen, limit)
	}
	{ // Field #17 'JustificationBits'
		t := t.JustificationBits
		idx := hh.Index()
		vlen := len(t)
		if vlen > 1 {
			return sszutils.ErrVectorLength
		}
		hh.PutBytes(t[:])
		hh.Merkleize(idx)
	}
	{ // Field #18 'PreviousJustifiedCheckpoint'
		t := t.PreviousJustifiedCheckpoint
		if err := t.HashTreeRootWith(hh); err != nil {
			return err
		}
	}
	{ // Field #19 'CurrentJustifiedCheckpoint'
		t := t.CurrentJustifiedCheckpoint
		if err := t.HashTreeRootWith(hh); err != nil {
			return err
		}
	}
	{ // Field #20 'FinalizedCheckpoint'
		t := t.FinalizedCheckpoint
		if err := t.HashTreeRootWith(hh); err != nil {
			return err
		}
	}
	{ // Field #21 'InactivityScores'
		t := t.InactivityScores
		idx := hh.Index()
		vlen := uint64(len(t))
		for i := 0; i < int(vlen); i++ {
			t := t[i]
			hh.AppendUint64(uint64(t))
		}
		limit := sszutils.CalculateLimit(1099511627776, vlen, 8)
		hh.MerkleizeWithMixin(idx, vlen, limit)
	}
	{ // Field #22 'CurrentSyncCommittee'
		t := t.CurrentSyncCommittee
		if err := t.HashTreeRootWith(hh); err != nil {
			return err
		}
	}
	{ // Field #23 'NextSyncCommittee'
		t := t.NextSyncCommittee
		if err := t.HashTreeRootWith(hh); err != nil {
			return err
		}
	}
	{ // Field #24 'LatestExecutionPayloadHeader'
		t := t.LatestExecutionPayloadHeader
		if err := t.HashTreeRootWith(hh); err != nil {
			return err
		}
	}
	{ // Field #25 'NextWithdrawalIndex'
		t := t.NextWithdrawalIndex
		hh.PutUint64(uint64(t))
	}
	{ // Field #26 'NextWithdrawalValidatorIndex'
		t := t.NextWithdrawalValidatorIndex
		hh.PutUint64(uint64(t))
	}
	{ // Field #27 'HistoricalSummaries'
		t := t.HistoricalSummaries
		idx := hh.Index()
		vlen := uint64(len(t))
		for i := 0; i < int(vlen); i++ {
			t := t[i]
			if err := t.HashTreeRootWith(hh); err != nil {
				return err
			}
		}
		limit := sszutils.CalculateLimit(16777216, vlen, 32)
		hh.MerkleizeWithMixin(idx, vlen, limit)
	}
	{ // Field #28 'DepositRequestsStartIndex'
		t := t.DepositRequestsStartIndex
		hh.PutUint64(uint64(t))
	}
	{ // Field #29 'DepositBalanceToConsume'
		t := t.DepositBalanceToConsume
		hh.PutUint64(uint64(t))
	}
	{ // Field #30 'ExitBalanceToConsume'
		t := t.ExitBalanceToConsume
		hh.PutUint64(uint64(t))
	}
	{ // Field #31 'EarliestExitEpoch'
		t := t.EarliestExitEpoch
		hh.PutUint64(uint64(t))
	}
	{ // Field #32 'ConsolidationBalanceToConsume'
		t := t.ConsolidationBalanceToConsume
		hh.PutUint64(uint64(t))
	}
	{ // Field #33 'EarliestConsolidationEpoch'
		t := t.EarliestConsolidationEpoch
		hh.PutUint64(uint64(t))
	}
	{ // Field #34 'PendingDeposits'
		t := t.PendingDeposits
		idx := hh.Index()
		vlen := uint64(len(t))
		for i := 0; i < int(vlen); i++ {
			t := t[i]
			if err := t.HashTreeRootWith(hh); err != nil {
				return err
			}
		}
		limit := sszutils.CalculateLimit(134217728, vlen, 32)
		hh.MerkleizeWithMixin(idx, vlen, limit)
	}
	{ // Field #35 'PendingPartialWithdrawals'
		t := t.PendingPartialWithdrawals
		idx := hh.Index()
		vlen := uint64(len(t))
		for i := 0; i < int(vlen); i++ {
			t := t[i]
			if err := t.HashTreeRootWith(hh); err != nil {
				return err
			}
		}
		limit := sszutils.CalculateLimit(134217728, vlen, 32)
		hh.MerkleizeWithMixin(idx, vlen, limit)
	}
	{ // Field #36 'PendingConsolidations'
		t := t.PendingConsolidations
		idx := hh.Index()
		vlen := uint64(len(t))
		for i := 0; i < int(vlen); i++ {
			t := t[i]
			if err := t.HashTreeRootWith(hh); err != nil {
				return err
			}
		}
		limit := sszutils.CalculateLimit(262144, vlen, 32)
		hh.MerkleizeWithMixin(idx, vlen, limit)
	}
	hh.Merkleize(idx)
	return nil
}

func (t *BeaconState) HashTreeRoot() ([32]byte, error) {
	pool := &hasher.FastHasherPool
	hh := pool.Get()
	defer func() {
		pool.Put(hh)
	}()
	if err := t.HashTreeRootWith(hh); err != nil {
		return [32]byte{}, err
	}
	r, _ := hh.HashRoot()
	return r, nil
}
