// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 413855a763305cca5f55c7b41388a2f24878bdf68970348bd71c5a2102909943
// Version: v0.0.4 (https://github.com/pk910/dynamic-ssz)
package electra

import (
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *ConsolidationRequest) MarshalSSZDyn(_ sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	return t.MarshalSSZTo(buf)
}
func (t *ConsolidationRequest) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	fn1 := func(t *ConsolidationRequest) (err error) { // *electra.ConsolidationRequest
		// Field #0 'SourceAddress'
		dst = append(dst, t.SourceAddress[:]...)
		// Field #1 'SourcePubkey'
		dst = append(dst, t.SourcePubkey[:]...)
		// Field #2 'TargetPubkey'
		dst = append(dst, t.TargetPubkey[:]...)
		return err
	}
	err = fn1(t)
	return dst, err
}
func (t *ConsolidationRequest) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

func (t *ConsolidationRequest) SizeSSZDyn(_ sszutils.DynamicSpecs) (size int) {
	return t.SizeSSZ()
}
func (t *ConsolidationRequest) SizeSSZ() (size int) {
	sfn1 := func(t *ConsolidationRequest) (size int) { // *ConsolidationRequest
		size = 116
		return size
	}
	return sfn1(t)
}

func (t *ConsolidationRequest) UnmarshalSSZDyn(_ sszutils.DynamicSpecs, buf []byte) (err error) {
	return t.UnmarshalSSZ(buf)
}
func (t *ConsolidationRequest) UnmarshalSSZ(buf []byte) (err error) {
	fn1 := func(t *ConsolidationRequest, buf []byte) (*ConsolidationRequest, error) { // *ConsolidationRequest
		var err error
		if t == nil {
			t = new(ConsolidationRequest)
		}
		buflen := len(buf)
		if buflen < 116 {
			return t, sszutils.ErrUnexpectedEOF
		}
		// Field #0 'SourceAddress'
		copy(t.SourceAddress[:], buf[0:20])
		// Field #1 'SourcePubkey'
		copy(t.SourcePubkey[:], buf[20:68])
		// Field #2 'TargetPubkey'
		copy(t.TargetPubkey[:], buf[68:116])
		return t, err
	}
	_, err = fn1(t, buf)
	return err
}

func (t *ConsolidationRequest) HashTreeRootWithDyn(_ sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	return t.HashTreeRootWith(hh)
}
func (t *ConsolidationRequest) HashTreeRootWith(hh sszutils.HashWalker) error {
	fn1 := func(t *ConsolidationRequest) (err error) { // *electra.ConsolidationRequest
		idx := hh.Index()
		// Field #0 'SourceAddress'
		hh.PutBytes(t.SourceAddress[:])
		// Field #1 'SourcePubkey'
		hh.PutBytes(t.SourcePubkey[:])
		// Field #2 'TargetPubkey'
		hh.PutBytes(t.TargetPubkey[:])
		hh.Merkleize(idx)
		return err
	}
	return fn1(t)
}
func (t *ConsolidationRequest) HashTreeRootDyn(ds sszutils.DynamicSpecs) ([32]byte, error) {
	pool := &hasher.FastHasherPool
	hh := pool.Get()
	defer func() {
		pool.Put(hh)
	}()
	if err := t.HashTreeRootWith(hh); err != nil {
		return [32]byte{}, err
	}
	r, _ := hh.HashRoot()
	return r, nil
}
func (t *ConsolidationRequest) HashTreeRoot() ([32]byte, error) {
	pool := &hasher.FastHasherPool
	hh := pool.Get()
	defer func() {
		pool.Put(hh)
	}()
	if err := t.HashTreeRootWith(hh); err != nil {
		return [32]byte{}, err
	}
	r, _ := hh.HashRoot()
	return r, nil
}
