// Code generated by fastssz. DO NOT EDIT.
// Hash: 17d4c9180818d70e873edf284079b326d586a16686d17c7c974a8a2fd19ec3e9
// Version: 0.1.3
package electra

import (
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the SignedConsolidation object
func (s *SignedConsolidation) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(s)
}

// MarshalSSZTo ssz marshals the SignedConsolidation object to a target array
func (s *SignedConsolidation) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'Message'
	if dst, err = s.Message.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (1) 'Signature'
	dst = append(dst, s.Signature[:]...)

	return
}

// UnmarshalSSZ ssz unmarshals the SignedConsolidation object
func (s *SignedConsolidation) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 120 {
		return ssz.ErrSize
	}

	// Field (0) 'Message'
	if err = s.Message.UnmarshalSSZ(buf[0:24]); err != nil {
		return err
	}

	// Field (1) 'Signature'
	copy(s.Signature[:], buf[24:120])

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the SignedConsolidation object
func (s *SignedConsolidation) SizeSSZ() (size int) {
	size = 120
	return
}

// HashTreeRoot ssz hashes the SignedConsolidation object
func (s *SignedConsolidation) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(s)
}

// HashTreeRootWith ssz hashes the SignedConsolidation object with a hasher
func (s *SignedConsolidation) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Message'
	if err = s.Message.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'Signature'
	hh.PutBytes(s.Signature[:])

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the SignedConsolidation object
func (s *SignedConsolidation) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(s)
}
