// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 23bf9253bd464b9b7de959992b6fdec85e98f9c27de44f535c2cedfd324cf85c
// Version: v1.3.1 (https://github.com/pk910/dynamic-ssz)
package deneb

import (
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

// MarshalSSZ marshals the *BeaconBlockBlob to SSZ-encoded bytes.
func (t *BeaconBlockBlob) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *BeaconBlockBlob to SSZ-encoded bytes, appending to the provided buffer.
func (t *BeaconBlockBlob) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(BeaconBlockBlob)
	}
	{ // Static Field #0 'Blob'
		dst = append(dst, t.Blob[:131072]...)
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *BeaconBlockBlob from SSZ-encoded bytes.
func (t *BeaconBlockBlob) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 131072 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 131072)
	}
	{ // Field #0 'Blob' (static)
		buf := buf[0:131072]
		copy(t.Blob[:], buf)
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *BeaconBlockBlob.
func (t *BeaconBlockBlob) SizeSSZ() (size int) {
	return 131072
}

// HashTreeRoot computes the SSZ hash tree root of the *BeaconBlockBlob.
func (t *BeaconBlockBlob) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *BeaconBlockBlob using the given hash walker.
func (t *BeaconBlockBlob) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(BeaconBlockBlob)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Blob'
		hh.PutBytes(t.Blob[:131072])
	}
	hh.Merkleize(idx)
	return nil
}
