// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 6744f46015a151229eea5c50db45670c0ca6575b5ef67d8601cdc56c3d21905b
// Version: v1.3.2 (https://github.com/pk910/dynamic-ssz)
package gloas

import (
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

var _ = sszutils.Annotate[BuilderExitRequest](`ssz-static:"true"`)

// MarshalSSZ marshals the *BuilderExitRequest to SSZ-encoded bytes.
func (t *BuilderExitRequest) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *BuilderExitRequest to SSZ-encoded bytes, appending to the provided buffer.
func (t *BuilderExitRequest) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(BuilderExitRequest)
	}
	{ // Static Field #0 'SourceAddress'
		dst = append(dst, t.SourceAddress[:20]...)
	}
	{ // Static Field #1 'Pubkey'
		dst = append(dst, t.Pubkey[:48]...)
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *BuilderExitRequest from SSZ-encoded bytes.
func (t *BuilderExitRequest) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 68 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 68)
	}
	if buflen > 68 {
		return sszutils.ErrTrailingDataFn(buflen - 68)
	}
	{ // Field #0 'SourceAddress' (static)
		buf := buf[0:20]
		copy(t.SourceAddress[:], buf)
	}
	{ // Field #1 'Pubkey' (static)
		buf := buf[20:68]
		copy(t.Pubkey[:], buf)
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *BuilderExitRequest.
func (t *BuilderExitRequest) SizeSSZ() (size int) {
	return 68
}

// HashTreeRoot computes the SSZ hash tree root of the *BuilderExitRequest.
func (t *BuilderExitRequest) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *BuilderExitRequest using the given hash walker.
func (t *BuilderExitRequest) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(BuilderExitRequest)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'SourceAddress'
		hh.PutBytes(t.SourceAddress[:20])
	}
	{ // Field #1 'Pubkey'
		hh.PutBytes(t.Pubkey[:48])
	}
	hh.Merkleize(idx)
	return nil
}
