// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 1d46c7a69ea582e780052d50baf963d1c45d3069b18399b1fc15fb3c3c30182c
// Version: v1.3.2 (https://github.com/pk910/dynamic-ssz)
package gloas

import (
	"encoding/binary"

	"github.com/attestantio/go-eth2-client/spec/phase0"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

var _ = sszutils.Annotate[BuilderEntry](`ssz-static:"false"`)

// MarshalSSZ marshals the *BuilderEntry to SSZ-encoded bytes.
func (t *BuilderEntry) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *BuilderEntry to SSZ-encoded bytes, appending to the provided buffer.
func (t *BuilderEntry) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	zeroBytes := sszutils.ZeroBytes()
	if t == nil {
		t = new(BuilderEntry)
	}
	dstlen := len(dst)
	// Offset Field #0 'URL'
	// Offset Field #1 'Auth'
	// Offset Field #2 'BuilderPubkeys'
	dst = append(dst, zeroBytes[:12]...)
	{ // Static Field #3 'MaxExecutionPayment'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.MaxExecutionPayment))
	}
	{ // Static Field #4 'MinBid'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.MinBid))
	}
	{ // Static Field #5 'BuilderBoostFactor'
		dst = binary.LittleEndian.AppendUint64(dst, t.BuilderBoostFactor)
	}
	{ // Dynamic Field #0 'URL'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		vlen := len(t.URL)
		if vlen > 2048 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 2048), "URL")
		}
		dst = append(dst, t.URL[:]...)
	}
	{ // Dynamic Field #1 'Auth'
		binary.LittleEndian.PutUint32(dst[dstlen+4:], uint32(len(dst)-dstlen))
		t := t.Auth
		if t == nil {
			t = new(SignedBuilderRequestAuth)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "Auth")
		}
	}
	{ // Dynamic Field #2 'BuilderPubkeys'
		binary.LittleEndian.PutUint32(dst[dstlen+8:], uint32(len(dst)-dstlen))
		t := t.BuilderPubkeys
		vlen := len(t)
		if vlen > 64 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 64), "BuilderPubkeys")
		}
		dst = sszutils.MarshalFixedBytesSlice(dst, t[:vlen])
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *BuilderEntry from SSZ-encoded bytes.
func (t *BuilderEntry) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 36 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 36)
	}
	// Field #0 'URL' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 36 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 36), "URL:o")
	}
	// Field #1 'Auth' (offset)
	offset1 := int(binary.LittleEndian.Uint32(buf[4:8]))
	if offset1 < offset0 || offset1 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset1, offset0, buflen), "Auth:o")
	}
	// Field #2 'BuilderPubkeys' (offset)
	offset2 := int(binary.LittleEndian.Uint32(buf[8:12]))
	if offset2 < offset1 || offset2 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset2, offset1, buflen), "BuilderPubkeys:o")
	}
	{ // Field #3 'MaxExecutionPayment' (static)
		buf := buf[12:20]
		t.MaxExecutionPayment = phase0.Gwei(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #4 'MinBid' (static)
		buf := buf[20:28]
		t.MinBid = phase0.Gwei(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #5 'BuilderBoostFactor' (static)
		buf := buf[28:36]
		t.BuilderBoostFactor = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #0 'URL' (dynamic)
		buf := buf[offset0:offset1]
		if len(buf) > 2048 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(len(buf), 2048), "URL")
		}
		t.URL = sszutils.ExpandSlice(t.URL, len(buf))
		copy(t.URL[:], buf)
	}
	{ // Field #1 'Auth' (dynamic)
		buf := buf[offset1:offset2]
		if t.Auth == nil {
			t.Auth = new(SignedBuilderRequestAuth)
		}
		if err = t.Auth.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "Auth")
		}
	}
	{ // Field #2 'BuilderPubkeys' (dynamic)
		buf := buf[offset2:]
		val1 := t.BuilderPubkeys
		itemCount := len(buf) / 48
		if len(buf)%48 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 48), "BuilderPubkeys")
		}
		if itemCount > 64 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 64), "BuilderPubkeys")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		sszutils.UnmarshalFixedBytesSlice(val1[:itemCount], buf)
		t.BuilderPubkeys = val1
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *BuilderEntry.
func (t *BuilderEntry) SizeSSZ() (size int) {
	if t == nil {
		t = new(BuilderEntry)
	}
	// Field #0 'URL' offset (4 bytes)
	// Field #1 'Auth' offset (4 bytes)
	// Field #2 'BuilderPubkeys' offset (4 bytes)
	// Field #3 'MaxExecutionPayment' static (8 bytes)
	// Field #4 'MinBid' static (8 bytes)
	// Field #5 'BuilderBoostFactor' static (8 bytes)
	size += 36
	{ // Dynamic field #0 'URL'
		size += len(t.URL)
	}
	{ // Dynamic field #1 'Auth'
		size += t.Auth.SizeSSZ()
	}
	{ // Dynamic field #2 'BuilderPubkeys'
		size += len(t.BuilderPubkeys) * 48
	}
	return size
}

// HashTreeRoot computes the SSZ hash tree root of the *BuilderEntry.
func (t *BuilderEntry) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *BuilderEntry using the given hash walker.
func (t *BuilderEntry) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(BuilderEntry)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'URL'
		vlen := uint64(len(t.URL))
		if vlen > 2048 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 2048), "URL")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		hh.AppendBytes32(t.URL[:])
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(2048, vlen, 1))
	}
	{ // Field #1 'Auth'
		t := t.Auth
		if t == nil {
			t = new(SignedBuilderRequestAuth)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "Auth")
		}
	}
	{ // Field #2 'BuilderPubkeys'
		t := t.BuilderPubkeys
		vlen := uint64(len(t))
		if vlen > 64 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 64), "BuilderPubkeys")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			hh.PutBytes(t[idx1][:48])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(64, vlen, 32))
	}
	{ // Field #3 'MaxExecutionPayment'
		hh.PutUint64(uint64(t.MaxExecutionPayment))
	}
	{ // Field #4 'MinBid'
		hh.PutUint64(uint64(t.MinBid))
	}
	{ // Field #5 'BuilderBoostFactor'
		hh.PutUint64(t.BuilderBoostFactor)
	}
	hh.MerkleizeProgressiveWithActiveFields(idx, []byte{0x3f})
	return nil
}
