// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 3908ebeeeffed33153f7c3f68780c43415eba9226b0a17b9aa73ddbe3e0a9892
// Version: v1.3.1 (https://github.com/pk910/dynamic-ssz)
package gloas

import (
	"encoding/binary"

	"github.com/attestantio/go-eth2-client/spec/phase0"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

// MarshalSSZ marshals the *PayloadAttestationMessage to SSZ-encoded bytes.
func (t *PayloadAttestationMessage) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *PayloadAttestationMessage to SSZ-encoded bytes, appending to the provided buffer.
func (t *PayloadAttestationMessage) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(PayloadAttestationMessage)
	}
	{ // Static Field #0 'ValidatorIndex'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.ValidatorIndex))
	}
	{ // Static Field #1 'Data'
		t := t.Data
		if t == nil {
			t = new(PayloadAttestationData)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "Data")
		}
	}
	{ // Static Field #2 'Signature'
		dst = append(dst, t.Signature[:96]...)
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *PayloadAttestationMessage from SSZ-encoded bytes.
func (t *PayloadAttestationMessage) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 146 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 146)
	}
	{ // Field #0 'ValidatorIndex' (static)
		buf := buf[0:8]
		t.ValidatorIndex = phase0.ValidatorIndex(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #1 'Data' (static)
		buf := buf[8:50]
		if t.Data == nil {
			t.Data = new(PayloadAttestationData)
		}
		if err = t.Data.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "Data")
		}
	}
	{ // Field #2 'Signature' (static)
		buf := buf[50:146]
		copy(t.Signature[:], buf)
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *PayloadAttestationMessage.
func (t *PayloadAttestationMessage) SizeSSZ() (size int) {
	return 146
}

// HashTreeRoot computes the SSZ hash tree root of the *PayloadAttestationMessage.
func (t *PayloadAttestationMessage) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *PayloadAttestationMessage using the given hash walker.
func (t *PayloadAttestationMessage) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(PayloadAttestationMessage)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'ValidatorIndex'
		hh.PutUint64(uint64(t.ValidatorIndex))
	}
	{ // Field #1 'Data'
		t := t.Data
		if t == nil {
			t = new(PayloadAttestationData)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "Data")
		}
	}
	{ // Field #2 'Signature'
		hh.PutBytes(t.Signature[:96])
	}
	hh.Merkleize(idx)
	return nil
}
