// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: fc74cb9c1451bda9e7c3795fa2c0a64872801553e85689f4a382111be30f7135
// Version: v1.3.1 (https://github.com/pk910/dynamic-ssz)
package gloas

import (
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

// MarshalSSZ marshals the *SignedProposerPreferences to SSZ-encoded bytes.
func (t *SignedProposerPreferences) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *SignedProposerPreferences to SSZ-encoded bytes, appending to the provided buffer.
func (t *SignedProposerPreferences) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(SignedProposerPreferences)
	}
	{ // Static Field #0 'Message'
		t := t.Message
		if t == nil {
			t = new(ProposerPreferences)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "Message")
		}
	}
	{ // Static Field #1 'Signature'
		dst = append(dst, t.Signature[:96]...)
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *SignedProposerPreferences from SSZ-encoded bytes.
func (t *SignedProposerPreferences) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 140 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 140)
	}
	{ // Field #0 'Message' (static)
		buf := buf[0:44]
		if t.Message == nil {
			t.Message = new(ProposerPreferences)
		}
		if err = t.Message.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "Message")
		}
	}
	{ // Field #1 'Signature' (static)
		buf := buf[44:140]
		copy(t.Signature[:], buf)
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *SignedProposerPreferences.
func (t *SignedProposerPreferences) SizeSSZ() (size int) {
	return 140
}

// HashTreeRoot computes the SSZ hash tree root of the *SignedProposerPreferences.
func (t *SignedProposerPreferences) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *SignedProposerPreferences using the given hash walker.
func (t *SignedProposerPreferences) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(SignedProposerPreferences)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Message'
		t := t.Message
		if t == nil {
			t = new(ProposerPreferences)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "Message")
		}
	}
	{ // Field #1 'Signature'
		hh.PutBytes(t.Signature[:96])
	}
	hh.Merkleize(idx)
	return nil
}
