// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: ae7a813264024184b3b42c55d1c86ef45eec802cb9ec18719ca8d1b4280056b0
// Version: v1.3.1 (https://github.com/pk910/dynamic-ssz)
package phase0

import (
	"encoding/binary"
	"math/bits"

	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

// MarshalSSZ marshals the *Attestation to SSZ-encoded bytes.
func (t *Attestation) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *Attestation to SSZ-encoded bytes, appending to the provided buffer.
func (t *Attestation) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(Attestation)
	}
	dstlen := len(dst)
	// Offset Field #0 'AggregationBits'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #1 'Data'
		t := t.Data
		if t == nil {
			t = new(AttestationData)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "Data")
		}
	}
	{ // Static Field #2 'Signature'
		dst = append(dst, t.Signature[:96]...)
	}
	{ // Dynamic Field #0 'AggregationBits'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.AggregationBits
		vlen := len(t)
		bval := []byte(t[:])
		if vlen == 0 {
			bval = []byte{0x01}
		} else if bval[vlen-1] == 0x00 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrBitlistNotTerminatedFn(), "AggregationBits")
		}
		if vlen > 0 {
			bitCount := 8*(vlen-1) + bits.Len8(bval[vlen-1]) - 1
			if bitCount > 2048 {
				return nil, sszutils.ErrorWithPath(sszutils.ErrBitlistLengthFn(bitCount, 2048), "AggregationBits")
			}
		}
		dst = append(dst, bval...)
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *Attestation from SSZ-encoded bytes.
func (t *Attestation) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 228 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 228)
	}
	// Field #0 'AggregationBits' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 228 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 228), "AggregationBits:o")
	}
	{ // Field #1 'Data' (static)
		buf := buf[4:132]
		if t.Data == nil {
			t.Data = new(AttestationData)
		}
		if err = t.Data.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "Data")
		}
	}
	{ // Field #2 'Signature' (static)
		buf := buf[132:228]
		copy(t.Signature[:], buf)
	}
	{ // Field #0 'AggregationBits' (dynamic)
		buf := buf[offset0:]
		val1 := t.AggregationBits
		blen := len(buf)
		if blen == 0 || buf[blen-1] == 0x00 {
			return sszutils.ErrorWithPath(sszutils.ErrBitlistNotTerminatedFn(), "AggregationBits")
		}
		bitCount := 8*(blen-1) + int(bits.Len8(buf[blen-1])) - 1
		if bitCount > 2048 {
			return sszutils.ErrorWithPath(sszutils.ErrBitlistLengthFn(bitCount, 2048), "AggregationBits")
		}
		val1 = sszutils.ExpandSlice(val1, blen)
		copy(val1[:], buf)
		t.AggregationBits = val1
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *Attestation.
func (t *Attestation) SizeSSZ() (size int) {
	if t == nil {
		t = new(Attestation)
	}
	// Field #0 'AggregationBits' offset (4 bytes)
	// Field #1 'Data' static (128 bytes)
	// Field #2 'Signature' static (96 bytes)
	size += 228
	{ // Dynamic field #0 'AggregationBits'
		if len(t.AggregationBits) == 0 {
			size += 1
		} else {
			size += len(t.AggregationBits)
		}
	}
	return size
}

// HashTreeRoot computes the SSZ hash tree root of the *Attestation.
func (t *Attestation) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *Attestation using the given hash walker.
func (t *Attestation) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(Attestation)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'AggregationBits'
		t := t.AggregationBits
		idx := hh.StartTree(sszutils.TreeTypeNone)
		bitlist, size := hasher.ParseBitlistWithHasher(hh, t[:])
		if size > 2048 {
			return sszutils.ErrorWithPath(sszutils.ErrBitlistLengthFn(size, 2048), "AggregationBits")
		}
		hh.AppendBytes32(bitlist)
		hh.MerkleizeWithMixin(idx, size, (2048+255)/256)
	}
	{ // Field #1 'Data'
		t := t.Data
		if t == nil {
			t = new(AttestationData)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "Data")
		}
	}
	{ // Field #2 'Signature'
		hh.PutBytes(t.Signature[:96])
	}
	hh.Merkleize(idx)
	return nil
}
