// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 2762ffbf7779b00b91a45a94046ddb1cb9adfd48a5b22d5494e45f62bb71dfa2
// Version: v0.0.4 (https://github.com/pk910/dynamic-ssz)
package phase0

import (
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *DepositMessage) MarshalSSZDyn(_ sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	return t.MarshalSSZTo(buf)
}
func (t *DepositMessage) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	fn1 := func(t *DepositMessage) (err error) { // *phase0.DepositMessage
		// Field #0 'PublicKey'
		dst = append(dst, t.PublicKey[:]...)
		// Field #1 'WithdrawalCredentials'
		if len(t.WithdrawalCredentials) > 32 {
			dst = append(dst, t.WithdrawalCredentials[:32]...)
		} else {
			dst = append(dst, t.WithdrawalCredentials[:]...)
			if len(t.WithdrawalCredentials) < 32 {
				dst = sszutils.AppendZeroPadding(dst, 32-len(t.WithdrawalCredentials))
			}
		}
		// Field #2 'Amount'
		dst = sszutils.MarshalUint64(dst, uint64(t.Amount))
		return err
	}
	err = fn1(t)
	return dst, err
}
func (t *DepositMessage) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

func (t *DepositMessage) SizeSSZDyn(_ sszutils.DynamicSpecs) (size int) {
	return t.SizeSSZ()
}
func (t *DepositMessage) SizeSSZ() (size int) {
	sfn1 := func(t *DepositMessage) (size int) { // *DepositMessage
		size = 88
		return size
	}
	return sfn1(t)
}

func (t *DepositMessage) UnmarshalSSZDyn(_ sszutils.DynamicSpecs, buf []byte) (err error) {
	return t.UnmarshalSSZ(buf)
}
func (t *DepositMessage) UnmarshalSSZ(buf []byte) (err error) {
	fn1 := func(t *DepositMessage, buf []byte) (*DepositMessage, error) { // *DepositMessage
		var err error
		if t == nil {
			t = new(DepositMessage)
		}
		buflen := len(buf)
		if buflen < 88 {
			return t, sszutils.ErrUnexpectedEOF
		}
		// Field #0 'PublicKey'
		copy(t.PublicKey[:], buf[0:48])
		// Field #1 'WithdrawalCredentials'
		if len(t.WithdrawalCredentials) < 32 {
			t.WithdrawalCredentials = make([]byte, 32)
		} else {
			t.WithdrawalCredentials = t.WithdrawalCredentials[:32]
		}
		copy(t.WithdrawalCredentials[:], buf[48:80])
		// Field #2 'Amount'
		t.Amount = (Gwei)(sszutils.UnmarshallUint64(buf[80:88]))
		return t, err
	}
	_, err = fn1(t, buf)
	return err
}

func (t *DepositMessage) HashTreeRootWithDyn(_ sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	return t.HashTreeRootWith(hh)
}
func (t *DepositMessage) HashTreeRootWith(hh sszutils.HashWalker) error {
	fn1 := func(t *DepositMessage) (err error) { // *phase0.DepositMessage
		idx := hh.Index()
		// Field #0 'PublicKey'
		hh.PutBytes(t.PublicKey[:])
		// Field #1 'WithdrawalCredentials'
		hh.PutBytes(t.WithdrawalCredentials[:])
		// Field #2 'Amount'
		hh.PutUint64(uint64(t.Amount))
		hh.Merkleize(idx)
		return err
	}
	return fn1(t)
}
func (t *DepositMessage) HashTreeRootDyn(ds sszutils.DynamicSpecs) ([32]byte, error) {
	pool := &hasher.FastHasherPool
	hh := pool.Get()
	defer func() {
		pool.Put(hh)
	}()
	if err := t.HashTreeRootWith(hh); err != nil {
		return [32]byte{}, err
	}
	r, _ := hh.HashRoot()
	return r, nil
}
func (t *DepositMessage) HashTreeRoot() ([32]byte, error) {
	pool := &hasher.FastHasherPool
	hh := pool.Get()
	defer func() {
		pool.Put(hh)
	}()
	if err := t.HashTreeRootWith(hh); err != nil {
		return [32]byte{}, err
	}
	r, _ := hh.HashRoot()
	return r, nil
}
