// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: d856c19f06ed00e2e0c541b87fee91ab75dc15fe8aec1e7a5ff2fd7f25f4a480
// Version: v1.0.1 (https://github.com/pk910/dynamic-ssz)
package phase0

import (
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *IndexedAttestation) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	dstlen := len(dst)
	// Offset #0 'AttestingIndices'
	offset0 := len(dst)
	dst = sszutils.MarshalOffset(dst, 0)
	{ // Field #1 'Data'
		t := t.Data
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return dst, err
		}
	}
	{ // Field #2 'Signature'
		t := t.Signature
		limit := 96
		dst = append(dst, []byte(t[:limit])...)
	}
	{ // Dynamic Field #0 'AttestingIndices'
		sszutils.UpdateOffset(dst[offset0:offset0+4], len(dst)-dstlen)
		t := t.AttestingIndices
		max := 2048
		hasMax := true
		vlen := len(t)
		if hasMax && vlen > int(max) {
			return dst, sszutils.ErrListTooBig
		}
		for i := 0; i < vlen; i++ {
			t := t[i]
			dst = sszutils.MarshalUint64(dst, uint64(t))
		}
	}
	return dst, nil
}

func (t *IndexedAttestation) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *IndexedAttestation) SizeSSZ() (size int) {
	// Field #0 'AttestingIndices' offset (4 bytes)
	// Field #1 'Data' static (128 bytes)
	// Field #2 'Signature' static (96 bytes)
	size += 228
	{ // Dynamic field #0 'AttestingIndices'
		vlen := len(t.AttestingIndices)
		size += vlen * 8
	}
	return size
}

func (t *IndexedAttestation) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 228 {
		return sszutils.ErrUnexpectedEOF
	}
	// Field #0 'AttestingIndices' (offset)
	offset0 := int(sszutils.UnmarshallUint32(buf[0:4]))
	if offset0 < 228 || offset0 > buflen {
		return sszutils.ErrOffset
	}
	{ // Field #1 'Data' (static)
		buf := buf[4:132]
		if t.Data == nil {
			t.Data = new(AttestationData)
		}
		if err = t.Data.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	{ // Field #2 'Signature' (static)
		buf := buf[132:228]
		copy(t.Signature[:], buf)
	}
	{ // Field #0 'AttestingIndices' (dynamic)
		buf := buf[offset0:]
		val1 := t.AttestingIndices
		itemCount := len(buf) / 8
		if len(buf)%8 != 0 {
			return sszutils.ErrUnexpectedEOF
		}
		if len(val1) < itemCount {
			val1 = make([]uint64, itemCount)
		} else if len(val1) > itemCount {
			val1 = val1[:itemCount]
		}
		for i := 0; i < itemCount; i++ {
			buf := buf[8*i : 8*(i+1)]
			val1[i] = uint64(sszutils.UnmarshallUint64(buf))
		}
		t.AttestingIndices = val1
	}
	return nil
}

func (t *IndexedAttestation) HashTreeRootWith(hh sszutils.HashWalker) error {
	idx := hh.Index()
	{ // Field #0 'AttestingIndices'
		t := t.AttestingIndices
		idx := hh.Index()
		vlen := uint64(len(t))
		for i := 0; i < int(vlen); i++ {
			t := t[i]
			hh.AppendUint64(uint64(t))
		}
		limit := sszutils.CalculateLimit(2048, vlen, 8)
		hh.MerkleizeWithMixin(idx, vlen, limit)
	}
	{ // Field #1 'Data'
		t := t.Data
		if err := t.HashTreeRootWith(hh); err != nil {
			return err
		}
	}
	{ // Field #2 'Signature'
		t := t.Signature
		idx := hh.Index()
		hh.PutBytes(t[:])
		hh.Merkleize(idx)
	}
	hh.Merkleize(idx)
	return nil
}

func (t *IndexedAttestation) HashTreeRoot() ([32]byte, error) {
	pool := &hasher.FastHasherPool
	hh := pool.Get()
	defer func() {
		pool.Put(hh)
	}()
	if err := t.HashTreeRootWith(hh); err != nil {
		return [32]byte{}, err
	}
	r, _ := hh.HashRoot()
	return r, nil
}
