// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: cd9c8658c4b8f498bedc38f07eb017d053a31f90dd6322511489b857930971ba
// Version: v1.1.0 (https://github.com/pk910/dynamic-ssz)
package phase0

import (
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *SignedBeaconBlockHeader) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(SignedBeaconBlockHeader)
	}
	{ // Field #0 'Message'
		t := t.Message
		if t == nil {
			t = new(BeaconBlockHeader)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return dst, err
		}
	}
	{ // Field #1 'Signature'
		t := &t.Signature
		dst = append(dst, []byte(t[:96])...)
	}
	return dst, nil
}

func (t *SignedBeaconBlockHeader) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *SignedBeaconBlockHeader) SizeSSZ() (size int) {
	return 208
}

func (t *SignedBeaconBlockHeader) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 208 {
		return sszutils.ErrUnexpectedEOF
	}
	{ // Field #0 'Message' (static)
		buf := buf[0:112]
		if t.Message == nil {
			t.Message = new(BeaconBlockHeader)
		}
		if err = t.Message.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	{ // Field #1 'Signature' (static)
		buf := buf[112:208]
		copy(t.Signature[:], buf)
	}
	return nil
}

func (t *SignedBeaconBlockHeader) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(SignedBeaconBlockHeader)
	}
	idx := hh.Index()
	{ // Field #0 'Message'
		t := t.Message
		if t == nil {
			t = new(BeaconBlockHeader)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return err
		}
	}
	{ // Field #1 'Signature'
		t := &t.Signature
		hh.PutBytes(t[:96])
	}
	hh.Merkleize(idx)
	return nil
}

func (t *SignedBeaconBlockHeader) HashTreeRoot() ([32]byte, error) {
	pool := &hasher.FastHasherPool
	hh := pool.Get()
	defer func() {
		pool.Put(hh)
	}()
	if err := t.HashTreeRootWith(hh); err != nil {
		return [32]byte{}, err
	}
	r, _ := hh.HashRoot()
	return r, nil
}
