// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: be3d10d4adc70322158ad8fbedc14ae3276d93c012681e86ca0dba12aa1594f1
// Version: v1.1.0 (https://github.com/pk910/dynamic-ssz)
package phase0

import (
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *SigningData) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *SigningData) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(SigningData)
	}
	{ // Field #0 'ObjectRoot'
		dst = append(dst, []byte(t.ObjectRoot[:32])...)
	}
	{ // Field #1 'Domain'
		dst = append(dst, []byte(t.Domain[:32])...)
	}
	return dst, nil
}

func (t *SigningData) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 64 {
		return sszutils.ErrUnexpectedEOF
	}
	{ // Field #0 'ObjectRoot' (static)
		buf := buf[0:32]
		copy(t.ObjectRoot[:], buf)
	}
	{ // Field #1 'Domain' (static)
		buf := buf[32:64]
		copy(t.Domain[:], buf)
	}
	return nil
}

func (t *SigningData) SizeSSZ() (size int) {
	return 64
}

func (t *SigningData) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}
func (t *SigningData) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(SigningData)
	}
	idx := hh.Index()
	{ // Field #0 'ObjectRoot'
		hh.PutBytes(t.ObjectRoot[:32])
	}
	{ // Field #1 'Domain'
		hh.PutBytes(t.Domain[:32])
	}
	hh.Merkleize(idx)
	return nil
}

