// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 2c256e6a2fcb1be9c2aef686cf2f34a10983e29cfd5632404bbf630ae203de87
// Version: v1.1.0 (https://github.com/pk910/dynamic-ssz)
package phase0

import (
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *Validator) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *Validator) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(Validator)
	}
	{ // Field #0 'PublicKey'
		t := &t.PublicKey
		dst = append(dst, []byte(t[:48])...)
	}
	{ // Field #1 'WithdrawalCredentials'
		t := t.WithdrawalCredentials
		vlen := len(t)
		if vlen > 32 {
			return dst, sszutils.ErrVectorLength
		}
		dst = append(dst, []byte(t[:vlen])...)
		if vlen < 32 {
			dst = sszutils.AppendZeroPadding(dst, (32-vlen)*1)
		}
	}
	{ // Field #2 'EffectiveBalance'
		t := t.EffectiveBalance
		dst = sszutils.MarshalUint64(dst, uint64(t))
	}
	{ // Field #3 'Slashed'
		t := t.Slashed
		dst = sszutils.MarshalBool(dst, bool(t))
	}
	{ // Field #4 'ActivationEligibilityEpoch'
		t := t.ActivationEligibilityEpoch
		dst = sszutils.MarshalUint64(dst, uint64(t))
	}
	{ // Field #5 'ActivationEpoch'
		t := t.ActivationEpoch
		dst = sszutils.MarshalUint64(dst, uint64(t))
	}
	{ // Field #6 'ExitEpoch'
		t := t.ExitEpoch
		dst = sszutils.MarshalUint64(dst, uint64(t))
	}
	{ // Field #7 'WithdrawableEpoch'
		t := t.WithdrawableEpoch
		dst = sszutils.MarshalUint64(dst, uint64(t))
	}
	return dst, nil
}

func (t *Validator) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 121 {
		return sszutils.ErrUnexpectedEOF
	}
	{ // Field #0 'PublicKey' (static)
		buf := buf[0:48]
		copy(t.PublicKey[:], buf)
	}
	{ // Field #1 'WithdrawalCredentials' (static)
		buf := buf[48:80]
		t.WithdrawalCredentials = sszutils.ExpandSlice(t.WithdrawalCredentials, 32)
		copy(t.WithdrawalCredentials[:], buf)
	}
	{ // Field #2 'EffectiveBalance' (static)
		buf := buf[80:88]
		t.EffectiveBalance = Gwei(sszutils.UnmarshallUint64(buf))
	}
	{ // Field #3 'Slashed' (static)
		buf := buf[88:89]
		t.Slashed = bool(sszutils.UnmarshalBool(buf))
	}
	{ // Field #4 'ActivationEligibilityEpoch' (static)
		buf := buf[89:97]
		t.ActivationEligibilityEpoch = Epoch(sszutils.UnmarshallUint64(buf))
	}
	{ // Field #5 'ActivationEpoch' (static)
		buf := buf[97:105]
		t.ActivationEpoch = Epoch(sszutils.UnmarshallUint64(buf))
	}
	{ // Field #6 'ExitEpoch' (static)
		buf := buf[105:113]
		t.ExitEpoch = Epoch(sszutils.UnmarshallUint64(buf))
	}
	{ // Field #7 'WithdrawableEpoch' (static)
		buf := buf[113:121]
		t.WithdrawableEpoch = Epoch(sszutils.UnmarshallUint64(buf))
	}
	return nil
}

func (t *Validator) SizeSSZ() (size int) {
	return 121
}

func (t *Validator) HashTreeRoot() ([32]byte, error) {
	pool := &hasher.FastHasherPool
	hh := pool.Get()
	defer func() {
		pool.Put(hh)
	}()
	if err := t.HashTreeRootWith(hh); err != nil {
		return [32]byte{}, err
	}
	r, _ := hh.HashRoot()
	return r, nil
}
func (t *Validator) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(Validator)
	}
	idx := hh.Index()
	{ // Field #0 'PublicKey'
		t := &t.PublicKey
		hh.PutBytes(t[:48])
	}
	{ // Field #1 'WithdrawalCredentials'
		t := t.WithdrawalCredentials
		vlen := len(t)
		if vlen > 32 {
			return sszutils.ErrVectorLength
		}
		val := t[:]
		if vlen < 32 {
			val = sszutils.AppendZeroPadding(val, (32-vlen)*1)
		}
		hh.PutBytes(val[:32])
	}
	{ // Field #2 'EffectiveBalance'
		t := t.EffectiveBalance
		hh.PutUint64(uint64(t))
	}
	{ // Field #3 'Slashed'
		t := t.Slashed
		hh.PutBool(t)
	}
	{ // Field #4 'ActivationEligibilityEpoch'
		t := t.ActivationEligibilityEpoch
		hh.PutUint64(uint64(t))
	}
	{ // Field #5 'ActivationEpoch'
		t := t.ActivationEpoch
		hh.PutUint64(uint64(t))
	}
	{ // Field #6 'ExitEpoch'
		t := t.ExitEpoch
		hh.PutUint64(uint64(t))
	}
	{ // Field #7 'WithdrawableEpoch'
		t := t.WithdrawableEpoch
		hh.PutUint64(uint64(t))
	}
	hh.Merkleize(idx)
	return nil
}

