// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 6931857ac246739b3b02b083c46e2e44e00de7a4263359843c3aba5251b49b26
// Version: v0.0.4 (https://github.com/pk910/dynamic-ssz)
package phase0

import (
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *VoluntaryExit) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	fn1 := func(t *VoluntaryExit) (err error) { // *phase0.VoluntaryExit
		// Field #0 'Epoch'
		dst = sszutils.MarshalUint64(dst, uint64(t.Epoch))
		// Field #1 'ValidatorIndex'
		dst = sszutils.MarshalUint64(dst, uint64(t.ValidatorIndex))
		return err
	}
	err = fn1(t)
	return dst, err
}
func (t *VoluntaryExit) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

func (t *VoluntaryExit) SizeSSZ() (size int) {
	sfn1 := func(t *VoluntaryExit) (size int) { // *VoluntaryExit
		size = 16
		return size
	}
	return sfn1(t)
}

func (t *VoluntaryExit) UnmarshalSSZ(buf []byte) (err error) {
	fn1 := func(t *VoluntaryExit, buf []byte) (*VoluntaryExit, error) { // *VoluntaryExit
		var err error
		if t == nil {
			t = new(VoluntaryExit)
		}
		buflen := len(buf)
		if buflen < 16 {
			return t, sszutils.ErrUnexpectedEOF
		}
		// Field #0 'Epoch'
		t.Epoch = (Epoch)(sszutils.UnmarshallUint64(buf[0:8]))
		// Field #1 'ValidatorIndex'
		t.ValidatorIndex = (ValidatorIndex)(sszutils.UnmarshallUint64(buf[8:16]))
		return t, err
	}
	_, err = fn1(t, buf)
	return err
}

func (t *VoluntaryExit) HashTreeRootWith(hh sszutils.HashWalker) error {
	fn1 := func(t *VoluntaryExit) (err error) { // *phase0.VoluntaryExit
		idx := hh.Index()
		// Field #0 'Epoch'
		hh.PutUint64(uint64(t.Epoch))
		// Field #1 'ValidatorIndex'
		hh.PutUint64(uint64(t.ValidatorIndex))
		hh.Merkleize(idx)
		return err
	}
	return fn1(t)
}
func (t *VoluntaryExit) HashTreeRoot() ([32]byte, error) {
	pool := &hasher.FastHasherPool
	hh := pool.Get()
	defer func() {
		pool.Put(hh)
	}()
	if err := t.HashTreeRootWith(hh); err != nil {
		return [32]byte{}, err
	}
	r, _ := hh.HashRoot()
	return r, nil
}
