// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 7246aa557afef6969b210d597ef4b6cdc56c54c2142fb7d519b13b399ce02f48
// Version: v1.3.1 (https://github.com/pk910/dynamic-ssz)
package capella

import (
	"encoding/binary"

	"github.com/attestantio/go-eth2-client/spec/phase0"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

// MarshalSSZ marshals the *BeaconBlock to SSZ-encoded bytes.
func (t *BeaconBlock) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *BeaconBlock to SSZ-encoded bytes, appending to the provided buffer.
func (t *BeaconBlock) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(BeaconBlock)
	}
	dstlen := len(dst)
	{ // Static Field #0 'Slot'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.Slot))
	}
	{ // Static Field #1 'ProposerIndex'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.ProposerIndex))
	}
	{ // Static Field #2 'ParentRoot'
		dst = append(dst, t.ParentRoot[:32]...)
	}
	{ // Static Field #3 'StateRoot'
		dst = append(dst, t.StateRoot[:32]...)
	}
	// Offset Field #4 'Body'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #4 'Body'
		binary.LittleEndian.PutUint32(dst[dstlen+80:], uint32(len(dst)-dstlen))
		t := t.Body
		if t == nil {
			t = new(BeaconBlockBody)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "Body")
		}
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *BeaconBlock from SSZ-encoded bytes.
func (t *BeaconBlock) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 84 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 84)
	}
	{ // Field #0 'Slot' (static)
		buf := buf[0:8]
		t.Slot = phase0.Slot(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #1 'ProposerIndex' (static)
		buf := buf[8:16]
		t.ProposerIndex = phase0.ValidatorIndex(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #2 'ParentRoot' (static)
		buf := buf[16:48]
		copy(t.ParentRoot[:], buf)
	}
	{ // Field #3 'StateRoot' (static)
		buf := buf[48:80]
		copy(t.StateRoot[:], buf)
	}
	// Field #4 'Body' (offset)
	offset4 := int(binary.LittleEndian.Uint32(buf[80:84]))
	if offset4 != 84 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset4, 84), "Body:o")
	}
	{ // Field #4 'Body' (dynamic)
		buf := buf[offset4:]
		if t.Body == nil {
			t.Body = new(BeaconBlockBody)
		}
		if err = t.Body.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "Body")
		}
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *BeaconBlock.
func (t *BeaconBlock) SizeSSZ() (size int) {
	if t == nil {
		t = new(BeaconBlock)
	}
	// Field #0 'Slot' static (8 bytes)
	// Field #1 'ProposerIndex' static (8 bytes)
	// Field #2 'ParentRoot' static (32 bytes)
	// Field #3 'StateRoot' static (32 bytes)
	// Field #4 'Body' offset (4 bytes)
	size += 84
	{ // Dynamic field #4 'Body'
		size += t.Body.SizeSSZ()
	}
	return size
}

// HashTreeRoot computes the SSZ hash tree root of the *BeaconBlock.
func (t *BeaconBlock) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *BeaconBlock using the given hash walker.
func (t *BeaconBlock) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(BeaconBlock)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Slot'
		hh.PutUint64(uint64(t.Slot))
	}
	{ // Field #1 'ProposerIndex'
		hh.PutUint64(uint64(t.ProposerIndex))
	}
	{ // Field #2 'ParentRoot'
		hh.PutBytes(t.ParentRoot[:32])
	}
	{ // Field #3 'StateRoot'
		hh.PutBytes(t.StateRoot[:32])
	}
	{ // Field #4 'Body'
		t := t.Body
		if t == nil {
			t = new(BeaconBlockBody)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "Body")
		}
	}
	hh.Merkleize(idx)
	return nil
}
