// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 816b120ae80f320cd4722fc7c1ad1bc91973eab501f026fb018919d70cfbf7ae
// Version: v1.3.1 (https://github.com/pk910/dynamic-ssz)
package capella

import (
	"encoding/binary"

	"github.com/attestantio/go-eth2-client/spec/altair"
	"github.com/attestantio/go-eth2-client/spec/phase0"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

// MarshalSSZ marshals the *BeaconState to SSZ-encoded bytes.
func (t *BeaconState) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *BeaconState to SSZ-encoded bytes, appending to the provided buffer.
func (t *BeaconState) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(BeaconState)
	}
	dstlen := len(dst)
	{ // Static Field #0 'GenesisTime'
		dst = binary.LittleEndian.AppendUint64(dst, t.GenesisTime)
	}
	{ // Static Field #1 'GenesisValidatorsRoot'
		dst = append(dst, t.GenesisValidatorsRoot[:32]...)
	}
	{ // Static Field #2 'Slot'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.Slot))
	}
	{ // Static Field #3 'Fork'
		t := t.Fork
		if t == nil {
			t = new(phase0.Fork)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "Fork")
		}
	}
	{ // Static Field #4 'LatestBlockHeader'
		t := t.LatestBlockHeader
		if t == nil {
			t = new(phase0.BeaconBlockHeader)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "LatestBlockHeader")
		}
	}
	{ // Static Field #5 'BlockRoots'
		t := t.BlockRoots
		vlen := len(t)
		if vlen > 8192 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, 8192), "BlockRoots")
		}
		for idx1 := range vlen {
			dst = append(dst, t[idx1][:32]...)
		}
		if vlen < 8192 {
			dst = sszutils.AppendZeroPadding(dst, (8192-vlen)*32)
		}
	}
	{ // Static Field #6 'StateRoots'
		t := t.StateRoots
		vlen := len(t)
		if vlen > 8192 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, 8192), "StateRoots")
		}
		for idx1 := range vlen {
			dst = append(dst, t[idx1][:32]...)
		}
		if vlen < 8192 {
			dst = sszutils.AppendZeroPadding(dst, (8192-vlen)*32)
		}
	}
	// Offset Field #7 'HistoricalRoots'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #8 'ETH1Data'
		t := t.ETH1Data
		if t == nil {
			t = new(phase0.ETH1Data)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "ETH1Data")
		}
	}
	// Offset Field #9 'ETH1DataVotes'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #10 'ETH1DepositIndex'
		dst = binary.LittleEndian.AppendUint64(dst, t.ETH1DepositIndex)
	}
	// Offset Field #11 'Validators'
	// Offset Field #12 'Balances'
	dst = append(dst, 0, 0, 0, 0, 0, 0, 0, 0)
	{ // Static Field #13 'RANDAOMixes'
		t := t.RANDAOMixes
		vlen := len(t)
		if vlen > 65536 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, 65536), "RANDAOMixes")
		}
		for idx1 := range vlen {
			dst = append(dst, t[idx1][:32]...)
		}
		if vlen < 65536 {
			dst = sszutils.AppendZeroPadding(dst, (65536-vlen)*32)
		}
	}
	{ // Static Field #14 'Slashings'
		t := t.Slashings
		vlen := len(t)
		if vlen > 8192 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, 8192), "Slashings")
		}
		dst = sszutils.MarshalUint64Slice(dst, t[:vlen])
		if vlen < 8192 {
			dst = sszutils.AppendZeroPadding(dst, (8192-vlen)*8)
		}
	}
	// Offset Field #15 'PreviousEpochParticipation'
	// Offset Field #16 'CurrentEpochParticipation'
	dst = append(dst, 0, 0, 0, 0, 0, 0, 0, 0)
	{ // Static Field #17 'JustificationBits'
		vlen := len(t.JustificationBits)
		if vlen > 1 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, 1), "JustificationBits")
		}
		dst = append(dst, t.JustificationBits[:vlen]...)
		if vlen < 1 {
			dst = sszutils.AppendZeroPadding(dst, (1-vlen)*1)
		}
	}
	{ // Static Field #18 'PreviousJustifiedCheckpoint'
		t := t.PreviousJustifiedCheckpoint
		if t == nil {
			t = new(phase0.Checkpoint)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "PreviousJustifiedCheckpoint")
		}
	}
	{ // Static Field #19 'CurrentJustifiedCheckpoint'
		t := t.CurrentJustifiedCheckpoint
		if t == nil {
			t = new(phase0.Checkpoint)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "CurrentJustifiedCheckpoint")
		}
	}
	{ // Static Field #20 'FinalizedCheckpoint'
		t := t.FinalizedCheckpoint
		if t == nil {
			t = new(phase0.Checkpoint)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "FinalizedCheckpoint")
		}
	}
	// Offset Field #21 'InactivityScores'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #22 'CurrentSyncCommittee'
		t := t.CurrentSyncCommittee
		if t == nil {
			t = new(altair.SyncCommittee)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "CurrentSyncCommittee")
		}
	}
	{ // Static Field #23 'NextSyncCommittee'
		t := t.NextSyncCommittee
		if t == nil {
			t = new(altair.SyncCommittee)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "NextSyncCommittee")
		}
	}
	// Offset Field #24 'LatestExecutionPayloadHeader'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #25 'NextWithdrawalIndex'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.NextWithdrawalIndex))
	}
	{ // Static Field #26 'NextWithdrawalValidatorIndex'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.NextWithdrawalValidatorIndex))
	}
	// Offset Field #27 'HistoricalSummaries'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #7 'HistoricalRoots'
		binary.LittleEndian.PutUint32(dst[dstlen+524464:], uint32(len(dst)-dstlen))
		t := t.HistoricalRoots
		vlen := len(t)
		if vlen > 16777216 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 16777216), "HistoricalRoots")
		}
		for idx1 := range vlen {
			dst = append(dst, t[idx1][:32]...)
		}
	}
	{ // Dynamic Field #9 'ETH1DataVotes'
		binary.LittleEndian.PutUint32(dst[dstlen+524540:], uint32(len(dst)-dstlen))
		t := t.ETH1DataVotes
		vlen := len(t)
		if vlen > 2048 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 2048), "ETH1DataVotes")
		}
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(phase0.ETH1Data)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "ETH1DataVotes[%d]", idx1)
			}
		}
	}
	{ // Dynamic Field #11 'Validators'
		binary.LittleEndian.PutUint32(dst[dstlen+524552:], uint32(len(dst)-dstlen))
		t := t.Validators
		vlen := len(t)
		if vlen > 1099511627776 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 1099511627776), "Validators")
		}
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(phase0.Validator)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "Validators[%d]", idx1)
			}
		}
	}
	{ // Dynamic Field #12 'Balances'
		binary.LittleEndian.PutUint32(dst[dstlen+524556:], uint32(len(dst)-dstlen))
		t := t.Balances
		vlen := len(t)
		if vlen > 1099511627776 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 1099511627776), "Balances")
		}
		dst = sszutils.MarshalUint64Slice(dst, t[:vlen])
	}
	{ // Dynamic Field #15 'PreviousEpochParticipation'
		binary.LittleEndian.PutUint32(dst[dstlen+2687248:], uint32(len(dst)-dstlen))
		t := t.PreviousEpochParticipation
		vlen := len(t)
		if vlen > 1099511627776 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 1099511627776), "PreviousEpochParticipation")
		}
		for idx1 := range vlen {
			dst = append(dst, byte(t[idx1]))
		}
	}
	{ // Dynamic Field #16 'CurrentEpochParticipation'
		binary.LittleEndian.PutUint32(dst[dstlen+2687252:], uint32(len(dst)-dstlen))
		t := t.CurrentEpochParticipation
		vlen := len(t)
		if vlen > 1099511627776 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 1099511627776), "CurrentEpochParticipation")
		}
		for idx1 := range vlen {
			dst = append(dst, byte(t[idx1]))
		}
	}
	{ // Dynamic Field #21 'InactivityScores'
		binary.LittleEndian.PutUint32(dst[dstlen+2687377:], uint32(len(dst)-dstlen))
		t := t.InactivityScores
		vlen := len(t)
		if vlen > 1099511627776 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 1099511627776), "InactivityScores")
		}
		dst = sszutils.MarshalUint64Slice(dst, t[:vlen])
	}
	{ // Dynamic Field #24 'LatestExecutionPayloadHeader'
		binary.LittleEndian.PutUint32(dst[dstlen+2736629:], uint32(len(dst)-dstlen))
		t := t.LatestExecutionPayloadHeader
		if t == nil {
			t = new(ExecutionPayloadHeader)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "LatestExecutionPayloadHeader")
		}
	}
	{ // Dynamic Field #27 'HistoricalSummaries'
		binary.LittleEndian.PutUint32(dst[dstlen+2736649:], uint32(len(dst)-dstlen))
		t := t.HistoricalSummaries
		vlen := len(t)
		if vlen > 16777216 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 16777216), "HistoricalSummaries")
		}
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(HistoricalSummary)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "HistoricalSummaries[%d]", idx1)
			}
		}
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *BeaconState from SSZ-encoded bytes.
func (t *BeaconState) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 2736653 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 2736653)
	}
	{ // Field #0 'GenesisTime' (static)
		buf := buf[0:8]
		t.GenesisTime = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #1 'GenesisValidatorsRoot' (static)
		buf := buf[8:40]
		copy(t.GenesisValidatorsRoot[:], buf)
	}
	{ // Field #2 'Slot' (static)
		buf := buf[40:48]
		t.Slot = phase0.Slot(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #3 'Fork' (static)
		buf := buf[48:64]
		if t.Fork == nil {
			t.Fork = new(phase0.Fork)
		}
		if err = t.Fork.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "Fork")
		}
	}
	{ // Field #4 'LatestBlockHeader' (static)
		buf := buf[64:176]
		if t.LatestBlockHeader == nil {
			t.LatestBlockHeader = new(phase0.BeaconBlockHeader)
		}
		if err = t.LatestBlockHeader.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "LatestBlockHeader")
		}
	}
	{ // Field #5 'BlockRoots' (static)
		buf := buf[176:262320]
		val1 := t.BlockRoots
		val1 = sszutils.ExpandSlice(val1, 8192)
		for idx1 := range 8192 {
			buf := buf[32*idx1 : 32*(idx1+1)]
			copy(val1[idx1][:], buf)
		}
		t.BlockRoots = val1
	}
	{ // Field #6 'StateRoots' (static)
		buf := buf[262320:524464]
		val2 := t.StateRoots
		val2 = sszutils.ExpandSlice(val2, 8192)
		for idx1 := range 8192 {
			buf := buf[32*idx1 : 32*(idx1+1)]
			copy(val2[idx1][:], buf)
		}
		t.StateRoots = val2
	}
	// Field #7 'HistoricalRoots' (offset)
	offset7 := int(binary.LittleEndian.Uint32(buf[524464:524468]))
	if offset7 != 2736653 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset7, 2736653), "HistoricalRoots:o")
	}
	{ // Field #8 'ETH1Data' (static)
		buf := buf[524468:524540]
		if t.ETH1Data == nil {
			t.ETH1Data = new(phase0.ETH1Data)
		}
		if err = t.ETH1Data.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "ETH1Data")
		}
	}
	// Field #9 'ETH1DataVotes' (offset)
	offset9 := int(binary.LittleEndian.Uint32(buf[524540:524544]))
	if offset9 < offset7 || offset9 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset9, offset7, buflen), "ETH1DataVotes:o")
	}
	{ // Field #10 'ETH1DepositIndex' (static)
		buf := buf[524544:524552]
		t.ETH1DepositIndex = binary.LittleEndian.Uint64(buf)
	}
	// Field #11 'Validators' (offset)
	offset11 := int(binary.LittleEndian.Uint32(buf[524552:524556]))
	if offset11 < offset9 || offset11 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset11, offset9, buflen), "Validators:o")
	}
	// Field #12 'Balances' (offset)
	offset12 := int(binary.LittleEndian.Uint32(buf[524556:524560]))
	if offset12 < offset11 || offset12 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset12, offset11, buflen), "Balances:o")
	}
	{ // Field #13 'RANDAOMixes' (static)
		buf := buf[524560:2621712]
		val3 := t.RANDAOMixes
		val3 = sszutils.ExpandSlice(val3, 65536)
		for idx1 := range 65536 {
			buf := buf[32*idx1 : 32*(idx1+1)]
			copy(val3[idx1][:], buf)
		}
		t.RANDAOMixes = val3
	}
	{ // Field #14 'Slashings' (static)
		buf := buf[2621712:2687248]
		val4 := t.Slashings
		val4 = sszutils.ExpandSlice(val4, 8192)
		sszutils.UnmarshalUint64Slice(val4[:8192], buf)
		t.Slashings = val4
	}
	// Field #15 'PreviousEpochParticipation' (offset)
	offset15 := int(binary.LittleEndian.Uint32(buf[2687248:2687252]))
	if offset15 < offset12 || offset15 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset15, offset12, buflen), "PreviousEpochParticipation:o")
	}
	// Field #16 'CurrentEpochParticipation' (offset)
	offset16 := int(binary.LittleEndian.Uint32(buf[2687252:2687256]))
	if offset16 < offset15 || offset16 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset16, offset15, buflen), "CurrentEpochParticipation:o")
	}
	{ // Field #17 'JustificationBits' (static)
		buf := buf[2687256:2687257]
		t.JustificationBits = sszutils.ExpandSlice(t.JustificationBits, 1)
		copy(t.JustificationBits[:], buf)
	}
	{ // Field #18 'PreviousJustifiedCheckpoint' (static)
		buf := buf[2687257:2687297]
		if t.PreviousJustifiedCheckpoint == nil {
			t.PreviousJustifiedCheckpoint = new(phase0.Checkpoint)
		}
		if err = t.PreviousJustifiedCheckpoint.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "PreviousJustifiedCheckpoint")
		}
	}
	{ // Field #19 'CurrentJustifiedCheckpoint' (static)
		buf := buf[2687297:2687337]
		if t.CurrentJustifiedCheckpoint == nil {
			t.CurrentJustifiedCheckpoint = new(phase0.Checkpoint)
		}
		if err = t.CurrentJustifiedCheckpoint.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "CurrentJustifiedCheckpoint")
		}
	}
	{ // Field #20 'FinalizedCheckpoint' (static)
		buf := buf[2687337:2687377]
		if t.FinalizedCheckpoint == nil {
			t.FinalizedCheckpoint = new(phase0.Checkpoint)
		}
		if err = t.FinalizedCheckpoint.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "FinalizedCheckpoint")
		}
	}
	// Field #21 'InactivityScores' (offset)
	offset21 := int(binary.LittleEndian.Uint32(buf[2687377:2687381]))
	if offset21 < offset16 || offset21 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset21, offset16, buflen), "InactivityScores:o")
	}
	{ // Field #22 'CurrentSyncCommittee' (static)
		buf := buf[2687381:2712005]
		if t.CurrentSyncCommittee == nil {
			t.CurrentSyncCommittee = new(altair.SyncCommittee)
		}
		if err = t.CurrentSyncCommittee.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "CurrentSyncCommittee")
		}
	}
	{ // Field #23 'NextSyncCommittee' (static)
		buf := buf[2712005:2736629]
		if t.NextSyncCommittee == nil {
			t.NextSyncCommittee = new(altair.SyncCommittee)
		}
		if err = t.NextSyncCommittee.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "NextSyncCommittee")
		}
	}
	// Field #24 'LatestExecutionPayloadHeader' (offset)
	offset24 := int(binary.LittleEndian.Uint32(buf[2736629:2736633]))
	if offset24 < offset21 || offset24 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset24, offset21, buflen), "LatestExecutionPayloadHeader:o")
	}
	{ // Field #25 'NextWithdrawalIndex' (static)
		buf := buf[2736633:2736641]
		t.NextWithdrawalIndex = WithdrawalIndex(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #26 'NextWithdrawalValidatorIndex' (static)
		buf := buf[2736641:2736649]
		t.NextWithdrawalValidatorIndex = phase0.ValidatorIndex(binary.LittleEndian.Uint64(buf))
	}
	// Field #27 'HistoricalSummaries' (offset)
	offset27 := int(binary.LittleEndian.Uint32(buf[2736649:2736653]))
	if offset27 < offset24 || offset27 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset27, offset24, buflen), "HistoricalSummaries:o")
	}
	{ // Field #7 'HistoricalRoots' (dynamic)
		buf := buf[offset7:offset9]
		val5 := t.HistoricalRoots
		itemCount := len(buf) / 32
		if len(buf)%32 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 32), "HistoricalRoots")
		}
		if itemCount > 16777216 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 16777216), "HistoricalRoots")
		}
		val5 = sszutils.ExpandSlice(val5, itemCount)
		for idx1 := range itemCount {
			buf := buf[32*idx1 : 32*(idx1+1)]
			copy(val5[idx1][:], buf)
		}
		t.HistoricalRoots = val5
	}
	{ // Field #9 'ETH1DataVotes' (dynamic)
		buf := buf[offset9:offset11]
		val6 := t.ETH1DataVotes
		itemCount := len(buf) / 72
		if len(buf)%72 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 72), "ETH1DataVotes")
		}
		if itemCount > 2048 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 2048), "ETH1DataVotes")
		}
		val6 = sszutils.ExpandSlice(val6, itemCount)
		for idx1 := range itemCount {
			if val6[idx1] == nil {
				val6[idx1] = new(phase0.ETH1Data)
			}
			buf := buf[72*idx1 : 72*(idx1+1)]
			if err = val6[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "ETH1DataVotes[%d]", idx1)
			}
		}
		t.ETH1DataVotes = val6
	}
	{ // Field #11 'Validators' (dynamic)
		buf := buf[offset11:offset12]
		val7 := t.Validators
		itemCount := len(buf) / 121
		if len(buf)%121 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 121), "Validators")
		}
		if itemCount > 1099511627776 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 1099511627776), "Validators")
		}
		val7 = sszutils.ExpandSlice(val7, itemCount)
		for idx1 := range itemCount {
			if val7[idx1] == nil {
				val7[idx1] = new(phase0.Validator)
			}
			buf := buf[121*idx1 : 121*(idx1+1)]
			if err = val7[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "Validators[%d]", idx1)
			}
		}
		t.Validators = val7
	}
	{ // Field #12 'Balances' (dynamic)
		buf := buf[offset12:offset15]
		val8 := t.Balances
		itemCount := len(buf) / 8
		if len(buf)%8 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 8), "Balances")
		}
		if itemCount > 1099511627776 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 1099511627776), "Balances")
		}
		val8 = sszutils.ExpandSlice(val8, itemCount)
		sszutils.UnmarshalUint64Slice(val8, buf)
		t.Balances = val8
	}
	{ // Field #15 'PreviousEpochParticipation' (dynamic)
		buf := buf[offset15:offset16]
		val9 := t.PreviousEpochParticipation
		itemCount := len(buf)
		if itemCount > 1099511627776 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 1099511627776), "PreviousEpochParticipation")
		}
		val9 = sszutils.ExpandSlice(val9, itemCount)
		for idx1 := range itemCount {
			buf := buf[1*idx1 : 1*(idx1+1)]
			val9[idx1] = altair.ParticipationFlags(buf[0])
		}
		t.PreviousEpochParticipation = val9
	}
	{ // Field #16 'CurrentEpochParticipation' (dynamic)
		buf := buf[offset16:offset21]
		val10 := t.CurrentEpochParticipation
		itemCount := len(buf)
		if itemCount > 1099511627776 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 1099511627776), "CurrentEpochParticipation")
		}
		val10 = sszutils.ExpandSlice(val10, itemCount)
		for idx1 := range itemCount {
			buf := buf[1*idx1 : 1*(idx1+1)]
			val10[idx1] = altair.ParticipationFlags(buf[0])
		}
		t.CurrentEpochParticipation = val10
	}
	{ // Field #21 'InactivityScores' (dynamic)
		buf := buf[offset21:offset24]
		val11 := t.InactivityScores
		itemCount := len(buf) / 8
		if len(buf)%8 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 8), "InactivityScores")
		}
		if itemCount > 1099511627776 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 1099511627776), "InactivityScores")
		}
		val11 = sszutils.ExpandSlice(val11, itemCount)
		sszutils.UnmarshalUint64Slice(val11, buf)
		t.InactivityScores = val11
	}
	{ // Field #24 'LatestExecutionPayloadHeader' (dynamic)
		buf := buf[offset24:offset27]
		if t.LatestExecutionPayloadHeader == nil {
			t.LatestExecutionPayloadHeader = new(ExecutionPayloadHeader)
		}
		if err = t.LatestExecutionPayloadHeader.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "LatestExecutionPayloadHeader")
		}
	}
	{ // Field #27 'HistoricalSummaries' (dynamic)
		buf := buf[offset27:]
		val12 := t.HistoricalSummaries
		itemCount := len(buf) / 64
		if len(buf)%64 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 64), "HistoricalSummaries")
		}
		if itemCount > 16777216 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 16777216), "HistoricalSummaries")
		}
		val12 = sszutils.ExpandSlice(val12, itemCount)
		for idx1 := range itemCount {
			if val12[idx1] == nil {
				val12[idx1] = new(HistoricalSummary)
			}
			buf := buf[64*idx1 : 64*(idx1+1)]
			if err = val12[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "HistoricalSummaries[%d]", idx1)
			}
		}
		t.HistoricalSummaries = val12
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *BeaconState.
func (t *BeaconState) SizeSSZ() (size int) {
	if t == nil {
		t = new(BeaconState)
	}
	// Field #0 'GenesisTime' static (8 bytes)
	// Field #1 'GenesisValidatorsRoot' static (32 bytes)
	// Field #2 'Slot' static (8 bytes)
	// Field #3 'Fork' static (16 bytes)
	// Field #4 'LatestBlockHeader' static (112 bytes)
	// Field #5 'BlockRoots' static (262144 bytes)
	// Field #6 'StateRoots' static (262144 bytes)
	// Field #7 'HistoricalRoots' offset (4 bytes)
	// Field #8 'ETH1Data' static (72 bytes)
	// Field #9 'ETH1DataVotes' offset (4 bytes)
	// Field #10 'ETH1DepositIndex' static (8 bytes)
	// Field #11 'Validators' offset (4 bytes)
	// Field #12 'Balances' offset (4 bytes)
	// Field #13 'RANDAOMixes' static (2097152 bytes)
	// Field #14 'Slashings' static (65536 bytes)
	// Field #15 'PreviousEpochParticipation' offset (4 bytes)
	// Field #16 'CurrentEpochParticipation' offset (4 bytes)
	// Field #17 'JustificationBits' static (1 bytes)
	// Field #18 'PreviousJustifiedCheckpoint' static (40 bytes)
	// Field #19 'CurrentJustifiedCheckpoint' static (40 bytes)
	// Field #20 'FinalizedCheckpoint' static (40 bytes)
	// Field #21 'InactivityScores' offset (4 bytes)
	// Field #22 'CurrentSyncCommittee' static (24624 bytes)
	// Field #23 'NextSyncCommittee' static (24624 bytes)
	// Field #24 'LatestExecutionPayloadHeader' offset (4 bytes)
	// Field #25 'NextWithdrawalIndex' static (8 bytes)
	// Field #26 'NextWithdrawalValidatorIndex' static (8 bytes)
	// Field #27 'HistoricalSummaries' offset (4 bytes)
	size += 2736653
	{ // Dynamic field #7 'HistoricalRoots'
		size += len(t.HistoricalRoots) * 32
	}
	{ // Dynamic field #9 'ETH1DataVotes'
		size += len(t.ETH1DataVotes) * 72
	}
	{ // Dynamic field #11 'Validators'
		size += len(t.Validators) * 121
	}
	{ // Dynamic field #12 'Balances'
		size += len(t.Balances) * 8
	}
	{ // Dynamic field #15 'PreviousEpochParticipation'
		size += len(t.PreviousEpochParticipation)
	}
	{ // Dynamic field #16 'CurrentEpochParticipation'
		size += len(t.CurrentEpochParticipation)
	}
	{ // Dynamic field #21 'InactivityScores'
		size += len(t.InactivityScores) * 8
	}
	{ // Dynamic field #24 'LatestExecutionPayloadHeader'
		size += t.LatestExecutionPayloadHeader.SizeSSZ()
	}
	{ // Dynamic field #27 'HistoricalSummaries'
		size += len(t.HistoricalSummaries) * 64
	}
	return size
}

// HashTreeRoot computes the SSZ hash tree root of the *BeaconState.
func (t *BeaconState) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *BeaconState using the given hash walker.
func (t *BeaconState) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(BeaconState)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'GenesisTime'
		hh.PutUint64(t.GenesisTime)
	}
	{ // Field #1 'GenesisValidatorsRoot'
		hh.PutBytes(t.GenesisValidatorsRoot[:32])
	}
	{ // Field #2 'Slot'
		hh.PutUint64(uint64(t.Slot))
	}
	{ // Field #3 'Fork'
		t := t.Fork
		if t == nil {
			t = new(phase0.Fork)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "Fork")
		}
	}
	{ // Field #4 'LatestBlockHeader'
		t := t.LatestBlockHeader
		if t == nil {
			t = new(phase0.BeaconBlockHeader)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "LatestBlockHeader")
		}
	}
	{ // Field #5 'BlockRoots'
		t := t.BlockRoots
		vlen := len(t)
		if vlen > 8192 {
			return sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, 8192), "BlockRoots")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		var val1 *phase0.Root
		for idx1 := range 8192 {
			if idx1 < vlen {
				val1 = &t[idx1]
			} else if idx1 == vlen {
				val1 = new(phase0.Root)
			}
			hh.PutBytes(val1[:32])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.Merkleize(idx)
	}
	{ // Field #6 'StateRoots'
		t := t.StateRoots
		vlen := len(t)
		if vlen > 8192 {
			return sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, 8192), "StateRoots")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		var val2 *phase0.Root
		for idx1 := range 8192 {
			if idx1 < vlen {
				val2 = &t[idx1]
			} else if idx1 == vlen {
				val2 = new(phase0.Root)
			}
			hh.PutBytes(val2[:32])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.Merkleize(idx)
	}
	{ // Field #7 'HistoricalRoots'
		t := t.HistoricalRoots
		vlen := uint64(len(t))
		if vlen > 16777216 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 16777216), "HistoricalRoots")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			hh.PutBytes(t[idx1][:32])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(16777216, vlen, 32))
	}
	{ // Field #8 'ETH1Data'
		t := t.ETH1Data
		if t == nil {
			t = new(phase0.ETH1Data)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "ETH1Data")
		}
	}
	{ // Field #9 'ETH1DataVotes'
		t := t.ETH1DataVotes
		vlen := uint64(len(t))
		if vlen > 2048 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 2048), "ETH1DataVotes")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			t := t[idx1]
			if t == nil {
				t = new(phase0.ETH1Data)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "ETH1DataVotes[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(2048, vlen, 32))
	}
	{ // Field #10 'ETH1DepositIndex'
		hh.PutUint64(t.ETH1DepositIndex)
	}
	{ // Field #11 'Validators'
		t := t.Validators
		vlen := uint64(len(t))
		if vlen > 1099511627776 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 1099511627776), "Validators")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			t := t[idx1]
			if t == nil {
				t = new(phase0.Validator)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "Validators[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(1099511627776, vlen, 32))
	}
	{ // Field #12 'Balances'
		t := t.Balances
		vlen := uint64(len(t))
		if vlen > 1099511627776 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 1099511627776), "Balances")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		sszutils.HashUint64Slice(hh, t)
		hh.FillUpTo32()
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(1099511627776, vlen, 8))
	}
	{ // Field #13 'RANDAOMixes'
		t := t.RANDAOMixes
		vlen := len(t)
		if vlen > 65536 {
			return sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, 65536), "RANDAOMixes")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		var val3 *phase0.Root
		for idx1 := range 65536 {
			if idx1 < vlen {
				val3 = &t[idx1]
			} else if idx1 == vlen {
				val3 = new(phase0.Root)
			}
			hh.PutBytes(val3[:32])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.Merkleize(idx)
	}
	{ // Field #14 'Slashings'
		t := t.Slashings
		vlen := len(t)
		if vlen > 8192 {
			return sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, 8192), "Slashings")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		var val4, val4Empty phase0.Gwei
		for idx1 := range 8192 {
			if idx1 < vlen {
				val4 = t[idx1]
			} else if idx1 == vlen {
				val4 = val4Empty
			}
			hh.AppendUint64(uint64(val4))
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.FillUpTo32()
		hh.Merkleize(idx)
	}
	{ // Field #15 'PreviousEpochParticipation'
		t := t.PreviousEpochParticipation
		vlen := uint64(len(t))
		if vlen > 1099511627776 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 1099511627776), "PreviousEpochParticipation")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			hh.AppendUint8(uint8(t[idx1]))
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.FillUpTo32()
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(1099511627776, vlen, 1))
	}
	{ // Field #16 'CurrentEpochParticipation'
		t := t.CurrentEpochParticipation
		vlen := uint64(len(t))
		if vlen > 1099511627776 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 1099511627776), "CurrentEpochParticipation")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			hh.AppendUint8(uint8(t[idx1]))
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.FillUpTo32()
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(1099511627776, vlen, 1))
	}
	{ // Field #17 'JustificationBits'
		vlen := len(t.JustificationBits)
		if vlen > 1 {
			return sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, 1), "JustificationBits")
		}
		val := t.JustificationBits[:]
		if vlen < 1 {
			val = sszutils.AppendZeroPadding(val, (1-vlen)*1)
		}
		hh.PutBytes(val[:1])
	}
	{ // Field #18 'PreviousJustifiedCheckpoint'
		t := t.PreviousJustifiedCheckpoint
		if t == nil {
			t = new(phase0.Checkpoint)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "PreviousJustifiedCheckpoint")
		}
	}
	{ // Field #19 'CurrentJustifiedCheckpoint'
		t := t.CurrentJustifiedCheckpoint
		if t == nil {
			t = new(phase0.Checkpoint)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "CurrentJustifiedCheckpoint")
		}
	}
	{ // Field #20 'FinalizedCheckpoint'
		t := t.FinalizedCheckpoint
		if t == nil {
			t = new(phase0.Checkpoint)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "FinalizedCheckpoint")
		}
	}
	{ // Field #21 'InactivityScores'
		t := t.InactivityScores
		vlen := uint64(len(t))
		if vlen > 1099511627776 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 1099511627776), "InactivityScores")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		sszutils.HashUint64Slice(hh, t)
		hh.FillUpTo32()
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(1099511627776, vlen, 8))
	}
	{ // Field #22 'CurrentSyncCommittee'
		t := t.CurrentSyncCommittee
		if t == nil {
			t = new(altair.SyncCommittee)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "CurrentSyncCommittee")
		}
	}
	{ // Field #23 'NextSyncCommittee'
		t := t.NextSyncCommittee
		if t == nil {
			t = new(altair.SyncCommittee)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "NextSyncCommittee")
		}
	}
	{ // Field #24 'LatestExecutionPayloadHeader'
		t := t.LatestExecutionPayloadHeader
		if t == nil {
			t = new(ExecutionPayloadHeader)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "LatestExecutionPayloadHeader")
		}
	}
	{ // Field #25 'NextWithdrawalIndex'
		hh.PutUint64(uint64(t.NextWithdrawalIndex))
	}
	{ // Field #26 'NextWithdrawalValidatorIndex'
		hh.PutUint64(uint64(t.NextWithdrawalValidatorIndex))
	}
	{ // Field #27 'HistoricalSummaries'
		t := t.HistoricalSummaries
		vlen := uint64(len(t))
		if vlen > 16777216 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 16777216), "HistoricalSummaries")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			t := t[idx1]
			if t == nil {
				t = new(HistoricalSummary)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "HistoricalSummaries[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(16777216, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}
