// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 1adf9d87c0daf2d5ca512a05673e6122f02eb93cea160ccd42328f11064fdd9e
// Version: v1.3.0 (https://github.com/pk910/dynamic-ssz)
package capella

import (
	"encoding/binary"

	"github.com/attestantio/go-eth2-client/spec/phase0"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

// MarshalSSZ marshals the *BLSToExecutionChange to SSZ-encoded bytes.
func (t *BLSToExecutionChange) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *BLSToExecutionChange to SSZ-encoded bytes, appending to the provided buffer.
func (t *BLSToExecutionChange) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(BLSToExecutionChange)
	}
	{ // Static Field #0 'ValidatorIndex'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.ValidatorIndex))
	}
	{ // Static Field #1 'FromBLSPubkey'
		dst = append(dst, t.FromBLSPubkey[:48]...)
	}
	{ // Static Field #2 'ToExecutionAddress'
		dst = append(dst, t.ToExecutionAddress[:20]...)
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *BLSToExecutionChange from SSZ-encoded bytes.
func (t *BLSToExecutionChange) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 76 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 76)
	}
	{ // Field #0 'ValidatorIndex' (static)
		buf := buf[0:8]
		t.ValidatorIndex = phase0.ValidatorIndex(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #1 'FromBLSPubkey' (static)
		buf := buf[8:56]
		copy(t.FromBLSPubkey[:], buf)
	}
	{ // Field #2 'ToExecutionAddress' (static)
		buf := buf[56:76]
		copy(t.ToExecutionAddress[:], buf)
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *BLSToExecutionChange.
func (t *BLSToExecutionChange) SizeSSZ() (size int) {
	return 76
}

// HashTreeRoot computes the SSZ hash tree root of the *BLSToExecutionChange.
func (t *BLSToExecutionChange) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}
// HashTreeRootWith computes the SSZ hash tree root of the *BLSToExecutionChange using the given hash walker.
func (t *BLSToExecutionChange) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(BLSToExecutionChange)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'ValidatorIndex'
		hh.PutUint64(uint64(t.ValidatorIndex))
	}
	{ // Field #1 'FromBLSPubkey'
		hh.PutBytes(t.FromBLSPubkey[:48])
	}
	{ // Field #2 'ToExecutionAddress'
		hh.PutBytes(t.ToExecutionAddress[:20])
	}
	hh.Merkleize(idx)
	return nil
}
