// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 1ea5c2b15f49dc58c9cac387e469b69b57a391726c89357f3c3475750b2865b7
// Version: v1.3.1 (https://github.com/pk910/dynamic-ssz)
package capella

import (
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

// MarshalSSZ marshals the *SignedBLSToExecutionChange to SSZ-encoded bytes.
func (t *SignedBLSToExecutionChange) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *SignedBLSToExecutionChange to SSZ-encoded bytes, appending to the provided buffer.
func (t *SignedBLSToExecutionChange) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(SignedBLSToExecutionChange)
	}
	{ // Static Field #0 'Message'
		t := t.Message
		if t == nil {
			t = new(BLSToExecutionChange)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "Message")
		}
	}
	{ // Static Field #1 'Signature'
		dst = append(dst, t.Signature[:96]...)
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *SignedBLSToExecutionChange from SSZ-encoded bytes.
func (t *SignedBLSToExecutionChange) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 172 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 172)
	}
	{ // Field #0 'Message' (static)
		buf := buf[0:76]
		if t.Message == nil {
			t.Message = new(BLSToExecutionChange)
		}
		if err = t.Message.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "Message")
		}
	}
	{ // Field #1 'Signature' (static)
		buf := buf[76:172]
		copy(t.Signature[:], buf)
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *SignedBLSToExecutionChange.
func (t *SignedBLSToExecutionChange) SizeSSZ() (size int) {
	return 172
}

// HashTreeRoot computes the SSZ hash tree root of the *SignedBLSToExecutionChange.
func (t *SignedBLSToExecutionChange) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *SignedBLSToExecutionChange using the given hash walker.
func (t *SignedBLSToExecutionChange) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(SignedBLSToExecutionChange)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Message'
		t := t.Message
		if t == nil {
			t = new(BLSToExecutionChange)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "Message")
		}
	}
	{ // Field #1 'Signature'
		hh.PutBytes(t.Signature[:96])
	}
	hh.Merkleize(idx)
	return nil
}
