// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 01ae2935cabf8ef95bd3d978abf67cf1baae4a4a25d96d4ac230614212d3dd49
// Version: v0.0.4 (https://github.com/pk910/dynamic-ssz)
package capella

import (
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *SignedBLSToExecutionChange) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	fn1 := func(t *BLSToExecutionChange) (err error) { // *capella.BLSToExecutionChange
		dst, err = t.MarshalSSZTo(dst)
		return err
	}
	fn2 := func(t *SignedBLSToExecutionChange) (err error) { // *capella.SignedBLSToExecutionChange
		// Field #0 'Message'
		if err = fn1(t.Message); err != nil {
			return err
		}
		// Field #1 'Signature'
		dst = append(dst, t.Signature[:]...)
		return err
	}
	err = fn2(t)
	return dst, err
}
func (t *SignedBLSToExecutionChange) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

func (t *SignedBLSToExecutionChange) SizeSSZ() (size int) {
	sfn1 := func(t *SignedBLSToExecutionChange) (size int) { // *SignedBLSToExecutionChange
		size = 172
		return size
	}
	return sfn1(t)
}

func (t *SignedBLSToExecutionChange) UnmarshalSSZ(buf []byte) (err error) {
	fn1 := func(t *BLSToExecutionChange, buf []byte) (*BLSToExecutionChange, error) { // *BLSToExecutionChange
		var err error
		if t == nil {
			t = new(BLSToExecutionChange)
		}
		err = t.UnmarshalSSZ(buf)
		return t, err
	}
	fn2 := func(t *SignedBLSToExecutionChange, buf []byte) (*SignedBLSToExecutionChange, error) { // *SignedBLSToExecutionChange
		var err error
		if t == nil {
			t = new(SignedBLSToExecutionChange)
		}
		buflen := len(buf)
		if buflen < 172 {
			return t, sszutils.ErrUnexpectedEOF
		}
		// Field #0 'Message'
		if t.Message, err = fn1(t.Message, buf[0:76]); err != nil {
			return t, err
		}
		// Field #1 'Signature'
		copy(t.Signature[:], buf[76:172])
		return t, err
	}
	_, err = fn2(t, buf)
	return err
}

func (t *SignedBLSToExecutionChange) HashTreeRootWith(hh sszutils.HashWalker) error {
	fn1 := func(t *SignedBLSToExecutionChange) (err error) { // *capella.SignedBLSToExecutionChange
		idx := hh.Index()
		// Field #0 'Message'
		if err = t.Message.HashTreeRootWith(hh); err != nil {
			return err
		}
		// Field #1 'Signature'
		hh.PutBytes(t.Signature[:])
		hh.Merkleize(idx)
		return err
	}
	return fn1(t)
}
func (t *SignedBLSToExecutionChange) HashTreeRoot() ([32]byte, error) {
	pool := &hasher.FastHasherPool
	hh := pool.Get()
	defer func() {
		pool.Put(hh)
	}()
	if err := t.HashTreeRootWith(hh); err != nil {
		return [32]byte{}, err
	}
	r, _ := hh.HashRoot()
	return r, nil
}
