// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: dde609e622a941e373617d8b52802870a55e9364e098cd4553497715c6c58032
// Version: v1.3.0 (https://github.com/pk910/dynamic-ssz)
package capella

import (
	"encoding/binary"

	"github.com/attestantio/go-eth2-client/spec/phase0"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

// MarshalSSZ marshals the *Withdrawal to SSZ-encoded bytes.
func (t *Withdrawal) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *Withdrawal to SSZ-encoded bytes, appending to the provided buffer.
func (t *Withdrawal) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(Withdrawal)
	}
	{ // Static Field #0 'Index'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.Index))
	}
	{ // Static Field #1 'ValidatorIndex'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.ValidatorIndex))
	}
	{ // Static Field #2 'Address'
		dst = append(dst, t.Address[:20]...)
	}
	{ // Static Field #3 'Amount'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.Amount))
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *Withdrawal from SSZ-encoded bytes.
func (t *Withdrawal) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 44 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 44)
	}
	{ // Field #0 'Index' (static)
		buf := buf[0:8]
		t.Index = WithdrawalIndex(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #1 'ValidatorIndex' (static)
		buf := buf[8:16]
		t.ValidatorIndex = phase0.ValidatorIndex(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #2 'Address' (static)
		buf := buf[16:36]
		copy(t.Address[:], buf)
	}
	{ // Field #3 'Amount' (static)
		buf := buf[36:44]
		t.Amount = phase0.Gwei(binary.LittleEndian.Uint64(buf))
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *Withdrawal.
func (t *Withdrawal) SizeSSZ() (size int) {
	return 44
}

// HashTreeRoot computes the SSZ hash tree root of the *Withdrawal.
func (t *Withdrawal) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}
// HashTreeRootWith computes the SSZ hash tree root of the *Withdrawal using the given hash walker.
func (t *Withdrawal) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(Withdrawal)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Index'
		hh.PutUint64(uint64(t.Index))
	}
	{ // Field #1 'ValidatorIndex'
		hh.PutUint64(uint64(t.ValidatorIndex))
	}
	{ // Field #2 'Address'
		hh.PutBytes(t.Address[:20])
	}
	{ // Field #3 'Amount'
		hh.PutUint64(uint64(t.Amount))
	}
	hh.Merkleize(idx)
	return nil
}
