// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 04fa7e5d456af8782705abb482a50276a413a1db9894d2016a90177121f6e7c2
// Version: v1.0.1 (https://github.com/pk910/dynamic-ssz)
package bellatrix

import (
	"github.com/attestantio/go-eth2-client/spec/bellatrix"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *ExecutionPayloadTransactions) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	dstlen := len(dst)
	// Offset #0 'Transactions'
	offset0 := len(dst)
	dst = sszutils.MarshalOffset(dst, 0)
	{ // Dynamic Field #0 'Transactions'
		sszutils.UpdateOffset(dst[offset0:offset0+4], len(dst)-dstlen)
		t := t.Transactions
		max := 1048576
		hasMax := true
		vlen := len(t)
		if hasMax && vlen > int(max) {
			return dst, sszutils.ErrListTooBig
		}
		dstlen := len(dst)
		dst = sszutils.AppendZeroPadding(dst, vlen*4)
		for i := 0; i < vlen; i++ {
			sszutils.UpdateOffset(dst[dstlen+(i*4):dstlen+((i+1)*4)], len(dst)-dstlen)
			t := t[i]
			max := 1073741824
			hasMax := true
			vlen := len(t)
			if hasMax && vlen > int(max) {
				return dst, sszutils.ErrListTooBig
			}
			dst = append(dst, []byte(t[:])...)
		}
	}
	return dst, nil
}

func (t *ExecutionPayloadTransactions) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *ExecutionPayloadTransactions) SizeSSZ() (size int) {
	// Field #0 'Transactions' offset (4 bytes)
	size += 4
	{ // Dynamic field #0 'Transactions'
		vlen := len(t.Transactions)
		size += vlen * 4 // Offsets
		for i := 0; i < vlen; i++ {
			t := t.Transactions[i]
			size += len(t)
		}
	}
	return size
}

func (t *ExecutionPayloadTransactions) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 4 {
		return sszutils.ErrUnexpectedEOF
	}
	// Field #0 'Transactions' (offset)
	offset0 := int(sszutils.UnmarshallUint32(buf[0:4]))
	if offset0 < 4 || offset0 > buflen {
		return sszutils.ErrOffset
	}
	{ // Field #0 'Transactions' (dynamic)
		buf := buf[offset0:]
		val1 := t.Transactions
		startOffset := int(0)
		if len(buf) != 0 {
			if len(buf) < 4 {
				return sszutils.ErrUnexpectedEOF
			}
			startOffset = int(sszutils.UnmarshallUint32(buf[0:4]))
		}
		itemCount := startOffset / 4
		if startOffset%4 != 0 || len(buf) < startOffset {
			return sszutils.ErrUnexpectedEOF
		}
		if len(val1) < itemCount {
			val1 = make([]bellatrix.Transaction, itemCount)
		} else if len(val1) > itemCount {
			val1 = val1[:itemCount]
		}
		for i := 0; i < itemCount; i++ {
			var endOffset int
			if i < itemCount-1 {
				endOffset = int(sszutils.UnmarshallUint32(buf[(i+1)*4 : (i+2)*4]))
			} else {
				endOffset = len(buf)
			}
			if endOffset < startOffset || endOffset > len(buf) {
				return sszutils.ErrOffset
			}
			buf := buf[startOffset:endOffset]
			startOffset = endOffset
			val2 := val1[i]
			limit := len(buf)
			if len(val2) < limit {
				val2 = make(bellatrix.Transaction, limit)
			} else if len(val2) > limit {
				val2 = val2[:limit]
			}
			copy(val2[:], buf)
			val1[i] = val2
		}
		t.Transactions = val1
	}
	return nil
}

func (t *ExecutionPayloadTransactions) HashTreeRootWith(hh sszutils.HashWalker) error {
	idx := hh.Index()
	{ // Field #0 'Transactions'
		t := t.Transactions
		idx := hh.Index()
		vlen := uint64(len(t))
		for i := 0; i < int(vlen); i++ {
			t := t[i]
			idx := hh.Index()
			vlen := uint64(len(t))
			hh.PutBytes(t[:])
			limit := sszutils.CalculateLimit(1073741824, vlen, 1)
			hh.MerkleizeWithMixin(idx, vlen, limit)
		}
		limit := sszutils.CalculateLimit(1048576, vlen, 32)
		hh.MerkleizeWithMixin(idx, vlen, limit)
	}
	hh.Merkleize(idx)
	return nil
}

func (t *ExecutionPayloadTransactions) HashTreeRoot() ([32]byte, error) {
	pool := &hasher.FastHasherPool
	hh := pool.Get()
	defer func() {
		pool.Put(hh)
	}()
	if err := t.HashTreeRootWith(hh); err != nil {
		return [32]byte{}, err
	}
	r, _ := hh.HashRoot()
	return r, nil
}
