// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 8016115cba90f9779a84e16d62fb70423cd9e6f2153f4d03a4764c40332f3758
// Version: v1.4.0-pre.1 (https://github.com/pk910/dynamic-ssz)
package electra

import (
	"encoding/binary"
	"math"

	"github.com/attestantio/go-eth2-client/spec/electra"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

var _ = sszutils.Annotate[ConsolidationRequests](`ssz-static:"false"`)

// MarshalSSZ marshals the *ConsolidationRequests to SSZ-encoded bytes.
func (t *ConsolidationRequests) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *ConsolidationRequests to SSZ-encoded bytes, appending to the provided buffer.
func (t *ConsolidationRequests) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(ConsolidationRequests)
	}
	dstlen := len(dst)
	// Offset Field #0 'ConsolidationRequests'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #0 'ConsolidationRequests'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen:], uint32(off))
		}
		t := t.ConsolidationRequests
		vlen := len(t)
		if vlen > 1 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 1), "ConsolidationRequests")
		}
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(electra.ConsolidationRequest)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "ConsolidationRequests[%d]", idx1)
			}
		}
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *ConsolidationRequests from SSZ-encoded bytes.
func (t *ConsolidationRequests) UnmarshalSSZ(buf []byte) (err error) {
	buflen := uint64(len(buf))
	if buflen < 4 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 4)
	}
	// Field #0 'ConsolidationRequests' (offset)
	offset0 := binary.LittleEndian.Uint32(buf[0:4])
	if offset0 != 4 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 4), "ConsolidationRequests:o")
	}
	{ // Field #0 'ConsolidationRequests' (dynamic)
		buf := buf[offset0:]
		val1 := t.ConsolidationRequests
		itemCount := len(buf) / 116
		if len(buf)%116 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 116), "ConsolidationRequests")
		}
		if itemCount > 1 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 1), "ConsolidationRequests")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		for idx1 := range itemCount {
			if val1[idx1] == nil {
				val1[idx1] = new(electra.ConsolidationRequest)
			}
			buf := buf[116*idx1 : 116*(idx1+1)]
			if err = val1[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "ConsolidationRequests[%d]", idx1)
			}
		}
		t.ConsolidationRequests = val1
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *ConsolidationRequests.
func (t *ConsolidationRequests) SizeSSZ() (size int) {
	if t == nil {
		t = new(ConsolidationRequests)
	}
	// Field #0 'ConsolidationRequests' offset (4 bytes)
	size += 4
	{ // Dynamic field #0 'ConsolidationRequests'
		size += len(t.ConsolidationRequests) * 116
	}
	return size
}

// HashTreeRoot computes the SSZ hash tree root of the *ConsolidationRequests.
func (t *ConsolidationRequests) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *ConsolidationRequests using the given hash walker.
func (t *ConsolidationRequests) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(ConsolidationRequests)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'ConsolidationRequests'
		t := t.ConsolidationRequests
		vlen := uint64(len(t))
		if vlen > 1 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 1), "ConsolidationRequests")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range len(t) {
			t := t[idx1]
			if t == nil {
				t = new(electra.ConsolidationRequest)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "ConsolidationRequests[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(1, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}
