// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 1a887e78b8d64124415d5e678b59869bc23f419e67a7c17083dfb501c15f063e
// Version: v1.1.1 (https://github.com/pk910/dynamic-ssz)
package electra

import (
	"github.com/attestantio/go-eth2-client/spec/electra"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *ConsolidationRequests) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *ConsolidationRequests) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(ConsolidationRequests)
	}
	dstlen := len(dst)
	// Offset #0 'ConsolidationRequests'
	offset0 := len(dst)
	dst = sszutils.MarshalOffset(dst, 0)
	{ // Dynamic Field #0 'ConsolidationRequests'
		sszutils.UpdateOffset(dst[offset0:offset0+4], len(dst)-dstlen)
		t := t.ConsolidationRequests
		vlen := len(t)
		if vlen > 1 {
			return dst, sszutils.ErrListTooBig
		}
		for i := 0; i < vlen; i++ {
			t := t[i]
			if t == nil {
				t = new(electra.ConsolidationRequest)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return dst, err
			}
		}
	}
	return dst, nil
}

func (t *ConsolidationRequests) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 4 {
		return sszutils.ErrUnexpectedEOF
	}
	// Field #0 'ConsolidationRequests' (offset)
	offset0 := int(sszutils.UnmarshallUint32(buf[0:4]))
	if offset0 != 4 {
		return sszutils.ErrOffset
	}
	{ // Field #0 'ConsolidationRequests' (dynamic)
		buf := buf[offset0:]
		val1 := t.ConsolidationRequests
		itemCount := len(buf) / 116
		if len(buf)%116 != 0 {
			return sszutils.ErrUnexpectedEOF
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		for i := 0; i < itemCount; i++ {
			if val1[i] == nil {
				val1[i] = new(electra.ConsolidationRequest)
			}
			buf := buf[116*i : 116*(i+1)]
			if err = val1[i].UnmarshalSSZ(buf); err != nil {
				return err
			}
		}
		t.ConsolidationRequests = val1
	}
	return nil
}

func (t *ConsolidationRequests) SizeSSZ() (size int) {
	if t == nil {
		t = new(ConsolidationRequests)
	}
	// Field #0 'ConsolidationRequests' offset (4 bytes)
	size += 4
	{ // Dynamic field #0 'ConsolidationRequests'
		size += len(t.ConsolidationRequests) * 116
	}
	return size
}

func (t *ConsolidationRequests) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}
func (t *ConsolidationRequests) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(ConsolidationRequests)
	}
	idx := hh.Index()
	{ // Field #0 'ConsolidationRequests'
		t := t.ConsolidationRequests
		vlen := uint64(len(t))
		if vlen > 1 {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		for i := 0; i < int(vlen); i++ {
			t := t[i]
			if t == nil {
				t = new(electra.ConsolidationRequest)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return err
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(1, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}

