// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 8bd2ea469a6307170297d2893e186f37417cfcf42075f1e168d9838a96edbc98
// Version: v0.0.4 (https://github.com/pk910/dynamic-ssz)
package api

import (
	"github.com/attestantio/go-eth2-client/api/v1/bellatrix"
	"github.com/attestantio/go-eth2-client/api/v1/capella"
	"github.com/attestantio/go-eth2-client/api/v1/deneb"
	"github.com/attestantio/go-eth2-client/api/v1/electra"
	"github.com/attestantio/go-eth2-client/spec"
	"github.com/attestantio/go-eth2-client/spec/altair"
	bellatrix1 "github.com/attestantio/go-eth2-client/spec/bellatrix"
	capella1 "github.com/attestantio/go-eth2-client/spec/capella"
	deneb1 "github.com/attestantio/go-eth2-client/spec/deneb"
	electra1 "github.com/attestantio/go-eth2-client/spec/electra"
	"github.com/attestantio/go-eth2-client/spec/phase0"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
	go_bitfield "github.com/prysmaticlabs/go-bitfield"
)

var _ = sszutils.ErrListTooBig

func (t *VersionedBlindedBeaconBlock) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	fn1 := func(t *phase0.ETH1Data) (err error) { // *phase0.ETH1Data
		dst, err = t.MarshalSSZTo(dst)
		return err
	}
	fn2 := func(t *phase0.ProposerSlashing) (err error) { // *phase0.ProposerSlashing
		dst, err = t.MarshalSSZTo(dst)
		return err
	}
	fn3 := func(t []*phase0.ProposerSlashing) (err error) { // []*phase0.ProposerSlashing
		vlen := len(t)
		for i := 0; i < vlen; i++ {
			if err = fn2(t[i]); err != nil {
				return err
			}
		}
		return err
	}
	fn4 := func(t *phase0.AttesterSlashing) (err error) { // *phase0.AttesterSlashing
		dst, err = t.MarshalSSZTo(dst)
		return err
	}
	fn5 := func(t []*phase0.AttesterSlashing) (err error) { // []*phase0.AttesterSlashing
		vlen := len(t)
		dstlen := len(dst)
		dst = sszutils.AppendZeroPadding(dst, vlen*4)
		for i := 0; i < vlen; i++ {
			sszutils.UpdateOffset(dst[dstlen+(i*4):dstlen+((i+1)*4)], len(dst)-dstlen)
			if err = fn4(t[i]); err != nil {
				return err
			}
		}
		return err
	}
	fn6 := func(t *phase0.Attestation) (err error) { // *phase0.Attestation
		dst, err = t.MarshalSSZTo(dst)
		return err
	}
	fn7 := func(t []*phase0.Attestation) (err error) { // []*phase0.Attestation
		vlen := len(t)
		dstlen := len(dst)
		dst = sszutils.AppendZeroPadding(dst, vlen*4)
		for i := 0; i < vlen; i++ {
			sszutils.UpdateOffset(dst[dstlen+(i*4):dstlen+((i+1)*4)], len(dst)-dstlen)
			if err = fn6(t[i]); err != nil {
				return err
			}
		}
		return err
	}
	fn8 := func(t [][]byte) (err error) { // [][]uint8:33:32
		limit := 33
		vlen := len(t)
		if vlen > int(limit) {
			return sszutils.ErrListTooBig
		}
		for i := 0; i < vlen; i++ {
			if len(t[i]) > 32 {
				dst = append(dst, t[i][:32]...)
			} else {
				dst = append(dst, t[i][:]...)
				if len(t[i]) < 32 {
					dst = sszutils.AppendZeroPadding(dst, 32-len(t[i]))
				}
			}
		}
		if vlen < int(limit) {
			dst = sszutils.AppendZeroPadding(dst, (int(limit)-vlen)*32)
		}
		return err
	}
	fn9 := func(t *phase0.DepositData) (err error) { // *phase0.DepositData
		dst, err = t.MarshalSSZTo(dst)
		return err
	}
	fn10 := func(t *phase0.Deposit) (err error) { // *phase0.Deposit
		// Field #0 'Proof'
		if err = fn8(t.Proof); err != nil {
			return err
		}
		// Field #1 'Data'
		if err = fn9(t.Data); err != nil {
			return err
		}
		return err
	}
	fn11 := func(t []*phase0.Deposit) (err error) { // []*phase0.Deposit
		vlen := len(t)
		for i := 0; i < vlen; i++ {
			if err = fn10(t[i]); err != nil {
				return err
			}
		}
		return err
	}
	fn12 := func(t *phase0.SignedVoluntaryExit) (err error) { // *phase0.SignedVoluntaryExit
		dst, err = t.MarshalSSZTo(dst)
		return err
	}
	fn13 := func(t []*phase0.SignedVoluntaryExit) (err error) { // []*phase0.SignedVoluntaryExit
		vlen := len(t)
		for i := 0; i < vlen; i++ {
			if err = fn12(t[i]); err != nil {
				return err
			}
		}
		return err
	}
	fn14 := func(t go_bitfield.Bitvector512) (err error) { // bitfield.Bitvector512:64
		limit := 64
		vlen := len(t)
		if vlen > int(limit) {
			return sszutils.ErrListTooBig
		}
		vlimit := int(limit)
		if vlimit > vlen {
			vlimit = vlen
		}
		dst = append(dst, t[:vlimit]...)
		if vlen < int(limit) {
			dst = sszutils.AppendZeroPadding(dst, int(limit)-vlen)
		}
		return err
	}
	fn15 := func(t *altair.SyncAggregate) (err error) { // *altair.SyncAggregate
		// Field #0 'SyncCommitteeBits'
		if err = fn14(t.SyncCommitteeBits); err != nil {
			return err
		}
		// Field #1 'SyncCommitteeSignature'
		dst = append(dst, t.SyncCommitteeSignature[:]...)
		return err
	}
	fn16 := func(t *bellatrix1.ExecutionPayloadHeader) (err error) { // *bellatrix.ExecutionPayloadHeader
		dst, err = t.MarshalSSZTo(dst)
		return err
	}
	fn17 := func(t *bellatrix.BlindedBeaconBlockBody) (err error) { // *bellatrix.BlindedBeaconBlockBody
		dstlen := len(dst)
		// Field #0 'RANDAOReveal'
		dst = append(dst, t.RANDAOReveal[:]...)
		// Field #1 'ETH1Data'
		if err = fn1(t.ETH1Data); err != nil {
			return err
		}
		// Field #2 'Graffiti'
		dst = append(dst, t.Graffiti[:]...)
		// Offset #3 'ProposerSlashings'
		offset3 := len(dst)
		dst = sszutils.MarshalOffset(dst, 0)
		// Offset #4 'AttesterSlashings'
		offset4 := len(dst)
		dst = sszutils.MarshalOffset(dst, 0)
		// Offset #5 'Attestations'
		offset5 := len(dst)
		dst = sszutils.MarshalOffset(dst, 0)
		// Offset #6 'Deposits'
		offset6 := len(dst)
		dst = sszutils.MarshalOffset(dst, 0)
		// Offset #7 'VoluntaryExits'
		offset7 := len(dst)
		dst = sszutils.MarshalOffset(dst, 0)
		// Field #8 'SyncAggregate'
		if err = fn15(t.SyncAggregate); err != nil {
			return err
		}
		// Offset #9 'ExecutionPayloadHeader'
		offset9 := len(dst)
		dst = sszutils.MarshalOffset(dst, 0)
		// Dynamic Field #3 'ProposerSlashings'
		sszutils.UpdateOffset(dst[offset3:offset3+4], len(dst)-dstlen)
		if err = fn3(t.ProposerSlashings); err != nil {
			return err
		}
		// Dynamic Field #4 'AttesterSlashings'
		sszutils.UpdateOffset(dst[offset4:offset4+4], len(dst)-dstlen)
		if err = fn5(t.AttesterSlashings); err != nil {
			return err
		}
		// Dynamic Field #5 'Attestations'
		sszutils.UpdateOffset(dst[offset5:offset5+4], len(dst)-dstlen)
		if err = fn7(t.Attestations); err != nil {
			return err
		}
		// Dynamic Field #6 'Deposits'
		sszutils.UpdateOffset(dst[offset6:offset6+4], len(dst)-dstlen)
		if err = fn11(t.Deposits); err != nil {
			return err
		}
		// Dynamic Field #7 'VoluntaryExits'
		sszutils.UpdateOffset(dst[offset7:offset7+4], len(dst)-dstlen)
		if err = fn13(t.VoluntaryExits); err != nil {
			return err
		}
		// Dynamic Field #9 'ExecutionPayloadHeader'
		sszutils.UpdateOffset(dst[offset9:offset9+4], len(dst)-dstlen)
		if err = fn16(t.ExecutionPayloadHeader); err != nil {
			return err
		}
		return err
	}
	fn18 := func(t *bellatrix.BlindedBeaconBlock) (err error) { // *bellatrix.BlindedBeaconBlock
		dstlen := len(dst)
		// Field #0 'Slot'
		dst = sszutils.MarshalUint64(dst, uint64(t.Slot))
		// Field #1 'ProposerIndex'
		dst = sszutils.MarshalUint64(dst, uint64(t.ProposerIndex))
		// Field #2 'ParentRoot'
		dst = append(dst, t.ParentRoot[:]...)
		// Field #3 'StateRoot'
		dst = append(dst, t.StateRoot[:]...)
		// Offset #4 'Body'
		offset4 := len(dst)
		dst = sszutils.MarshalOffset(dst, 0)
		// Dynamic Field #4 'Body'
		sszutils.UpdateOffset(dst[offset4:offset4+4], len(dst)-dstlen)
		if err = fn17(t.Body); err != nil {
			return err
		}
		return err
	}
	fn19 := func(t *capella1.ExecutionPayloadHeader) (err error) { // *capella.ExecutionPayloadHeader
		dst, err = t.MarshalSSZTo(dst)
		return err
	}
	fn20 := func(t *capella1.SignedBLSToExecutionChange) (err error) { // *capella.SignedBLSToExecutionChange
		dst, err = t.MarshalSSZTo(dst)
		return err
	}
	fn21 := func(t []*capella1.SignedBLSToExecutionChange) (err error) { // []*capella.SignedBLSToExecutionChange
		vlen := len(t)
		for i := 0; i < vlen; i++ {
			if err = fn20(t[i]); err != nil {
				return err
			}
		}
		return err
	}
	fn22 := func(t *capella.BlindedBeaconBlockBody) (err error) { // *capella.BlindedBeaconBlockBody
		dstlen := len(dst)
		// Field #0 'RANDAOReveal'
		dst = append(dst, t.RANDAOReveal[:]...)
		// Field #1 'ETH1Data'
		if err = fn1(t.ETH1Data); err != nil {
			return err
		}
		// Field #2 'Graffiti'
		dst = append(dst, t.Graffiti[:]...)
		// Offset #3 'ProposerSlashings'
		offset3 := len(dst)
		dst = sszutils.MarshalOffset(dst, 0)
		// Offset #4 'AttesterSlashings'
		offset4 := len(dst)
		dst = sszutils.MarshalOffset(dst, 0)
		// Offset #5 'Attestations'
		offset5 := len(dst)
		dst = sszutils.MarshalOffset(dst, 0)
		// Offset #6 'Deposits'
		offset6 := len(dst)
		dst = sszutils.MarshalOffset(dst, 0)
		// Offset #7 'VoluntaryExits'
		offset7 := len(dst)
		dst = sszutils.MarshalOffset(dst, 0)
		// Field #8 'SyncAggregate'
		if err = fn15(t.SyncAggregate); err != nil {
			return err
		}
		// Offset #9 'ExecutionPayloadHeader'
		offset9 := len(dst)
		dst = sszutils.MarshalOffset(dst, 0)
		// Offset #10 'BLSToExecutionChanges'
		offset10 := len(dst)
		dst = sszutils.MarshalOffset(dst, 0)
		// Dynamic Field #3 'ProposerSlashings'
		sszutils.UpdateOffset(dst[offset3:offset3+4], len(dst)-dstlen)
		if err = fn3(t.ProposerSlashings); err != nil {
			return err
		}
		// Dynamic Field #4 'AttesterSlashings'
		sszutils.UpdateOffset(dst[offset4:offset4+4], len(dst)-dstlen)
		if err = fn5(t.AttesterSlashings); err != nil {
			return err
		}
		// Dynamic Field #5 'Attestations'
		sszutils.UpdateOffset(dst[offset5:offset5+4], len(dst)-dstlen)
		if err = fn7(t.Attestations); err != nil {
			return err
		}
		// Dynamic Field #6 'Deposits'
		sszutils.UpdateOffset(dst[offset6:offset6+4], len(dst)-dstlen)
		if err = fn11(t.Deposits); err != nil {
			return err
		}
		// Dynamic Field #7 'VoluntaryExits'
		sszutils.UpdateOffset(dst[offset7:offset7+4], len(dst)-dstlen)
		if err = fn13(t.VoluntaryExits); err != nil {
			return err
		}
		// Dynamic Field #9 'ExecutionPayloadHeader'
		sszutils.UpdateOffset(dst[offset9:offset9+4], len(dst)-dstlen)
		if err = fn19(t.ExecutionPayloadHeader); err != nil {
			return err
		}
		// Dynamic Field #10 'BLSToExecutionChanges'
		sszutils.UpdateOffset(dst[offset10:offset10+4], len(dst)-dstlen)
		if err = fn21(t.BLSToExecutionChanges); err != nil {
			return err
		}
		return err
	}
	fn23 := func(t *capella.BlindedBeaconBlock) (err error) { // *capella.BlindedBeaconBlock
		dstlen := len(dst)
		// Field #0 'Slot'
		dst = sszutils.MarshalUint64(dst, uint64(t.Slot))
		// Field #1 'ProposerIndex'
		dst = sszutils.MarshalUint64(dst, uint64(t.ProposerIndex))
		// Field #2 'ParentRoot'
		dst = append(dst, t.ParentRoot[:]...)
		// Field #3 'StateRoot'
		dst = append(dst, t.StateRoot[:]...)
		// Offset #4 'Body'
		offset4 := len(dst)
		dst = sszutils.MarshalOffset(dst, 0)
		// Dynamic Field #4 'Body'
		sszutils.UpdateOffset(dst[offset4:offset4+4], len(dst)-dstlen)
		if err = fn22(t.Body); err != nil {
			return err
		}
		return err
	}
	fn24 := func(t *deneb1.ExecutionPayloadHeader) (err error) { // *deneb.ExecutionPayloadHeader
		dst, err = t.MarshalSSZTo(dst)
		return err
	}
	fn25 := func(t []deneb1.KZGCommitment) (err error) { // []deneb.KZGCommitment:48
		vlen := len(t)
		for i := 0; i < vlen; i++ {
			dst = append(dst, t[i][:]...)
		}
		return err
	}
	fn26 := func(t *deneb.BlindedBeaconBlockBody) (err error) { // *deneb.BlindedBeaconBlockBody
		dstlen := len(dst)
		// Field #0 'RANDAOReveal'
		dst = append(dst, t.RANDAOReveal[:]...)
		// Field #1 'ETH1Data'
		if err = fn1(t.ETH1Data); err != nil {
			return err
		}
		// Field #2 'Graffiti'
		dst = append(dst, t.Graffiti[:]...)
		// Offset #3 'ProposerSlashings'
		offset3 := len(dst)
		dst = sszutils.MarshalOffset(dst, 0)
		// Offset #4 'AttesterSlashings'
		offset4 := len(dst)
		dst = sszutils.MarshalOffset(dst, 0)
		// Offset #5 'Attestations'
		offset5 := len(dst)
		dst = sszutils.MarshalOffset(dst, 0)
		// Offset #6 'Deposits'
		offset6 := len(dst)
		dst = sszutils.MarshalOffset(dst, 0)
		// Offset #7 'VoluntaryExits'
		offset7 := len(dst)
		dst = sszutils.MarshalOffset(dst, 0)
		// Field #8 'SyncAggregate'
		if err = fn15(t.SyncAggregate); err != nil {
			return err
		}
		// Offset #9 'ExecutionPayloadHeader'
		offset9 := len(dst)
		dst = sszutils.MarshalOffset(dst, 0)
		// Offset #10 'BLSToExecutionChanges'
		offset10 := len(dst)
		dst = sszutils.MarshalOffset(dst, 0)
		// Offset #11 'BlobKZGCommitments'
		offset11 := len(dst)
		dst = sszutils.MarshalOffset(dst, 0)
		// Dynamic Field #3 'ProposerSlashings'
		sszutils.UpdateOffset(dst[offset3:offset3+4], len(dst)-dstlen)
		if err = fn3(t.ProposerSlashings); err != nil {
			return err
		}
		// Dynamic Field #4 'AttesterSlashings'
		sszutils.UpdateOffset(dst[offset4:offset4+4], len(dst)-dstlen)
		if err = fn5(t.AttesterSlashings); err != nil {
			return err
		}
		// Dynamic Field #5 'Attestations'
		sszutils.UpdateOffset(dst[offset5:offset5+4], len(dst)-dstlen)
		if err = fn7(t.Attestations); err != nil {
			return err
		}
		// Dynamic Field #6 'Deposits'
		sszutils.UpdateOffset(dst[offset6:offset6+4], len(dst)-dstlen)
		if err = fn11(t.Deposits); err != nil {
			return err
		}
		// Dynamic Field #7 'VoluntaryExits'
		sszutils.UpdateOffset(dst[offset7:offset7+4], len(dst)-dstlen)
		if err = fn13(t.VoluntaryExits); err != nil {
			return err
		}
		// Dynamic Field #9 'ExecutionPayloadHeader'
		sszutils.UpdateOffset(dst[offset9:offset9+4], len(dst)-dstlen)
		if err = fn24(t.ExecutionPayloadHeader); err != nil {
			return err
		}
		// Dynamic Field #10 'BLSToExecutionChanges'
		sszutils.UpdateOffset(dst[offset10:offset10+4], len(dst)-dstlen)
		if err = fn21(t.BLSToExecutionChanges); err != nil {
			return err
		}
		// Dynamic Field #11 'BlobKZGCommitments'
		sszutils.UpdateOffset(dst[offset11:offset11+4], len(dst)-dstlen)
		if err = fn25(t.BlobKZGCommitments); err != nil {
			return err
		}
		return err
	}
	fn27 := func(t *deneb.BlindedBeaconBlock) (err error) { // *deneb.BlindedBeaconBlock
		dstlen := len(dst)
		// Field #0 'Slot'
		dst = sszutils.MarshalUint64(dst, uint64(t.Slot))
		// Field #1 'ProposerIndex'
		dst = sszutils.MarshalUint64(dst, uint64(t.ProposerIndex))
		// Field #2 'ParentRoot'
		dst = append(dst, t.ParentRoot[:]...)
		// Field #3 'StateRoot'
		dst = append(dst, t.StateRoot[:]...)
		// Offset #4 'Body'
		offset4 := len(dst)
		dst = sszutils.MarshalOffset(dst, 0)
		// Dynamic Field #4 'Body'
		sszutils.UpdateOffset(dst[offset4:offset4+4], len(dst)-dstlen)
		if err = fn26(t.Body); err != nil {
			return err
		}
		return err
	}
	fn28 := func(t *electra1.AttesterSlashing) (err error) { // *electra.AttesterSlashing
		dst, err = t.MarshalSSZTo(dst)
		return err
	}
	fn29 := func(t []*electra1.AttesterSlashing) (err error) { // []*electra.AttesterSlashing
		vlen := len(t)
		dstlen := len(dst)
		dst = sszutils.AppendZeroPadding(dst, vlen*4)
		for i := 0; i < vlen; i++ {
			sszutils.UpdateOffset(dst[dstlen+(i*4):dstlen+((i+1)*4)], len(dst)-dstlen)
			if err = fn28(t[i]); err != nil {
				return err
			}
		}
		return err
	}
	fn30 := func(t go_bitfield.Bitlist) (err error) { // bitfield.Bitlist
		dst = append(dst, t[:]...)
		return err
	}
	fn31 := func(t *phase0.AttestationData) (err error) { // *phase0.AttestationData
		dst, err = t.MarshalSSZTo(dst)
		return err
	}
	fn32 := func(t go_bitfield.Bitvector64) (err error) { // bitfield.Bitvector64:8
		limit := 8
		vlen := len(t)
		if vlen > int(limit) {
			return sszutils.ErrListTooBig
		}
		vlimit := int(limit)
		if vlimit > vlen {
			vlimit = vlen
		}
		dst = append(dst, t[:vlimit]...)
		if vlen < int(limit) {
			dst = sszutils.AppendZeroPadding(dst, int(limit)-vlen)
		}
		return err
	}
	fn33 := func(t *electra1.Attestation) (err error) { // *electra.Attestation
		dstlen := len(dst)
		// Offset #0 'AggregationBits'
		offset0 := len(dst)
		dst = sszutils.MarshalOffset(dst, 0)
		// Field #1 'Data'
		if err = fn31(t.Data); err != nil {
			return err
		}
		// Field #2 'Signature'
		dst = append(dst, t.Signature[:]...)
		// Field #3 'CommitteeBits'
		if err = fn32(t.CommitteeBits); err != nil {
			return err
		}
		// Dynamic Field #0 'AggregationBits'
		sszutils.UpdateOffset(dst[offset0:offset0+4], len(dst)-dstlen)
		if err = fn30(t.AggregationBits); err != nil {
			return err
		}
		return err
	}
	fn34 := func(t []*electra1.Attestation) (err error) { // []*electra.Attestation
		vlen := len(t)
		dstlen := len(dst)
		dst = sszutils.AppendZeroPadding(dst, vlen*4)
		for i := 0; i < vlen; i++ {
			sszutils.UpdateOffset(dst[dstlen+(i*4):dstlen+((i+1)*4)], len(dst)-dstlen)
			if err = fn33(t[i]); err != nil {
				return err
			}
		}
		return err
	}
	fn35 := func(t *electra1.ExecutionRequests) (err error) { // *electra.ExecutionRequests
		dst, err = t.MarshalSSZTo(dst)
		return err
	}
	fn36 := func(t *electra.BlindedBeaconBlockBody) (err error) { // *electra.BlindedBeaconBlockBody
		dstlen := len(dst)
		// Field #0 'RANDAOReveal'
		dst = append(dst, t.RANDAOReveal[:]...)
		// Field #1 'ETH1Data'
		if err = fn1(t.ETH1Data); err != nil {
			return err
		}
		// Field #2 'Graffiti'
		dst = append(dst, t.Graffiti[:]...)
		// Offset #3 'ProposerSlashings'
		offset3 := len(dst)
		dst = sszutils.MarshalOffset(dst, 0)
		// Offset #4 'AttesterSlashings'
		offset4 := len(dst)
		dst = sszutils.MarshalOffset(dst, 0)
		// Offset #5 'Attestations'
		offset5 := len(dst)
		dst = sszutils.MarshalOffset(dst, 0)
		// Offset #6 'Deposits'
		offset6 := len(dst)
		dst = sszutils.MarshalOffset(dst, 0)
		// Offset #7 'VoluntaryExits'
		offset7 := len(dst)
		dst = sszutils.MarshalOffset(dst, 0)
		// Field #8 'SyncAggregate'
		if err = fn15(t.SyncAggregate); err != nil {
			return err
		}
		// Offset #9 'ExecutionPayloadHeader'
		offset9 := len(dst)
		dst = sszutils.MarshalOffset(dst, 0)
		// Offset #10 'BLSToExecutionChanges'
		offset10 := len(dst)
		dst = sszutils.MarshalOffset(dst, 0)
		// Offset #11 'BlobKZGCommitments'
		offset11 := len(dst)
		dst = sszutils.MarshalOffset(dst, 0)
		// Offset #12 'ExecutionRequests'
		offset12 := len(dst)
		dst = sszutils.MarshalOffset(dst, 0)
		// Dynamic Field #3 'ProposerSlashings'
		sszutils.UpdateOffset(dst[offset3:offset3+4], len(dst)-dstlen)
		if err = fn3(t.ProposerSlashings); err != nil {
			return err
		}
		// Dynamic Field #4 'AttesterSlashings'
		sszutils.UpdateOffset(dst[offset4:offset4+4], len(dst)-dstlen)
		if err = fn29(t.AttesterSlashings); err != nil {
			return err
		}
		// Dynamic Field #5 'Attestations'
		sszutils.UpdateOffset(dst[offset5:offset5+4], len(dst)-dstlen)
		if err = fn34(t.Attestations); err != nil {
			return err
		}
		// Dynamic Field #6 'Deposits'
		sszutils.UpdateOffset(dst[offset6:offset6+4], len(dst)-dstlen)
		if err = fn11(t.Deposits); err != nil {
			return err
		}
		// Dynamic Field #7 'VoluntaryExits'
		sszutils.UpdateOffset(dst[offset7:offset7+4], len(dst)-dstlen)
		if err = fn13(t.VoluntaryExits); err != nil {
			return err
		}
		// Dynamic Field #9 'ExecutionPayloadHeader'
		sszutils.UpdateOffset(dst[offset9:offset9+4], len(dst)-dstlen)
		if err = fn24(t.ExecutionPayloadHeader); err != nil {
			return err
		}
		// Dynamic Field #10 'BLSToExecutionChanges'
		sszutils.UpdateOffset(dst[offset10:offset10+4], len(dst)-dstlen)
		if err = fn21(t.BLSToExecutionChanges); err != nil {
			return err
		}
		// Dynamic Field #11 'BlobKZGCommitments'
		sszutils.UpdateOffset(dst[offset11:offset11+4], len(dst)-dstlen)
		if err = fn25(t.BlobKZGCommitments); err != nil {
			return err
		}
		// Dynamic Field #12 'ExecutionRequests'
		sszutils.UpdateOffset(dst[offset12:offset12+4], len(dst)-dstlen)
		if err = fn35(t.ExecutionRequests); err != nil {
			return err
		}
		return err
	}
	fn37 := func(t *electra.BlindedBeaconBlock) (err error) { // *electra.BlindedBeaconBlock
		dstlen := len(dst)
		// Field #0 'Slot'
		dst = sszutils.MarshalUint64(dst, uint64(t.Slot))
		// Field #1 'ProposerIndex'
		dst = sszutils.MarshalUint64(dst, uint64(t.ProposerIndex))
		// Field #2 'ParentRoot'
		dst = append(dst, t.ParentRoot[:]...)
		// Field #3 'StateRoot'
		dst = append(dst, t.StateRoot[:]...)
		// Offset #4 'Body'
		offset4 := len(dst)
		dst = sszutils.MarshalOffset(dst, 0)
		// Dynamic Field #4 'Body'
		sszutils.UpdateOffset(dst[offset4:offset4+4], len(dst)-dstlen)
		if err = fn36(t.Body); err != nil {
			return err
		}
		return err
	}
	fn38 := func(t *VersionedBlindedBeaconBlock) (err error) { // *api.VersionedBlindedBeaconBlock
		dstlen := len(dst)
		// Field #0 'Version'
		dst = sszutils.MarshalUint64(dst, uint64(t.Version))
		// Offset #1 'Bellatrix'
		offset1 := len(dst)
		dst = sszutils.MarshalOffset(dst, 0)
		// Offset #2 'Capella'
		offset2 := len(dst)
		dst = sszutils.MarshalOffset(dst, 0)
		// Offset #3 'Deneb'
		offset3 := len(dst)
		dst = sszutils.MarshalOffset(dst, 0)
		// Offset #4 'Electra'
		offset4 := len(dst)
		dst = sszutils.MarshalOffset(dst, 0)
		// Offset #5 'Fulu'
		offset5 := len(dst)
		dst = sszutils.MarshalOffset(dst, 0)
		// Dynamic Field #1 'Bellatrix'
		sszutils.UpdateOffset(dst[offset1:offset1+4], len(dst)-dstlen)
		if err = fn18(t.Bellatrix); err != nil {
			return err
		}
		// Dynamic Field #2 'Capella'
		sszutils.UpdateOffset(dst[offset2:offset2+4], len(dst)-dstlen)
		if err = fn23(t.Capella); err != nil {
			return err
		}
		// Dynamic Field #3 'Deneb'
		sszutils.UpdateOffset(dst[offset3:offset3+4], len(dst)-dstlen)
		if err = fn27(t.Deneb); err != nil {
			return err
		}
		// Dynamic Field #4 'Electra'
		sszutils.UpdateOffset(dst[offset4:offset4+4], len(dst)-dstlen)
		if err = fn37(t.Electra); err != nil {
			return err
		}
		// Dynamic Field #5 'Fulu'
		sszutils.UpdateOffset(dst[offset5:offset5+4], len(dst)-dstlen)
		if err = fn37(t.Fulu); err != nil {
			return err
		}
		return err
	}
	err = fn38(t)
	return dst, err
}
func (t *VersionedBlindedBeaconBlock) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

func (t *VersionedBlindedBeaconBlock) SizeSSZ() (size int) {
	sfn1 := func(t []*phase0.ProposerSlashing) (size int) { // []*phase0.ProposerSlashing
		size += len(t) * 416
		return size
	}
	sfn2 := func(t *phase0.AttesterSlashing) (size int) { // *phase0.AttesterSlashing
		size = t.SizeSSZ()
		return size
	}
	sfn3 := func(t []*phase0.AttesterSlashing) (size int) { // []*phase0.AttesterSlashing
		vlen := len(t)
		for i := 0; i < vlen; i++ {
			size += 4 + sfn2(t[i])
		}
		return size
	}
	sfn4 := func(t *phase0.Attestation) (size int) { // *phase0.Attestation
		size = t.SizeSSZ()
		return size
	}
	sfn5 := func(t []*phase0.Attestation) (size int) { // []*phase0.Attestation
		vlen := len(t)
		for i := 0; i < vlen; i++ {
			size += 4 + sfn4(t[i])
		}
		return size
	}
	sfn6 := func(t [][]byte) (size int) { // [][]byte:33:32
		limit := 33
		size += int(limit) * 32
		return size
	}
	sfn7 := func(t *phase0.Deposit) (size int) { // *phase0.Deposit
		size = 184
		size += sfn6(t.Proof)
		return size
	}
	sfn8 := func(t []*phase0.Deposit) (size int) { // []*phase0.Deposit
		if len(t) > 0 {
			size += len(t) * sfn7(t[0])
		}
		return size
	}
	sfn9 := func(t []*phase0.SignedVoluntaryExit) (size int) { // []*phase0.SignedVoluntaryExit
		size += len(t) * 112
		return size
	}
	sfn10 := func(t go_bitfield.Bitvector512) (size int) { // go_bitfield.Bitvector512:64
		limit := 64
		size += int(limit) * 1
		return size
	}
	sfn11 := func(t *altair.SyncAggregate) (size int) { // *altair.SyncAggregate
		size = 96
		size += sfn10(t.SyncCommitteeBits)
		return size
	}
	sfn12 := func(t *bellatrix1.ExecutionPayloadHeader) (size int) { // *bellatrix1.ExecutionPayloadHeader
		size = t.SizeSSZ()
		return size
	}
	sfn13 := func(t *bellatrix.BlindedBeaconBlockBody) (size int) { // *bellatrix.BlindedBeaconBlockBody
		size = 200
		size += 4 + sfn1(t.ProposerSlashings)
		size += 4 + sfn3(t.AttesterSlashings)
		size += 4 + sfn5(t.Attestations)
		size += 4 + sfn8(t.Deposits)
		size += 4 + sfn9(t.VoluntaryExits)
		size += sfn11(t.SyncAggregate)
		size += 4 + sfn12(t.ExecutionPayloadHeader)
		return size
	}
	sfn14 := func(t *bellatrix.BlindedBeaconBlock) (size int) { // *bellatrix.BlindedBeaconBlock
		size = 80
		size += 4 + sfn13(t.Body)
		return size
	}
	sfn15 := func(t *capella1.ExecutionPayloadHeader) (size int) { // *capella1.ExecutionPayloadHeader
		size = t.SizeSSZ()
		return size
	}
	sfn16 := func(t []*capella1.SignedBLSToExecutionChange) (size int) { // []*capella1.SignedBLSToExecutionChange
		size += len(t) * 172
		return size
	}
	sfn17 := func(t *capella.BlindedBeaconBlockBody) (size int) { // *capella.BlindedBeaconBlockBody
		size = 200
		size += 4 + sfn1(t.ProposerSlashings)
		size += 4 + sfn3(t.AttesterSlashings)
		size += 4 + sfn5(t.Attestations)
		size += 4 + sfn8(t.Deposits)
		size += 4 + sfn9(t.VoluntaryExits)
		size += sfn11(t.SyncAggregate)
		size += 4 + sfn15(t.ExecutionPayloadHeader)
		size += 4 + sfn16(t.BLSToExecutionChanges)
		return size
	}
	sfn18 := func(t *capella.BlindedBeaconBlock) (size int) { // *capella.BlindedBeaconBlock
		size = 80
		size += 4 + sfn17(t.Body)
		return size
	}
	sfn19 := func(t *deneb1.ExecutionPayloadHeader) (size int) { // *deneb1.ExecutionPayloadHeader
		size = t.SizeSSZ()
		return size
	}
	sfn20 := func(t []deneb1.KZGCommitment) (size int) { // []deneb1.KZGCommitment:48
		size += len(t) * 48
		return size
	}
	sfn21 := func(t *deneb.BlindedBeaconBlockBody) (size int) { // *deneb.BlindedBeaconBlockBody
		size = 200
		size += 4 + sfn1(t.ProposerSlashings)
		size += 4 + sfn3(t.AttesterSlashings)
		size += 4 + sfn5(t.Attestations)
		size += 4 + sfn8(t.Deposits)
		size += 4 + sfn9(t.VoluntaryExits)
		size += sfn11(t.SyncAggregate)
		size += 4 + sfn19(t.ExecutionPayloadHeader)
		size += 4 + sfn16(t.BLSToExecutionChanges)
		size += 4 + sfn20(t.BlobKZGCommitments)
		return size
	}
	sfn22 := func(t *deneb.BlindedBeaconBlock) (size int) { // *deneb.BlindedBeaconBlock
		size = 80
		size += 4 + sfn21(t.Body)
		return size
	}
	sfn23 := func(t *electra1.AttesterSlashing) (size int) { // *electra1.AttesterSlashing
		size = t.SizeSSZ()
		return size
	}
	sfn24 := func(t []*electra1.AttesterSlashing) (size int) { // []*electra1.AttesterSlashing
		vlen := len(t)
		for i := 0; i < vlen; i++ {
			size += 4 + sfn23(t[i])
		}
		return size
	}
	sfn25 := func(t go_bitfield.Bitlist) (size int) { // go_bitfield.Bitlist
		size += len(t)
		return size
	}
	sfn26 := func(t go_bitfield.Bitvector64) (size int) { // go_bitfield.Bitvector64:8
		limit := 8
		size += int(limit) * 1
		return size
	}
	sfn27 := func(t *electra1.Attestation) (size int) { // *electra1.Attestation
		size = 224
		size += 4 + sfn25(t.AggregationBits)
		size += sfn26(t.CommitteeBits)
		return size
	}
	sfn28 := func(t []*electra1.Attestation) (size int) { // []*electra1.Attestation
		vlen := len(t)
		for i := 0; i < vlen; i++ {
			size += 4 + sfn27(t[i])
		}
		return size
	}
	sfn29 := func(t *electra1.ExecutionRequests) (size int) { // *electra1.ExecutionRequests
		size = t.SizeSSZ()
		return size
	}
	sfn30 := func(t *electra.BlindedBeaconBlockBody) (size int) { // *electra.BlindedBeaconBlockBody
		size = 200
		size += 4 + sfn1(t.ProposerSlashings)
		size += 4 + sfn24(t.AttesterSlashings)
		size += 4 + sfn28(t.Attestations)
		size += 4 + sfn8(t.Deposits)
		size += 4 + sfn9(t.VoluntaryExits)
		size += sfn11(t.SyncAggregate)
		size += 4 + sfn19(t.ExecutionPayloadHeader)
		size += 4 + sfn16(t.BLSToExecutionChanges)
		size += 4 + sfn20(t.BlobKZGCommitments)
		size += 4 + sfn29(t.ExecutionRequests)
		return size
	}
	sfn31 := func(t *electra.BlindedBeaconBlock) (size int) { // *electra.BlindedBeaconBlock
		size = 80
		size += 4 + sfn30(t.Body)
		return size
	}
	sfn32 := func(t *VersionedBlindedBeaconBlock) (size int) { // *VersionedBlindedBeaconBlock
		size = 8
		size += 4 + sfn14(t.Bellatrix)
		size += 4 + sfn18(t.Capella)
		size += 4 + sfn22(t.Deneb)
		size += 4 + sfn31(t.Electra)
		size += 4 + sfn31(t.Fulu)
		return size
	}
	return sfn32(t)
}

func (t *VersionedBlindedBeaconBlock) UnmarshalSSZ(buf []byte) (err error) {
	fn1 := func(t *phase0.ETH1Data, buf []byte) (*phase0.ETH1Data, error) { // *phase0.ETH1Data
		var err error
		if t == nil {
			t = new(phase0.ETH1Data)
		}
		err = t.UnmarshalSSZ(buf)
		return t, err
	}
	fn2 := func(t *phase0.ProposerSlashing, buf []byte) (*phase0.ProposerSlashing, error) { // *phase0.ProposerSlashing
		var err error
		if t == nil {
			t = new(phase0.ProposerSlashing)
		}
		err = t.UnmarshalSSZ(buf)
		return t, err
	}
	fn3 := func(t []*phase0.ProposerSlashing, buf []byte) ([]*phase0.ProposerSlashing, error) { // []*phase0.ProposerSlashing
		var err error
		buflen := len(buf)
		itemsize := 416
		itemCount := buflen / itemsize
		if buflen%itemsize != 0 {
			return t, sszutils.ErrUnexpectedEOF
		}
		if len(t) < itemCount {
			t = make([]*phase0.ProposerSlashing, itemCount)
		} else {
			t = t[:itemCount]
		}
		for i := 0; i < itemCount; i++ {
			if t[i], err = fn2(t[i], buf[i*itemsize:(i+1)*itemsize]); err != nil {
				return t, err
			}
		}
		return t, err
	}
	fn4 := func(t *phase0.AttesterSlashing, buf []byte) (*phase0.AttesterSlashing, error) { // *phase0.AttesterSlashing
		var err error
		if t == nil {
			t = new(phase0.AttesterSlashing)
		}
		err = t.UnmarshalSSZ(buf)
		return t, err
	}
	fn5 := func(t []*phase0.AttesterSlashing, buf []byte) ([]*phase0.AttesterSlashing, error) { // []*phase0.AttesterSlashing
		var err error
		buflen := len(buf)
		if buflen == 0 {
			return t, nil
		}
		if buflen < 4 {
			return t, sszutils.ErrUnexpectedEOF
		}
		offset := int(sszutils.ReadOffset(buf[0:4]))
		itemCount := offset / 4
		if buflen < itemCount*4 {
			return t, sszutils.ErrUnexpectedEOF
		}
		if len(t) < itemCount {
			t = make([]*phase0.AttesterSlashing, itemCount)
		} else {
			t = t[:itemCount]
		}
		var endOffset int
		for i := 0; i < itemCount; i++ {
			if i < itemCount-1 {
				endOffset = int(sszutils.ReadOffset(buf[(i+1)*4 : (i+2)*4]))
			} else {
				endOffset = buflen
			}
			if endOffset < offset || endOffset > buflen {
				return t, sszutils.ErrOffset
			}
			if t[i], err = fn4(t[i], buf[offset:endOffset]); err != nil {
				return t, err
			}
			offset = endOffset
		}
		return t, err
	}
	fn6 := func(t *phase0.Attestation, buf []byte) (*phase0.Attestation, error) { // *phase0.Attestation
		var err error
		if t == nil {
			t = new(phase0.Attestation)
		}
		err = t.UnmarshalSSZ(buf)
		return t, err
	}
	fn7 := func(t []*phase0.Attestation, buf []byte) ([]*phase0.Attestation, error) { // []*phase0.Attestation
		var err error
		buflen := len(buf)
		if buflen == 0 {
			return t, nil
		}
		if buflen < 4 {
			return t, sszutils.ErrUnexpectedEOF
		}
		offset := int(sszutils.ReadOffset(buf[0:4]))
		itemCount := offset / 4
		if buflen < itemCount*4 {
			return t, sszutils.ErrUnexpectedEOF
		}
		if len(t) < itemCount {
			t = make([]*phase0.Attestation, itemCount)
		} else {
			t = t[:itemCount]
		}
		var endOffset int
		for i := 0; i < itemCount; i++ {
			if i < itemCount-1 {
				endOffset = int(sszutils.ReadOffset(buf[(i+1)*4 : (i+2)*4]))
			} else {
				endOffset = buflen
			}
			if endOffset < offset || endOffset > buflen {
				return t, sszutils.ErrOffset
			}
			if t[i], err = fn6(t[i], buf[offset:endOffset]); err != nil {
				return t, err
			}
			offset = endOffset
		}
		return t, err
	}
	fn8 := func(t [][]byte, buf []byte) ([][]byte, error) { // [][]byte:33:32
		var err error
		itemsize := 32
		limit := 33
		if len(t) < int(limit) {
			t = make([][]byte, int(limit))
		} else {
			t = t[:int(limit)]
		}
		if len(buf) > int(limit)*itemsize {
			return t, sszutils.ErrListTooBig
		}
		for i := 0; i < int(limit); i++ {
			if len(t[i]) < 32 {
				t[i] = make([]byte, 32)
			} else {
				t[i] = t[i][:32]
			}
			copy(t[i][:], buf[i*itemsize:(i+1)*itemsize])
		}
		return t, err
	}
	fn9 := func(t *phase0.DepositData, buf []byte) (*phase0.DepositData, error) { // *phase0.DepositData
		var err error
		if t == nil {
			t = new(phase0.DepositData)
		}
		err = t.UnmarshalSSZ(buf)
		return t, err
	}
	fn10 := func(t *phase0.Deposit, buf []byte) (*phase0.Deposit, error) { // *phase0.Deposit
		var err error
		if t == nil {
			t = new(phase0.Deposit)
		}
		buflen := len(buf)
		if buflen < 1240 {
			return t, sszutils.ErrUnexpectedEOF
		}
		// Field #0 'Proof'
		if t.Proof, err = fn8(t.Proof, buf[0:1056]); err != nil {
			return t, err
		}
		// Field #1 'Data'
		if t.Data, err = fn9(t.Data, buf[1056:1240]); err != nil {
			return t, err
		}
		return t, err
	}
	fn11 := func(t []*phase0.Deposit, buf []byte) ([]*phase0.Deposit, error) { // []*phase0.Deposit
		var err error
		buflen := len(buf)
		itemsize := 1240
		itemCount := buflen / itemsize
		if buflen%itemsize != 0 {
			return t, sszutils.ErrUnexpectedEOF
		}
		if len(t) < itemCount {
			t = make([]*phase0.Deposit, itemCount)
		} else {
			t = t[:itemCount]
		}
		for i := 0; i < itemCount; i++ {
			if t[i], err = fn10(t[i], buf[i*itemsize:(i+1)*itemsize]); err != nil {
				return t, err
			}
		}
		return t, err
	}
	fn12 := func(t *phase0.SignedVoluntaryExit, buf []byte) (*phase0.SignedVoluntaryExit, error) { // *phase0.SignedVoluntaryExit
		var err error
		if t == nil {
			t = new(phase0.SignedVoluntaryExit)
		}
		err = t.UnmarshalSSZ(buf)
		return t, err
	}
	fn13 := func(t []*phase0.SignedVoluntaryExit, buf []byte) ([]*phase0.SignedVoluntaryExit, error) { // []*phase0.SignedVoluntaryExit
		var err error
		buflen := len(buf)
		itemsize := 112
		itemCount := buflen / itemsize
		if buflen%itemsize != 0 {
			return t, sszutils.ErrUnexpectedEOF
		}
		if len(t) < itemCount {
			t = make([]*phase0.SignedVoluntaryExit, itemCount)
		} else {
			t = t[:itemCount]
		}
		for i := 0; i < itemCount; i++ {
			if t[i], err = fn12(t[i], buf[i*itemsize:(i+1)*itemsize]); err != nil {
				return t, err
			}
		}
		return t, err
	}
	fn14 := func(t go_bitfield.Bitvector512, buf []byte) (go_bitfield.Bitvector512, error) { // go_bitfield.Bitvector512:64
		var err error
		itemsize := 1
		limit := 64
		if len(t) < int(limit) {
			t = make(go_bitfield.Bitvector512, int(limit))
		} else {
			t = t[:int(limit)]
		}
		if len(buf) > int(limit)*itemsize {
			return t, sszutils.ErrListTooBig
		}
		copy(t[:], buf)
		return t, err
	}
	fn15 := func(t *altair.SyncAggregate, buf []byte) (*altair.SyncAggregate, error) { // *altair.SyncAggregate
		var err error
		if t == nil {
			t = new(altair.SyncAggregate)
		}
		buflen := len(buf)
		if buflen < 160 {
			return t, sszutils.ErrUnexpectedEOF
		}
		// Field #0 'SyncCommitteeBits'
		if t.SyncCommitteeBits, err = fn14(t.SyncCommitteeBits, buf[0:64]); err != nil {
			return t, err
		}
		// Field #1 'SyncCommitteeSignature'
		copy(t.SyncCommitteeSignature[:], buf[64:160])
		return t, err
	}
	fn16 := func(t *bellatrix1.ExecutionPayloadHeader, buf []byte) (*bellatrix1.ExecutionPayloadHeader, error) { // *bellatrix1.ExecutionPayloadHeader
		var err error
		if t == nil {
			t = new(bellatrix1.ExecutionPayloadHeader)
		}
		err = t.UnmarshalSSZ(buf)
		return t, err
	}
	fn17 := func(t *bellatrix.BlindedBeaconBlockBody, buf []byte) (*bellatrix.BlindedBeaconBlockBody, error) { // *bellatrix.BlindedBeaconBlockBody
		var err error
		if t == nil {
			t = new(bellatrix.BlindedBeaconBlockBody)
		}
		bufpos := 384
		buflen := len(buf)
		if buflen < 384 {
			return t, sszutils.ErrUnexpectedEOF
		}
		// Read offset #3 'ProposerSlashings'
		offset3 := int(sszutils.ReadOffset(buf[200:204]))
		// Read offset #4 'AttesterSlashings'
		offset4 := int(sszutils.ReadOffset(buf[204:208]))
		// Read offset #5 'Attestations'
		offset5 := int(sszutils.ReadOffset(buf[208:212]))
		// Read offset #6 'Deposits'
		offset6 := int(sszutils.ReadOffset(buf[212:216]))
		// Read offset #7 'VoluntaryExits'
		offset7 := int(sszutils.ReadOffset(buf[216:220]))
		// Read offset #9 'ExecutionPayloadHeader'
		offset9 := int(sszutils.ReadOffset(buf[380:384]))
		// Field #0 'RANDAOReveal'
		copy(t.RANDAOReveal[:], buf[0:96])
		// Field #1 'ETH1Data'
		if t.ETH1Data, err = fn1(t.ETH1Data, buf[96:168]); err != nil {
			return t, err
		}
		// Field #2 'Graffiti'
		copy(t.Graffiti[:], buf[168:200])
		// Field #8 'SyncAggregate'
		if t.SyncAggregate, err = fn15(t.SyncAggregate, buf[220:380]); err != nil {
			return t, err
		}
		// Dynamic Field #3 'ProposerSlashings'
		if offset3 < bufpos || offset4 > buflen || offset4 < offset3 {
			return t, sszutils.ErrOffset
		}
		{
			fieldSlice := buf[offset3:offset4]
			if t.ProposerSlashings, err = fn3(t.ProposerSlashings, fieldSlice); err != nil {
				return t, err
			}
			bufpos += len(fieldSlice)
		}
		// Dynamic Field #4 'AttesterSlashings'
		if offset4 < bufpos || offset5 > buflen || offset5 < offset4 {
			return t, sszutils.ErrOffset
		}
		{
			fieldSlice := buf[offset4:offset5]
			if t.AttesterSlashings, err = fn5(t.AttesterSlashings, fieldSlice); err != nil {
				return t, err
			}
			bufpos += len(fieldSlice)
		}
		// Dynamic Field #5 'Attestations'
		if offset5 < bufpos || offset6 > buflen || offset6 < offset5 {
			return t, sszutils.ErrOffset
		}
		{
			fieldSlice := buf[offset5:offset6]
			if t.Attestations, err = fn7(t.Attestations, fieldSlice); err != nil {
				return t, err
			}
			bufpos += len(fieldSlice)
		}
		// Dynamic Field #6 'Deposits'
		if offset6 < bufpos || offset7 > buflen || offset7 < offset6 {
			return t, sszutils.ErrOffset
		}
		{
			fieldSlice := buf[offset6:offset7]
			if t.Deposits, err = fn11(t.Deposits, fieldSlice); err != nil {
				return t, err
			}
			bufpos += len(fieldSlice)
		}
		// Dynamic Field #7 'VoluntaryExits'
		if offset7 < bufpos || offset9 > buflen || offset9 < offset7 {
			return t, sszutils.ErrOffset
		}
		{
			fieldSlice := buf[offset7:offset9]
			if t.VoluntaryExits, err = fn13(t.VoluntaryExits, fieldSlice); err != nil {
				return t, err
			}
			bufpos += len(fieldSlice)
		}
		// Dynamic Field #9 'ExecutionPayloadHeader'
		if offset9 < bufpos {
			return t, sszutils.ErrOffset
		}
		{
			fieldSlice := buf[offset9:]
			if t.ExecutionPayloadHeader, err = fn16(t.ExecutionPayloadHeader, fieldSlice); err != nil {
				return t, err
			}
			bufpos += len(fieldSlice)
		}
		return t, err
	}
	fn18 := func(t *bellatrix.BlindedBeaconBlock, buf []byte) (*bellatrix.BlindedBeaconBlock, error) { // *bellatrix.BlindedBeaconBlock
		var err error
		if t == nil {
			t = new(bellatrix.BlindedBeaconBlock)
		}
		bufpos := 84
		buflen := len(buf)
		if buflen < 84 {
			return t, sszutils.ErrUnexpectedEOF
		}
		// Read offset #4 'Body'
		offset4 := int(sszutils.ReadOffset(buf[80:84]))
		// Field #0 'Slot'
		t.Slot = (phase0.Slot)(sszutils.UnmarshallUint64(buf[0:8]))
		// Field #1 'ProposerIndex'
		t.ProposerIndex = (phase0.ValidatorIndex)(sszutils.UnmarshallUint64(buf[8:16]))
		// Field #2 'ParentRoot'
		copy(t.ParentRoot[:], buf[16:48])
		// Field #3 'StateRoot'
		copy(t.StateRoot[:], buf[48:80])
		// Dynamic Field #4 'Body'
		if offset4 < bufpos {
			return t, sszutils.ErrOffset
		}
		{
			fieldSlice := buf[offset4:]
			if t.Body, err = fn17(t.Body, fieldSlice); err != nil {
				return t, err
			}
			bufpos += len(fieldSlice)
		}
		return t, err
	}
	fn19 := func(t *capella1.ExecutionPayloadHeader, buf []byte) (*capella1.ExecutionPayloadHeader, error) { // *capella1.ExecutionPayloadHeader
		var err error
		if t == nil {
			t = new(capella1.ExecutionPayloadHeader)
		}
		err = t.UnmarshalSSZ(buf)
		return t, err
	}
	fn20 := func(t *capella1.SignedBLSToExecutionChange, buf []byte) (*capella1.SignedBLSToExecutionChange, error) { // *capella1.SignedBLSToExecutionChange
		var err error
		if t == nil {
			t = new(capella1.SignedBLSToExecutionChange)
		}
		err = t.UnmarshalSSZ(buf)
		return t, err
	}
	fn21 := func(t []*capella1.SignedBLSToExecutionChange, buf []byte) ([]*capella1.SignedBLSToExecutionChange, error) { // []*capella1.SignedBLSToExecutionChange
		var err error
		buflen := len(buf)
		itemsize := 172
		itemCount := buflen / itemsize
		if buflen%itemsize != 0 {
			return t, sszutils.ErrUnexpectedEOF
		}
		if len(t) < itemCount {
			t = make([]*capella1.SignedBLSToExecutionChange, itemCount)
		} else {
			t = t[:itemCount]
		}
		for i := 0; i < itemCount; i++ {
			if t[i], err = fn20(t[i], buf[i*itemsize:(i+1)*itemsize]); err != nil {
				return t, err
			}
		}
		return t, err
	}
	fn22 := func(t *capella.BlindedBeaconBlockBody, buf []byte) (*capella.BlindedBeaconBlockBody, error) { // *capella.BlindedBeaconBlockBody
		var err error
		if t == nil {
			t = new(capella.BlindedBeaconBlockBody)
		}
		bufpos := 388
		buflen := len(buf)
		if buflen < 388 {
			return t, sszutils.ErrUnexpectedEOF
		}
		// Read offset #3 'ProposerSlashings'
		offset3 := int(sszutils.ReadOffset(buf[200:204]))
		// Read offset #4 'AttesterSlashings'
		offset4 := int(sszutils.ReadOffset(buf[204:208]))
		// Read offset #5 'Attestations'
		offset5 := int(sszutils.ReadOffset(buf[208:212]))
		// Read offset #6 'Deposits'
		offset6 := int(sszutils.ReadOffset(buf[212:216]))
		// Read offset #7 'VoluntaryExits'
		offset7 := int(sszutils.ReadOffset(buf[216:220]))
		// Read offset #9 'ExecutionPayloadHeader'
		offset9 := int(sszutils.ReadOffset(buf[380:384]))
		// Read offset #10 'BLSToExecutionChanges'
		offset10 := int(sszutils.ReadOffset(buf[384:388]))
		// Field #0 'RANDAOReveal'
		copy(t.RANDAOReveal[:], buf[0:96])
		// Field #1 'ETH1Data'
		if t.ETH1Data, err = fn1(t.ETH1Data, buf[96:168]); err != nil {
			return t, err
		}
		// Field #2 'Graffiti'
		copy(t.Graffiti[:], buf[168:200])
		// Field #8 'SyncAggregate'
		if t.SyncAggregate, err = fn15(t.SyncAggregate, buf[220:380]); err != nil {
			return t, err
		}
		// Dynamic Field #3 'ProposerSlashings'
		if offset3 < bufpos || offset4 > buflen || offset4 < offset3 {
			return t, sszutils.ErrOffset
		}
		{
			fieldSlice := buf[offset3:offset4]
			if t.ProposerSlashings, err = fn3(t.ProposerSlashings, fieldSlice); err != nil {
				return t, err
			}
			bufpos += len(fieldSlice)
		}
		// Dynamic Field #4 'AttesterSlashings'
		if offset4 < bufpos || offset5 > buflen || offset5 < offset4 {
			return t, sszutils.ErrOffset
		}
		{
			fieldSlice := buf[offset4:offset5]
			if t.AttesterSlashings, err = fn5(t.AttesterSlashings, fieldSlice); err != nil {
				return t, err
			}
			bufpos += len(fieldSlice)
		}
		// Dynamic Field #5 'Attestations'
		if offset5 < bufpos || offset6 > buflen || offset6 < offset5 {
			return t, sszutils.ErrOffset
		}
		{
			fieldSlice := buf[offset5:offset6]
			if t.Attestations, err = fn7(t.Attestations, fieldSlice); err != nil {
				return t, err
			}
			bufpos += len(fieldSlice)
		}
		// Dynamic Field #6 'Deposits'
		if offset6 < bufpos || offset7 > buflen || offset7 < offset6 {
			return t, sszutils.ErrOffset
		}
		{
			fieldSlice := buf[offset6:offset7]
			if t.Deposits, err = fn11(t.Deposits, fieldSlice); err != nil {
				return t, err
			}
			bufpos += len(fieldSlice)
		}
		// Dynamic Field #7 'VoluntaryExits'
		if offset7 < bufpos || offset9 > buflen || offset9 < offset7 {
			return t, sszutils.ErrOffset
		}
		{
			fieldSlice := buf[offset7:offset9]
			if t.VoluntaryExits, err = fn13(t.VoluntaryExits, fieldSlice); err != nil {
				return t, err
			}
			bufpos += len(fieldSlice)
		}
		// Dynamic Field #9 'ExecutionPayloadHeader'
		if offset9 < bufpos || offset10 > buflen || offset10 < offset9 {
			return t, sszutils.ErrOffset
		}
		{
			fieldSlice := buf[offset9:offset10]
			if t.ExecutionPayloadHeader, err = fn19(t.ExecutionPayloadHeader, fieldSlice); err != nil {
				return t, err
			}
			bufpos += len(fieldSlice)
		}
		// Dynamic Field #10 'BLSToExecutionChanges'
		if offset10 < bufpos {
			return t, sszutils.ErrOffset
		}
		{
			fieldSlice := buf[offset10:]
			if t.BLSToExecutionChanges, err = fn21(t.BLSToExecutionChanges, fieldSlice); err != nil {
				return t, err
			}
			bufpos += len(fieldSlice)
		}
		return t, err
	}
	fn23 := func(t *capella.BlindedBeaconBlock, buf []byte) (*capella.BlindedBeaconBlock, error) { // *capella.BlindedBeaconBlock
		var err error
		if t == nil {
			t = new(capella.BlindedBeaconBlock)
		}
		bufpos := 84
		buflen := len(buf)
		if buflen < 84 {
			return t, sszutils.ErrUnexpectedEOF
		}
		// Read offset #4 'Body'
		offset4 := int(sszutils.ReadOffset(buf[80:84]))
		// Field #0 'Slot'
		t.Slot = (phase0.Slot)(sszutils.UnmarshallUint64(buf[0:8]))
		// Field #1 'ProposerIndex'
		t.ProposerIndex = (phase0.ValidatorIndex)(sszutils.UnmarshallUint64(buf[8:16]))
		// Field #2 'ParentRoot'
		copy(t.ParentRoot[:], buf[16:48])
		// Field #3 'StateRoot'
		copy(t.StateRoot[:], buf[48:80])
		// Dynamic Field #4 'Body'
		if offset4 < bufpos {
			return t, sszutils.ErrOffset
		}
		{
			fieldSlice := buf[offset4:]
			if t.Body, err = fn22(t.Body, fieldSlice); err != nil {
				return t, err
			}
			bufpos += len(fieldSlice)
		}
		return t, err
	}
	fn24 := func(t *deneb1.ExecutionPayloadHeader, buf []byte) (*deneb1.ExecutionPayloadHeader, error) { // *deneb1.ExecutionPayloadHeader
		var err error
		if t == nil {
			t = new(deneb1.ExecutionPayloadHeader)
		}
		err = t.UnmarshalSSZ(buf)
		return t, err
	}
	fn25 := func(t []deneb1.KZGCommitment, buf []byte) ([]deneb1.KZGCommitment, error) { // []deneb1.KZGCommitment:48
		var err error
		buflen := len(buf)
		itemsize := 48
		itemCount := buflen / itemsize
		if buflen%itemsize != 0 {
			return t, sszutils.ErrUnexpectedEOF
		}
		if len(t) < itemCount {
			t = make([]deneb1.KZGCommitment, itemCount)
		} else {
			t = t[:itemCount]
		}
		for i := 0; i < itemCount; i++ {
			copy(t[i][:], buf[i*itemsize:(i+1)*itemsize])
		}
		return t, err
	}
	fn26 := func(t *deneb.BlindedBeaconBlockBody, buf []byte) (*deneb.BlindedBeaconBlockBody, error) { // *deneb.BlindedBeaconBlockBody
		var err error
		if t == nil {
			t = new(deneb.BlindedBeaconBlockBody)
		}
		bufpos := 392
		buflen := len(buf)
		if buflen < 392 {
			return t, sszutils.ErrUnexpectedEOF
		}
		// Read offset #3 'ProposerSlashings'
		offset3 := int(sszutils.ReadOffset(buf[200:204]))
		// Read offset #4 'AttesterSlashings'
		offset4 := int(sszutils.ReadOffset(buf[204:208]))
		// Read offset #5 'Attestations'
		offset5 := int(sszutils.ReadOffset(buf[208:212]))
		// Read offset #6 'Deposits'
		offset6 := int(sszutils.ReadOffset(buf[212:216]))
		// Read offset #7 'VoluntaryExits'
		offset7 := int(sszutils.ReadOffset(buf[216:220]))
		// Read offset #9 'ExecutionPayloadHeader'
		offset9 := int(sszutils.ReadOffset(buf[380:384]))
		// Read offset #10 'BLSToExecutionChanges'
		offset10 := int(sszutils.ReadOffset(buf[384:388]))
		// Read offset #11 'BlobKZGCommitments'
		offset11 := int(sszutils.ReadOffset(buf[388:392]))
		// Field #0 'RANDAOReveal'
		copy(t.RANDAOReveal[:], buf[0:96])
		// Field #1 'ETH1Data'
		if t.ETH1Data, err = fn1(t.ETH1Data, buf[96:168]); err != nil {
			return t, err
		}
		// Field #2 'Graffiti'
		copy(t.Graffiti[:], buf[168:200])
		// Field #8 'SyncAggregate'
		if t.SyncAggregate, err = fn15(t.SyncAggregate, buf[220:380]); err != nil {
			return t, err
		}
		// Dynamic Field #3 'ProposerSlashings'
		if offset3 < bufpos || offset4 > buflen || offset4 < offset3 {
			return t, sszutils.ErrOffset
		}
		{
			fieldSlice := buf[offset3:offset4]
			if t.ProposerSlashings, err = fn3(t.ProposerSlashings, fieldSlice); err != nil {
				return t, err
			}
			bufpos += len(fieldSlice)
		}
		// Dynamic Field #4 'AttesterSlashings'
		if offset4 < bufpos || offset5 > buflen || offset5 < offset4 {
			return t, sszutils.ErrOffset
		}
		{
			fieldSlice := buf[offset4:offset5]
			if t.AttesterSlashings, err = fn5(t.AttesterSlashings, fieldSlice); err != nil {
				return t, err
			}
			bufpos += len(fieldSlice)
		}
		// Dynamic Field #5 'Attestations'
		if offset5 < bufpos || offset6 > buflen || offset6 < offset5 {
			return t, sszutils.ErrOffset
		}
		{
			fieldSlice := buf[offset5:offset6]
			if t.Attestations, err = fn7(t.Attestations, fieldSlice); err != nil {
				return t, err
			}
			bufpos += len(fieldSlice)
		}
		// Dynamic Field #6 'Deposits'
		if offset6 < bufpos || offset7 > buflen || offset7 < offset6 {
			return t, sszutils.ErrOffset
		}
		{
			fieldSlice := buf[offset6:offset7]
			if t.Deposits, err = fn11(t.Deposits, fieldSlice); err != nil {
				return t, err
			}
			bufpos += len(fieldSlice)
		}
		// Dynamic Field #7 'VoluntaryExits'
		if offset7 < bufpos || offset9 > buflen || offset9 < offset7 {
			return t, sszutils.ErrOffset
		}
		{
			fieldSlice := buf[offset7:offset9]
			if t.VoluntaryExits, err = fn13(t.VoluntaryExits, fieldSlice); err != nil {
				return t, err
			}
			bufpos += len(fieldSlice)
		}
		// Dynamic Field #9 'ExecutionPayloadHeader'
		if offset9 < bufpos || offset10 > buflen || offset10 < offset9 {
			return t, sszutils.ErrOffset
		}
		{
			fieldSlice := buf[offset9:offset10]
			if t.ExecutionPayloadHeader, err = fn24(t.ExecutionPayloadHeader, fieldSlice); err != nil {
				return t, err
			}
			bufpos += len(fieldSlice)
		}
		// Dynamic Field #10 'BLSToExecutionChanges'
		if offset10 < bufpos || offset11 > buflen || offset11 < offset10 {
			return t, sszutils.ErrOffset
		}
		{
			fieldSlice := buf[offset10:offset11]
			if t.BLSToExecutionChanges, err = fn21(t.BLSToExecutionChanges, fieldSlice); err != nil {
				return t, err
			}
			bufpos += len(fieldSlice)
		}
		// Dynamic Field #11 'BlobKZGCommitments'
		if offset11 < bufpos {
			return t, sszutils.ErrOffset
		}
		{
			fieldSlice := buf[offset11:]
			if t.BlobKZGCommitments, err = fn25(t.BlobKZGCommitments, fieldSlice); err != nil {
				return t, err
			}
			bufpos += len(fieldSlice)
		}
		return t, err
	}
	fn27 := func(t *deneb.BlindedBeaconBlock, buf []byte) (*deneb.BlindedBeaconBlock, error) { // *deneb.BlindedBeaconBlock
		var err error
		if t == nil {
			t = new(deneb.BlindedBeaconBlock)
		}
		bufpos := 84
		buflen := len(buf)
		if buflen < 84 {
			return t, sszutils.ErrUnexpectedEOF
		}
		// Read offset #4 'Body'
		offset4 := int(sszutils.ReadOffset(buf[80:84]))
		// Field #0 'Slot'
		t.Slot = (phase0.Slot)(sszutils.UnmarshallUint64(buf[0:8]))
		// Field #1 'ProposerIndex'
		t.ProposerIndex = (phase0.ValidatorIndex)(sszutils.UnmarshallUint64(buf[8:16]))
		// Field #2 'ParentRoot'
		copy(t.ParentRoot[:], buf[16:48])
		// Field #3 'StateRoot'
		copy(t.StateRoot[:], buf[48:80])
		// Dynamic Field #4 'Body'
		if offset4 < bufpos {
			return t, sszutils.ErrOffset
		}
		{
			fieldSlice := buf[offset4:]
			if t.Body, err = fn26(t.Body, fieldSlice); err != nil {
				return t, err
			}
			bufpos += len(fieldSlice)
		}
		return t, err
	}
	fn28 := func(t *electra1.AttesterSlashing, buf []byte) (*electra1.AttesterSlashing, error) { // *electra1.AttesterSlashing
		var err error
		if t == nil {
			t = new(electra1.AttesterSlashing)
		}
		err = t.UnmarshalSSZ(buf)
		return t, err
	}
	fn29 := func(t []*electra1.AttesterSlashing, buf []byte) ([]*electra1.AttesterSlashing, error) { // []*electra1.AttesterSlashing
		var err error
		buflen := len(buf)
		if buflen == 0 {
			return t, nil
		}
		if buflen < 4 {
			return t, sszutils.ErrUnexpectedEOF
		}
		offset := int(sszutils.ReadOffset(buf[0:4]))
		itemCount := offset / 4
		if buflen < itemCount*4 {
			return t, sszutils.ErrUnexpectedEOF
		}
		if len(t) < itemCount {
			t = make([]*electra1.AttesterSlashing, itemCount)
		} else {
			t = t[:itemCount]
		}
		var endOffset int
		for i := 0; i < itemCount; i++ {
			if i < itemCount-1 {
				endOffset = int(sszutils.ReadOffset(buf[(i+1)*4 : (i+2)*4]))
			} else {
				endOffset = buflen
			}
			if endOffset < offset || endOffset > buflen {
				return t, sszutils.ErrOffset
			}
			if t[i], err = fn28(t[i], buf[offset:endOffset]); err != nil {
				return t, err
			}
			offset = endOffset
		}
		return t, err
	}
	fn30 := func(t go_bitfield.Bitlist, buf []byte) (go_bitfield.Bitlist, error) { // go_bitfield.Bitlist
		var err error
		if len(t) < len(buf) {
			t = make(go_bitfield.Bitlist, len(buf))
		} else {
			t = t[:len(buf)]
		}
		if len(buf) > 0 {
			copy(t[:], buf)
		}
		return t, err
	}
	fn31 := func(t *phase0.AttestationData, buf []byte) (*phase0.AttestationData, error) { // *phase0.AttestationData
		var err error
		if t == nil {
			t = new(phase0.AttestationData)
		}
		err = t.UnmarshalSSZ(buf)
		return t, err
	}
	fn32 := func(t go_bitfield.Bitvector64, buf []byte) (go_bitfield.Bitvector64, error) { // go_bitfield.Bitvector64:8
		var err error
		itemsize := 1
		limit := 8
		if len(t) < int(limit) {
			t = make(go_bitfield.Bitvector64, int(limit))
		} else {
			t = t[:int(limit)]
		}
		if len(buf) > int(limit)*itemsize {
			return t, sszutils.ErrListTooBig
		}
		copy(t[:], buf)
		return t, err
	}
	fn33 := func(t *electra1.Attestation, buf []byte) (*electra1.Attestation, error) { // *electra1.Attestation
		var err error
		if t == nil {
			t = new(electra1.Attestation)
		}
		bufpos := 236
		buflen := len(buf)
		if buflen < 236 {
			return t, sszutils.ErrUnexpectedEOF
		}
		// Read offset #0 'AggregationBits'
		offset0 := int(sszutils.ReadOffset(buf[0:4]))
		// Field #1 'Data'
		if t.Data, err = fn31(t.Data, buf[4:132]); err != nil {
			return t, err
		}
		// Field #2 'Signature'
		copy(t.Signature[:], buf[132:228])
		// Field #3 'CommitteeBits'
		if t.CommitteeBits, err = fn32(t.CommitteeBits, buf[228:236]); err != nil {
			return t, err
		}
		// Dynamic Field #0 'AggregationBits'
		if offset0 < bufpos {
			return t, sszutils.ErrOffset
		}
		{
			fieldSlice := buf[offset0:]
			if t.AggregationBits, err = fn30(t.AggregationBits, fieldSlice); err != nil {
				return t, err
			}
			bufpos += len(fieldSlice)
		}
		return t, err
	}
	fn34 := func(t []*electra1.Attestation, buf []byte) ([]*electra1.Attestation, error) { // []*electra1.Attestation
		var err error
		buflen := len(buf)
		if buflen == 0 {
			return t, nil
		}
		if buflen < 4 {
			return t, sszutils.ErrUnexpectedEOF
		}
		offset := int(sszutils.ReadOffset(buf[0:4]))
		itemCount := offset / 4
		if buflen < itemCount*4 {
			return t, sszutils.ErrUnexpectedEOF
		}
		if len(t) < itemCount {
			t = make([]*electra1.Attestation, itemCount)
		} else {
			t = t[:itemCount]
		}
		var endOffset int
		for i := 0; i < itemCount; i++ {
			if i < itemCount-1 {
				endOffset = int(sszutils.ReadOffset(buf[(i+1)*4 : (i+2)*4]))
			} else {
				endOffset = buflen
			}
			if endOffset < offset || endOffset > buflen {
				return t, sszutils.ErrOffset
			}
			if t[i], err = fn33(t[i], buf[offset:endOffset]); err != nil {
				return t, err
			}
			offset = endOffset
		}
		return t, err
	}
	fn35 := func(t *electra1.ExecutionRequests, buf []byte) (*electra1.ExecutionRequests, error) { // *electra1.ExecutionRequests
		var err error
		if t == nil {
			t = new(electra1.ExecutionRequests)
		}
		err = t.UnmarshalSSZ(buf)
		return t, err
	}
	fn36 := func(t *electra.BlindedBeaconBlockBody, buf []byte) (*electra.BlindedBeaconBlockBody, error) { // *electra.BlindedBeaconBlockBody
		var err error
		if t == nil {
			t = new(electra.BlindedBeaconBlockBody)
		}
		bufpos := 396
		buflen := len(buf)
		if buflen < 396 {
			return t, sszutils.ErrUnexpectedEOF
		}
		// Read offset #3 'ProposerSlashings'
		offset3 := int(sszutils.ReadOffset(buf[200:204]))
		// Read offset #4 'AttesterSlashings'
		offset4 := int(sszutils.ReadOffset(buf[204:208]))
		// Read offset #5 'Attestations'
		offset5 := int(sszutils.ReadOffset(buf[208:212]))
		// Read offset #6 'Deposits'
		offset6 := int(sszutils.ReadOffset(buf[212:216]))
		// Read offset #7 'VoluntaryExits'
		offset7 := int(sszutils.ReadOffset(buf[216:220]))
		// Read offset #9 'ExecutionPayloadHeader'
		offset9 := int(sszutils.ReadOffset(buf[380:384]))
		// Read offset #10 'BLSToExecutionChanges'
		offset10 := int(sszutils.ReadOffset(buf[384:388]))
		// Read offset #11 'BlobKZGCommitments'
		offset11 := int(sszutils.ReadOffset(buf[388:392]))
		// Read offset #12 'ExecutionRequests'
		offset12 := int(sszutils.ReadOffset(buf[392:396]))
		// Field #0 'RANDAOReveal'
		copy(t.RANDAOReveal[:], buf[0:96])
		// Field #1 'ETH1Data'
		if t.ETH1Data, err = fn1(t.ETH1Data, buf[96:168]); err != nil {
			return t, err
		}
		// Field #2 'Graffiti'
		copy(t.Graffiti[:], buf[168:200])
		// Field #8 'SyncAggregate'
		if t.SyncAggregate, err = fn15(t.SyncAggregate, buf[220:380]); err != nil {
			return t, err
		}
		// Dynamic Field #3 'ProposerSlashings'
		if offset3 < bufpos || offset4 > buflen || offset4 < offset3 {
			return t, sszutils.ErrOffset
		}
		{
			fieldSlice := buf[offset3:offset4]
			if t.ProposerSlashings, err = fn3(t.ProposerSlashings, fieldSlice); err != nil {
				return t, err
			}
			bufpos += len(fieldSlice)
		}
		// Dynamic Field #4 'AttesterSlashings'
		if offset4 < bufpos || offset5 > buflen || offset5 < offset4 {
			return t, sszutils.ErrOffset
		}
		{
			fieldSlice := buf[offset4:offset5]
			if t.AttesterSlashings, err = fn29(t.AttesterSlashings, fieldSlice); err != nil {
				return t, err
			}
			bufpos += len(fieldSlice)
		}
		// Dynamic Field #5 'Attestations'
		if offset5 < bufpos || offset6 > buflen || offset6 < offset5 {
			return t, sszutils.ErrOffset
		}
		{
			fieldSlice := buf[offset5:offset6]
			if t.Attestations, err = fn34(t.Attestations, fieldSlice); err != nil {
				return t, err
			}
			bufpos += len(fieldSlice)
		}
		// Dynamic Field #6 'Deposits'
		if offset6 < bufpos || offset7 > buflen || offset7 < offset6 {
			return t, sszutils.ErrOffset
		}
		{
			fieldSlice := buf[offset6:offset7]
			if t.Deposits, err = fn11(t.Deposits, fieldSlice); err != nil {
				return t, err
			}
			bufpos += len(fieldSlice)
		}
		// Dynamic Field #7 'VoluntaryExits'
		if offset7 < bufpos || offset9 > buflen || offset9 < offset7 {
			return t, sszutils.ErrOffset
		}
		{
			fieldSlice := buf[offset7:offset9]
			if t.VoluntaryExits, err = fn13(t.VoluntaryExits, fieldSlice); err != nil {
				return t, err
			}
			bufpos += len(fieldSlice)
		}
		// Dynamic Field #9 'ExecutionPayloadHeader'
		if offset9 < bufpos || offset10 > buflen || offset10 < offset9 {
			return t, sszutils.ErrOffset
		}
		{
			fieldSlice := buf[offset9:offset10]
			if t.ExecutionPayloadHeader, err = fn24(t.ExecutionPayloadHeader, fieldSlice); err != nil {
				return t, err
			}
			bufpos += len(fieldSlice)
		}
		// Dynamic Field #10 'BLSToExecutionChanges'
		if offset10 < bufpos || offset11 > buflen || offset11 < offset10 {
			return t, sszutils.ErrOffset
		}
		{
			fieldSlice := buf[offset10:offset11]
			if t.BLSToExecutionChanges, err = fn21(t.BLSToExecutionChanges, fieldSlice); err != nil {
				return t, err
			}
			bufpos += len(fieldSlice)
		}
		// Dynamic Field #11 'BlobKZGCommitments'
		if offset11 < bufpos || offset12 > buflen || offset12 < offset11 {
			return t, sszutils.ErrOffset
		}
		{
			fieldSlice := buf[offset11:offset12]
			if t.BlobKZGCommitments, err = fn25(t.BlobKZGCommitments, fieldSlice); err != nil {
				return t, err
			}
			bufpos += len(fieldSlice)
		}
		// Dynamic Field #12 'ExecutionRequests'
		if offset12 < bufpos {
			return t, sszutils.ErrOffset
		}
		{
			fieldSlice := buf[offset12:]
			if t.ExecutionRequests, err = fn35(t.ExecutionRequests, fieldSlice); err != nil {
				return t, err
			}
			bufpos += len(fieldSlice)
		}
		return t, err
	}
	fn37 := func(t *electra.BlindedBeaconBlock, buf []byte) (*electra.BlindedBeaconBlock, error) { // *electra.BlindedBeaconBlock
		var err error
		if t == nil {
			t = new(electra.BlindedBeaconBlock)
		}
		bufpos := 84
		buflen := len(buf)
		if buflen < 84 {
			return t, sszutils.ErrUnexpectedEOF
		}
		// Read offset #4 'Body'
		offset4 := int(sszutils.ReadOffset(buf[80:84]))
		// Field #0 'Slot'
		t.Slot = (phase0.Slot)(sszutils.UnmarshallUint64(buf[0:8]))
		// Field #1 'ProposerIndex'
		t.ProposerIndex = (phase0.ValidatorIndex)(sszutils.UnmarshallUint64(buf[8:16]))
		// Field #2 'ParentRoot'
		copy(t.ParentRoot[:], buf[16:48])
		// Field #3 'StateRoot'
		copy(t.StateRoot[:], buf[48:80])
		// Dynamic Field #4 'Body'
		if offset4 < bufpos {
			return t, sszutils.ErrOffset
		}
		{
			fieldSlice := buf[offset4:]
			if t.Body, err = fn36(t.Body, fieldSlice); err != nil {
				return t, err
			}
			bufpos += len(fieldSlice)
		}
		return t, err
	}
	fn38 := func(t *VersionedBlindedBeaconBlock, buf []byte) (*VersionedBlindedBeaconBlock, error) { // *VersionedBlindedBeaconBlock
		var err error
		if t == nil {
			t = new(VersionedBlindedBeaconBlock)
		}
		bufpos := 28
		buflen := len(buf)
		if buflen < 28 {
			return t, sszutils.ErrUnexpectedEOF
		}
		// Read offset #1 'Bellatrix'
		offset1 := int(sszutils.ReadOffset(buf[8:12]))
		// Read offset #2 'Capella'
		offset2 := int(sszutils.ReadOffset(buf[12:16]))
		// Read offset #3 'Deneb'
		offset3 := int(sszutils.ReadOffset(buf[16:20]))
		// Read offset #4 'Electra'
		offset4 := int(sszutils.ReadOffset(buf[20:24]))
		// Read offset #5 'Fulu'
		offset5 := int(sszutils.ReadOffset(buf[24:28]))
		// Field #0 'Version'
		t.Version = (spec.DataVersion)(sszutils.UnmarshallUint64(buf[0:8]))
		// Dynamic Field #1 'Bellatrix'
		if offset1 < bufpos || offset2 > buflen || offset2 < offset1 {
			return t, sszutils.ErrOffset
		}
		{
			fieldSlice := buf[offset1:offset2]
			if t.Bellatrix, err = fn18(t.Bellatrix, fieldSlice); err != nil {
				return t, err
			}
			bufpos += len(fieldSlice)
		}
		// Dynamic Field #2 'Capella'
		if offset2 < bufpos || offset3 > buflen || offset3 < offset2 {
			return t, sszutils.ErrOffset
		}
		{
			fieldSlice := buf[offset2:offset3]
			if t.Capella, err = fn23(t.Capella, fieldSlice); err != nil {
				return t, err
			}
			bufpos += len(fieldSlice)
		}
		// Dynamic Field #3 'Deneb'
		if offset3 < bufpos || offset4 > buflen || offset4 < offset3 {
			return t, sszutils.ErrOffset
		}
		{
			fieldSlice := buf[offset3:offset4]
			if t.Deneb, err = fn27(t.Deneb, fieldSlice); err != nil {
				return t, err
			}
			bufpos += len(fieldSlice)
		}
		// Dynamic Field #4 'Electra'
		if offset4 < bufpos || offset5 > buflen || offset5 < offset4 {
			return t, sszutils.ErrOffset
		}
		{
			fieldSlice := buf[offset4:offset5]
			if t.Electra, err = fn37(t.Electra, fieldSlice); err != nil {
				return t, err
			}
			bufpos += len(fieldSlice)
		}
		// Dynamic Field #5 'Fulu'
		if offset5 < bufpos {
			return t, sszutils.ErrOffset
		}
		{
			fieldSlice := buf[offset5:]
			if t.Fulu, err = fn37(t.Fulu, fieldSlice); err != nil {
				return t, err
			}
			bufpos += len(fieldSlice)
		}
		return t, err
	}
	_, err = fn38(t, buf)
	return err
}

func (t *VersionedBlindedBeaconBlock) HashTreeRootWith(hh sszutils.HashWalker) error {
	fn1 := func(t []*phase0.ProposerSlashing) (err error) { // []*phase0.ProposerSlashing:16
		maxLen := 16
		vlen := len(t)
		if vlen > int(maxLen) {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		for i := 0; i < vlen; i++ {
			if err = t[i].HashTreeRootWith(hh); err != nil {
				return err
			}
		}
		limit := uint64(maxLen)
		if (uint64(hh.Index()-idx)+31)/32 > limit {
			return sszutils.ErrListTooBig
		}
		hh.MerkleizeWithMixin(idx, uint64(vlen), limit)
		return err
	}
	fn2 := func(t []*phase0.AttesterSlashing) (err error) { // []*phase0.AttesterSlashing:2
		maxLen := 2
		vlen := len(t)
		if vlen > int(maxLen) {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		for i := 0; i < vlen; i++ {
			if err = t[i].HashTreeRootWith(hh); err != nil {
				return err
			}
		}
		limit := uint64(maxLen)
		if (uint64(hh.Index()-idx)+31)/32 > limit {
			return sszutils.ErrListTooBig
		}
		hh.MerkleizeWithMixin(idx, uint64(vlen), limit)
		return err
	}
	fn3 := func(t go_bitfield.Bitlist) (err error) { // bitfield.Bitlist:2048
		maxLen := uint64(2048)
		var size uint64
		var bitlist []byte
		hh.WithTemp(func(tmp []byte) []byte {
			tmp, size = hasher.ParseBitlist(tmp[:0], t[:])
			bitlist = tmp
			return tmp
		})
		if size > maxLen {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		hh.AppendBytes32(bitlist)
		hh.MerkleizeWithMixin(idx, size, (maxLen+255)/256)
		return err
	}
	fn4 := func(t *phase0.Attestation) (err error) { // *phase0.Attestation:pack
		idx := hh.Index()
		// Field #0 'AggregationBits'
		if err = fn3(t.AggregationBits); err != nil {
			return err
		}
		// Field #1 'Data'
		if err = t.Data.HashTreeRootWith(hh); err != nil {
			return err
		}
		// Field #2 'Signature'
		hh.PutBytes(t.Signature[:])
		hh.Merkleize(idx)
		return err
	}
	fn5 := func(t []*phase0.Attestation) (err error) { // []*phase0.Attestation:128
		maxLen := 128
		vlen := len(t)
		if vlen > int(maxLen) {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		for i := 0; i < vlen; i++ {
			if err = fn4(t[i]); err != nil {
				return err
			}
		}
		limit := uint64(maxLen)
		if (uint64(hh.Index()-idx)+31)/32 > limit {
			return sszutils.ErrListTooBig
		}
		hh.MerkleizeWithMixin(idx, uint64(vlen), limit)
		return err
	}
	fn6 := func(t [][]byte) (err error) { // [][]uint8:33:32
		limit := 33
		idx := hh.Index()
		vlen := len(t)
		if vlen > int(limit) {
			return sszutils.ErrVectorLength
		}
		for i := 0; i < vlen; i++ {
			hh.PutBytes(t[i][:])
		}
		for i := vlen; i < int(limit); i++ {
			hh.PutUint8(0)
		}
		hh.Merkleize(idx)
		return err
	}
	fn7 := func(t *phase0.Deposit) (err error) { // *phase0.Deposit:pack
		idx := hh.Index()
		// Field #0 'Proof'
		if err = fn6(t.Proof); err != nil {
			return err
		}
		// Field #1 'Data'
		if err = t.Data.HashTreeRootWith(hh); err != nil {
			return err
		}
		hh.Merkleize(idx)
		return err
	}
	fn8 := func(t []*phase0.Deposit) (err error) { // []*phase0.Deposit:16
		maxLen := 16
		vlen := len(t)
		if vlen > int(maxLen) {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		for i := 0; i < vlen; i++ {
			if err = fn7(t[i]); err != nil {
				return err
			}
		}
		limit := uint64(maxLen)
		if (uint64(hh.Index()-idx)+31)/32 > limit {
			return sszutils.ErrListTooBig
		}
		hh.MerkleizeWithMixin(idx, uint64(vlen), limit)
		return err
	}
	fn9 := func(t []*phase0.SignedVoluntaryExit) (err error) { // []*phase0.SignedVoluntaryExit:16
		maxLen := 16
		vlen := len(t)
		if vlen > int(maxLen) {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		for i := 0; i < vlen; i++ {
			if err = t[i].HashTreeRootWith(hh); err != nil {
				return err
			}
		}
		limit := uint64(maxLen)
		if (uint64(hh.Index()-idx)+31)/32 > limit {
			return sszutils.ErrListTooBig
		}
		hh.MerkleizeWithMixin(idx, uint64(vlen), limit)
		return err
	}
	fn10 := func(t go_bitfield.Bitvector512) (err error) { // bitfield.Bitvector512:64
		limit := 64
		if len(t) != int(limit) {
			return sszutils.ErrVectorLength
		}
		hh.PutBytes(t[:])
		return err
	}
	fn11 := func(t *altair.SyncAggregate) (err error) { // *altair.SyncAggregate
		idx := hh.Index()
		// Field #0 'SyncCommitteeBits'
		if err = fn10(t.SyncCommitteeBits); err != nil {
			return err
		}
		// Field #1 'SyncCommitteeSignature'
		hh.PutBytes(t.SyncCommitteeSignature[:])
		hh.Merkleize(idx)
		return err
	}
	fn12 := func(t *bellatrix.BlindedBeaconBlockBody) (err error) { // *bellatrix.BlindedBeaconBlockBody
		idx := hh.Index()
		// Field #0 'RANDAOReveal'
		hh.PutBytes(t.RANDAOReveal[:])
		// Field #1 'ETH1Data'
		if err = t.ETH1Data.HashTreeRootWith(hh); err != nil {
			return err
		}
		// Field #2 'Graffiti'
		hh.PutBytes(t.Graffiti[:])
		// Field #3 'ProposerSlashings'
		if err = fn1(t.ProposerSlashings); err != nil {
			return err
		}
		// Field #4 'AttesterSlashings'
		if err = fn2(t.AttesterSlashings); err != nil {
			return err
		}
		// Field #5 'Attestations'
		if err = fn5(t.Attestations); err != nil {
			return err
		}
		// Field #6 'Deposits'
		if err = fn8(t.Deposits); err != nil {
			return err
		}
		// Field #7 'VoluntaryExits'
		if err = fn9(t.VoluntaryExits); err != nil {
			return err
		}
		// Field #8 'SyncAggregate'
		if err = fn11(t.SyncAggregate); err != nil {
			return err
		}
		// Field #9 'ExecutionPayloadHeader'
		if err = t.ExecutionPayloadHeader.HashTreeRootWith(hh); err != nil {
			return err
		}
		hh.Merkleize(idx)
		return err
	}
	fn13 := func(t *bellatrix.BlindedBeaconBlock) (err error) { // *bellatrix.BlindedBeaconBlock
		idx := hh.Index()
		// Field #0 'Slot'
		hh.PutUint64(uint64(t.Slot))
		// Field #1 'ProposerIndex'
		hh.PutUint64(uint64(t.ProposerIndex))
		// Field #2 'ParentRoot'
		hh.PutBytes(t.ParentRoot[:])
		// Field #3 'StateRoot'
		hh.PutBytes(t.StateRoot[:])
		// Field #4 'Body'
		if err = fn12(t.Body); err != nil {
			return err
		}
		hh.Merkleize(idx)
		return err
	}
	fn14 := func(t []*capella1.SignedBLSToExecutionChange) (err error) { // []*capella.SignedBLSToExecutionChange:16
		maxLen := 16
		vlen := len(t)
		if vlen > int(maxLen) {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		for i := 0; i < vlen; i++ {
			if err = t[i].HashTreeRootWith(hh); err != nil {
				return err
			}
		}
		limit := uint64(maxLen)
		if (uint64(hh.Index()-idx)+31)/32 > limit {
			return sszutils.ErrListTooBig
		}
		hh.MerkleizeWithMixin(idx, uint64(vlen), limit)
		return err
	}
	fn15 := func(t *capella.BlindedBeaconBlockBody) (err error) { // *capella.BlindedBeaconBlockBody
		idx := hh.Index()
		// Field #0 'RANDAOReveal'
		hh.PutBytes(t.RANDAOReveal[:])
		// Field #1 'ETH1Data'
		if err = t.ETH1Data.HashTreeRootWith(hh); err != nil {
			return err
		}
		// Field #2 'Graffiti'
		hh.PutBytes(t.Graffiti[:])
		// Field #3 'ProposerSlashings'
		if err = fn1(t.ProposerSlashings); err != nil {
			return err
		}
		// Field #4 'AttesterSlashings'
		if err = fn2(t.AttesterSlashings); err != nil {
			return err
		}
		// Field #5 'Attestations'
		if err = fn5(t.Attestations); err != nil {
			return err
		}
		// Field #6 'Deposits'
		if err = fn8(t.Deposits); err != nil {
			return err
		}
		// Field #7 'VoluntaryExits'
		if err = fn9(t.VoluntaryExits); err != nil {
			return err
		}
		// Field #8 'SyncAggregate'
		if err = fn11(t.SyncAggregate); err != nil {
			return err
		}
		// Field #9 'ExecutionPayloadHeader'
		if err = t.ExecutionPayloadHeader.HashTreeRootWith(hh); err != nil {
			return err
		}
		// Field #10 'BLSToExecutionChanges'
		if err = fn14(t.BLSToExecutionChanges); err != nil {
			return err
		}
		hh.Merkleize(idx)
		return err
	}
	fn16 := func(t *capella.BlindedBeaconBlock) (err error) { // *capella.BlindedBeaconBlock
		idx := hh.Index()
		// Field #0 'Slot'
		hh.PutUint64(uint64(t.Slot))
		// Field #1 'ProposerIndex'
		hh.PutUint64(uint64(t.ProposerIndex))
		// Field #2 'ParentRoot'
		hh.PutBytes(t.ParentRoot[:])
		// Field #3 'StateRoot'
		hh.PutBytes(t.StateRoot[:])
		// Field #4 'Body'
		if err = fn15(t.Body); err != nil {
			return err
		}
		hh.Merkleize(idx)
		return err
	}
	fn17 := func(t []deneb1.KZGCommitment) (err error) { // []deneb.KZGCommitment:4096:48
		maxLen := 4096
		vlen := len(t)
		if vlen > int(maxLen) {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		for i := 0; i < vlen; i++ {
			hh.PutBytes(t[i][:])
		}
		limit := uint64(maxLen)
		if (uint64(hh.Index()-idx)+31)/32 > limit {
			return sszutils.ErrListTooBig
		}
		hh.MerkleizeWithMixin(idx, uint64(vlen), limit)
		return err
	}
	fn18 := func(t *deneb.BlindedBeaconBlockBody) (err error) { // *deneb.BlindedBeaconBlockBody
		idx := hh.Index()
		// Field #0 'RANDAOReveal'
		hh.PutBytes(t.RANDAOReveal[:])
		// Field #1 'ETH1Data'
		if err = t.ETH1Data.HashTreeRootWith(hh); err != nil {
			return err
		}
		// Field #2 'Graffiti'
		hh.PutBytes(t.Graffiti[:])
		// Field #3 'ProposerSlashings'
		if err = fn1(t.ProposerSlashings); err != nil {
			return err
		}
		// Field #4 'AttesterSlashings'
		if err = fn2(t.AttesterSlashings); err != nil {
			return err
		}
		// Field #5 'Attestations'
		if err = fn5(t.Attestations); err != nil {
			return err
		}
		// Field #6 'Deposits'
		if err = fn8(t.Deposits); err != nil {
			return err
		}
		// Field #7 'VoluntaryExits'
		if err = fn9(t.VoluntaryExits); err != nil {
			return err
		}
		// Field #8 'SyncAggregate'
		if err = fn11(t.SyncAggregate); err != nil {
			return err
		}
		// Field #9 'ExecutionPayloadHeader'
		if err = t.ExecutionPayloadHeader.HashTreeRootWith(hh); err != nil {
			return err
		}
		// Field #10 'BLSToExecutionChanges'
		if err = fn14(t.BLSToExecutionChanges); err != nil {
			return err
		}
		// Field #11 'BlobKZGCommitments'
		if err = fn17(t.BlobKZGCommitments); err != nil {
			return err
		}
		hh.Merkleize(idx)
		return err
	}
	fn19 := func(t *deneb.BlindedBeaconBlock) (err error) { // *deneb.BlindedBeaconBlock
		idx := hh.Index()
		// Field #0 'Slot'
		hh.PutUint64(uint64(t.Slot))
		// Field #1 'ProposerIndex'
		hh.PutUint64(uint64(t.ProposerIndex))
		// Field #2 'ParentRoot'
		hh.PutBytes(t.ParentRoot[:])
		// Field #3 'StateRoot'
		hh.PutBytes(t.StateRoot[:])
		// Field #4 'Body'
		if err = fn18(t.Body); err != nil {
			return err
		}
		hh.Merkleize(idx)
		return err
	}
	fn20 := func(t []uint64) (err error) { // []uint64:131072
		maxLen := 131072
		vlen := len(t)
		if vlen > int(maxLen) {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		for i := 0; i < vlen; i++ {
			hh.AppendUint64(uint64(t[i]))
		}
		limit := sszutils.CalculateLimit(uint64(maxLen), uint64(vlen), uint64(8))
		if (uint64(hh.Index()-idx)+31)/32 > limit {
			return sszutils.ErrListTooBig
		}
		hh.MerkleizeWithMixin(idx, uint64(vlen), limit)
		return err
	}
	fn21 := func(t *electra1.IndexedAttestation) (err error) { // *electra.IndexedAttestation
		idx := hh.Index()
		// Field #0 'AttestingIndices'
		if err = fn20(t.AttestingIndices); err != nil {
			return err
		}
		// Field #1 'Data'
		if err = t.Data.HashTreeRootWith(hh); err != nil {
			return err
		}
		// Field #2 'Signature'
		hh.PutBytes(t.Signature[:])
		hh.Merkleize(idx)
		return err
	}
	fn22 := func(t *electra1.AttesterSlashing) (err error) { // *electra.AttesterSlashing:pack
		idx := hh.Index()
		// Field #0 'Attestation1'
		if err = fn21(t.Attestation1); err != nil {
			return err
		}
		// Field #1 'Attestation2'
		if err = fn21(t.Attestation2); err != nil {
			return err
		}
		hh.Merkleize(idx)
		return err
	}
	fn23 := func(t []*electra1.AttesterSlashing) (err error) { // []*electra.AttesterSlashing:1
		maxLen := 1
		vlen := len(t)
		if vlen > int(maxLen) {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		for i := 0; i < vlen; i++ {
			if err = fn22(t[i]); err != nil {
				return err
			}
		}
		limit := uint64(maxLen)
		if (uint64(hh.Index()-idx)+31)/32 > limit {
			return sszutils.ErrListTooBig
		}
		hh.MerkleizeWithMixin(idx, uint64(vlen), limit)
		return err
	}
	fn24 := func(t go_bitfield.Bitlist) (err error) { // bitfield.Bitlist:131072
		maxLen := uint64(131072)
		var size uint64
		var bitlist []byte
		hh.WithTemp(func(tmp []byte) []byte {
			tmp, size = hasher.ParseBitlist(tmp[:0], t[:])
			bitlist = tmp
			return tmp
		})
		if size > maxLen {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		hh.AppendBytes32(bitlist)
		hh.MerkleizeWithMixin(idx, size, (maxLen+255)/256)
		return err
	}
	fn25 := func(t go_bitfield.Bitvector64) (err error) { // bitfield.Bitvector64:8
		limit := 8
		if len(t) != int(limit) {
			return sszutils.ErrVectorLength
		}
		hh.PutBytes(t[:])
		return err
	}
	fn26 := func(t *electra1.Attestation) (err error) { // *electra.Attestation:pack
		idx := hh.Index()
		// Field #0 'AggregationBits'
		if err = fn24(t.AggregationBits); err != nil {
			return err
		}
		// Field #1 'Data'
		if err = t.Data.HashTreeRootWith(hh); err != nil {
			return err
		}
		// Field #2 'Signature'
		hh.PutBytes(t.Signature[:])
		// Field #3 'CommitteeBits'
		if err = fn25(t.CommitteeBits); err != nil {
			return err
		}
		hh.Merkleize(idx)
		return err
	}
	fn27 := func(t []*electra1.Attestation) (err error) { // []*electra.Attestation:8
		maxLen := 8
		vlen := len(t)
		if vlen > int(maxLen) {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		for i := 0; i < vlen; i++ {
			if err = fn26(t[i]); err != nil {
				return err
			}
		}
		limit := uint64(maxLen)
		if (uint64(hh.Index()-idx)+31)/32 > limit {
			return sszutils.ErrListTooBig
		}
		hh.MerkleizeWithMixin(idx, uint64(vlen), limit)
		return err
	}
	fn28 := func(t []*electra1.DepositRequest) (err error) { // []*electra.DepositRequest:8192
		maxLen := 8192
		vlen := len(t)
		if vlen > int(maxLen) {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		for i := 0; i < vlen; i++ {
			if err = t[i].HashTreeRootWith(hh); err != nil {
				return err
			}
		}
		limit := uint64(maxLen)
		if (uint64(hh.Index()-idx)+31)/32 > limit {
			return sszutils.ErrListTooBig
		}
		hh.MerkleizeWithMixin(idx, uint64(vlen), limit)
		return err
	}
	fn29 := func(t []*electra1.WithdrawalRequest) (err error) { // []*electra.WithdrawalRequest:16
		maxLen := 16
		vlen := len(t)
		if vlen > int(maxLen) {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		for i := 0; i < vlen; i++ {
			if err = t[i].HashTreeRootWith(hh); err != nil {
				return err
			}
		}
		limit := uint64(maxLen)
		if (uint64(hh.Index()-idx)+31)/32 > limit {
			return sszutils.ErrListTooBig
		}
		hh.MerkleizeWithMixin(idx, uint64(vlen), limit)
		return err
	}
	fn30 := func(t []*electra1.ConsolidationRequest) (err error) { // []*electra.ConsolidationRequest:2
		maxLen := 2
		vlen := len(t)
		if vlen > int(maxLen) {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		for i := 0; i < vlen; i++ {
			if err = t[i].HashTreeRootWith(hh); err != nil {
				return err
			}
		}
		limit := uint64(maxLen)
		if (uint64(hh.Index()-idx)+31)/32 > limit {
			return sszutils.ErrListTooBig
		}
		hh.MerkleizeWithMixin(idx, uint64(vlen), limit)
		return err
	}
	fn31 := func(t *electra1.ExecutionRequests) (err error) { // *electra.ExecutionRequests
		idx := hh.Index()
		// Field #0 'Deposits'
		if err = fn28(t.Deposits); err != nil {
			return err
		}
		// Field #1 'Withdrawals'
		if err = fn29(t.Withdrawals); err != nil {
			return err
		}
		// Field #2 'Consolidations'
		if err = fn30(t.Consolidations); err != nil {
			return err
		}
		hh.Merkleize(idx)
		return err
	}
	fn32 := func(t *electra.BlindedBeaconBlockBody) (err error) { // *electra.BlindedBeaconBlockBody
		idx := hh.Index()
		// Field #0 'RANDAOReveal'
		hh.PutBytes(t.RANDAOReveal[:])
		// Field #1 'ETH1Data'
		if err = t.ETH1Data.HashTreeRootWith(hh); err != nil {
			return err
		}
		// Field #2 'Graffiti'
		hh.PutBytes(t.Graffiti[:])
		// Field #3 'ProposerSlashings'
		if err = fn1(t.ProposerSlashings); err != nil {
			return err
		}
		// Field #4 'AttesterSlashings'
		if err = fn23(t.AttesterSlashings); err != nil {
			return err
		}
		// Field #5 'Attestations'
		if err = fn27(t.Attestations); err != nil {
			return err
		}
		// Field #6 'Deposits'
		if err = fn8(t.Deposits); err != nil {
			return err
		}
		// Field #7 'VoluntaryExits'
		if err = fn9(t.VoluntaryExits); err != nil {
			return err
		}
		// Field #8 'SyncAggregate'
		if err = fn11(t.SyncAggregate); err != nil {
			return err
		}
		// Field #9 'ExecutionPayloadHeader'
		if err = t.ExecutionPayloadHeader.HashTreeRootWith(hh); err != nil {
			return err
		}
		// Field #10 'BLSToExecutionChanges'
		if err = fn14(t.BLSToExecutionChanges); err != nil {
			return err
		}
		// Field #11 'BlobKZGCommitments'
		if err = fn17(t.BlobKZGCommitments); err != nil {
			return err
		}
		// Field #12 'ExecutionRequests'
		if err = fn31(t.ExecutionRequests); err != nil {
			return err
		}
		hh.Merkleize(idx)
		return err
	}
	fn33 := func(t *electra.BlindedBeaconBlock) (err error) { // *electra.BlindedBeaconBlock
		idx := hh.Index()
		// Field #0 'Slot'
		hh.PutUint64(uint64(t.Slot))
		// Field #1 'ProposerIndex'
		hh.PutUint64(uint64(t.ProposerIndex))
		// Field #2 'ParentRoot'
		hh.PutBytes(t.ParentRoot[:])
		// Field #3 'StateRoot'
		hh.PutBytes(t.StateRoot[:])
		// Field #4 'Body'
		if err = fn32(t.Body); err != nil {
			return err
		}
		hh.Merkleize(idx)
		return err
	}
	fn34 := func(t *VersionedBlindedBeaconBlock) (err error) { // *api.VersionedBlindedBeaconBlock
		idx := hh.Index()
		// Field #0 'Version'
		hh.PutUint64(uint64(t.Version))
		// Field #1 'Bellatrix'
		if err = fn13(t.Bellatrix); err != nil {
			return err
		}
		// Field #2 'Capella'
		if err = fn16(t.Capella); err != nil {
			return err
		}
		// Field #3 'Deneb'
		if err = fn19(t.Deneb); err != nil {
			return err
		}
		// Field #4 'Electra'
		if err = fn33(t.Electra); err != nil {
			return err
		}
		// Field #5 'Fulu'
		if err = fn33(t.Fulu); err != nil {
			return err
		}
		hh.Merkleize(idx)
		return err
	}
	return fn34(t)
}
func (t *VersionedBlindedBeaconBlock) HashTreeRoot() ([32]byte, error) {
	pool := &hasher.FastHasherPool
	hh := pool.Get()
	defer func() {
		pool.Put(hh)
	}()
	if err := t.HashTreeRootWith(hh); err != nil {
		return [32]byte{}, err
	}
	r, _ := hh.HashRoot()
	return r, nil
}
