name: revive
on:
  push:
    branches:
    - master
  pull_request:

permissions:
  contents: read

jobs:
  revive:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-go@v5
        with:
          cache: false
          go-version: '1.21'
      - uses: actions/checkout@v4
      - uses: morphy2k/revive-action@v2
