name: test
on:
  push:
    branches:
    - master
  pull_request:
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-go@v5
        with:
          cache: false
          go-version: '1.21'
      - uses: actions/checkout@v4
      - uses: n8maninger/action-golang-test@v2
        with:
          args: "-race;-timeout=30m"

